name: Get diff in submodule to decide testing

description: ""

inputs:
  submod-name:
    description: ""
    required: true
    default: struphy-parameter-files

runs:
  using: composite
  steps:
    - name: Check for changes in submodule
      shell: bash
      # the following compares the base branch to the current head of the feature branch (I verified)!
      run: |
        git diff --name-only HEAD~1 HEAD 
        if git diff --name-only HEAD~1 HEAD -- ${{ inputs.submod-name }} | grep -q .; then
          echo "SUBMOD_CHANGED=true" >> $GITHUB_ENV
          echo "SUBMOD_NAME=${{ inputs.submod-name }}" >> $GITHUB_ENV
          exit 0
        fi