name: "Install MacOS prereqs"

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        brew update
        # brew install python3
        brew install gcc
        brew install openblas
        brew install lapack
        brew install open-mpi
        brew install pkgconf
        brew install libomp
        brew install git
        brew install pandoc
        brew install hdf5
        brew install netcdf-fortran
        brew install cmake
        brew link --overwrite cmake
        cmake --version 
        make -v
        system_profiler SPHardwareDataType
        which gfortran || echo "could not find gfortran"
        which gcc || echo "could not find gcc"
        which g++ || echo "could not find g++"
        # Update environment variables
        echo "FC=$(which gfortran)" >> $GITHUB_ENV # for gvec
        echo "CC=$(which gcc)" >> $GITHUB_ENV # for gvec
        echo "CXX=$(which g++)" >> $GITHUB_ENV # for gvec
        echo "----------------"
        
