name: "Compile kernels with pyccel"

runs:
  using: composite
  steps:
    - name: Checkout pyccel version
      shell: bash
      run: |
        pyccel --version

    - name: Compile kernels
      shell: bash
      run: |
        struphy compile --status
        struphy compile -y --language ${{ matrix.compile-language }} || (
          echo "Initial compile failed. Removing compiled kernels and trying again..." &&
          struphy compile -d -y &&
          struphy compile -y --language ${{ matrix.compile-language }}
        )
