name: "Compile kernels with pyccel"

description: 

inputs:
  language:
    required: true
    default: fortran

runs:
  using: composite
  steps:
    - name: Checkout pyccel version
      shell: bash
      run: |
        pyccel --version

    - name: Compile kernels
      shell: bash
      run: |
        struphy compile -d -y
        struphy compile -y --language ${{ inputs.language }} || (
          echo "Initial compile failed. Removing compiled kernels and trying again..." &&
          struphy compile -d -y &&
          struphy compile -y --language ${{ inputs.language }}
        )
