name: Set environment variables for mpi unit tests

description: 

inputs:
  n-procs:
    default: 2

runs:
  using: composite
  steps:
    - name: set and export variables
      shell: bash
      run: |
        TESTMON_KEY="testmon-unit-mpi"
        RUN_MAXWELL="mpirun -n 1 pytest -m single --testmon-forceselect -s --with-mpi --model-name Maxwell"
        PYTEST_CMD="mpirun -n ${{ inputs.n-procs }} pytest --testmon --with-mpi ${{ env.TEST_FILES }}"
        echo "TESTMON_KEY=${TESTMON_KEY}" >> $GITHUB_ENV
        echo "RUN_MAXWELL=${RUN_MAXWELL}" >> $GITHUB_ENV
        echo "PYTEST_CMD=${PYTEST_CMD}" >> $GITHUB_ENV