/* File: STRUPHY_pushermodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Feb 17 14:58:41 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *STRUPHY_pusher_error;
static PyObject *STRUPHY_pusher_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(STRUPHY_pusher_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = STRUPHY_pusher_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = STRUPHY_pusher_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(mapping_matrices,MAPPING_MATRICES)(int*,double*,int*,int*,double*,int*,int*,int*,double*);
extern void F_FUNC_US(matrix_vector,MATRIX_VECTOR)(int*,int*,double*,int*,double*,int*,double*);
extern void F_FUNC_US(matrix_matrix,MATRIX_MATRIX)(int*,int*,double*,int*,int*,double*,int*,int*,double*);
extern void F_FUNC(transpose,TRANSPOSE)(int*,int*,double*,int*,int*,double*);
extern double F_FUNC(det,DET)(int*,int*,double*);
extern void F_FUNC_US(pusher_step3,PUSHER_STEP3)(int*,int*,double*,int*,double*,double*,int*,int*,double*,int*,int*,double*);
extern void F_FUNC_US(pusher_step4,PUSHER_STEP4)(int*,int*,double*,int*,double*,double*);
extern void F_FUNC_US(pusher_step5,PUSHER_STEP5)(int*,int*,double*,int*,double*,double*,int*,int*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/****************************** mapping_matrices ******************************/
static char doc_f2py_rout_STRUPHY_pusher_mapping_matrices[] = "\
mapping_matrices(q,kind,params,output,a,[n0_q,n0_params,n0_a,n1_a])\n\nWrapper for ``mapping_matrices``.\
\n\nParameters\n----------\n"
"q : input rank-1 array('d') with bounds (n0_q)\n"
"kind : input int\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"output : input int\n"
"a : in/output rank-2 array('d') with bounds (n0_a,n1_a)\n"
"\nOther Parameters\n----------------\n"
"n0_q : input int, optional\n    Default: len(q)\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"n0_a : input int, optional\n    Default: shape(a,0)\n"
"n1_a : input int, optional\n    Default: shape(a,1)";
/* extern void F_FUNC_US(mapping_matrices,MAPPING_MATRICES)(int*,double*,int*,int*,double*,int*,int*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_mapping_matrices(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,double*,int*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_q = 0;
  PyObject *n0_q_capi = Py_None;
  double *q = NULL;
  npy_intp q_Dims[1] = {-1};
  const int q_Rank = 1;
  PyArrayObject *capi_q_tmp = NULL;
  int capi_q_intent = 0;
  PyObject *q_capi = Py_None;
  int kind = 0;
  PyObject *kind_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  int output = 0;
  PyObject *output_capi = Py_None;
  int n0_a = 0;
  PyObject *n0_a_capi = Py_None;
  int n1_a = 0;
  PyObject *n1_a_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  static char *capi_kwlist[] = {"q","kind","params","output","a","n0_q","n0_params","n0_a","n1_a",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOOO:STRUPHY_pusher.mapping_matrices",\
    capi_kwlist,&q_capi,&kind_capi,&params_capi,&output_capi,&a_capi,&n0_q_capi,&n0_params_capi,&n0_a_capi,&n1_a_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable q */
  ;
  capi_q_intent |= F2PY_INTENT_IN;
  capi_q_tmp = array_from_pyobj(NPY_DOUBLE,q_Dims,q_Rank,capi_q_intent,q_capi);
  if (capi_q_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `q' of STRUPHY_pusher.mapping_matrices to C/Fortran array" );
  } else {
    q = (double *)(PyArray_DATA(capi_q_tmp));

  /* Processing variable output */
    f2py_success = int_from_pyobj(&output,output_capi,"STRUPHY_pusher.mapping_matrices() 4th argument (output) can't be converted to int");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 3rd argument `params' of STRUPHY_pusher.mapping_matrices to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable kind */
    f2py_success = int_from_pyobj(&kind,kind_capi,"STRUPHY_pusher.mapping_matrices() 2nd argument (kind) can't be converted to int");
  if (f2py_success) {
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_INOUT;
  capi_a_tmp = array_from_pyobj(NPY_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 5th argument `a' of STRUPHY_pusher.mapping_matrices to C/Fortran array" );
  } else {
    a = (double *)(PyArray_DATA(capi_a_tmp));

  /* Processing variable n0_q */
  if (n0_q_capi == Py_None) n0_q = len(q); else
    f2py_success = int_from_pyobj(&n0_q,n0_q_capi,"STRUPHY_pusher.mapping_matrices() 1st keyword (n0_q) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(q)>=n0_q,"len(q)>=n0_q","1st keyword n0_q","mapping_matrices:n0_q=%d",n0_q) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"STRUPHY_pusher.mapping_matrices() 2nd keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","2nd keyword n0_params","mapping_matrices:n0_params=%d",n0_params) {
  /* Processing variable n0_a */
  if (n0_a_capi == Py_None) n0_a = shape(a,0); else
    f2py_success = int_from_pyobj(&n0_a,n0_a_capi,"STRUPHY_pusher.mapping_matrices() 3rd keyword (n0_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,0)==n0_a,"shape(a,0)==n0_a","3rd keyword n0_a","mapping_matrices:n0_a=%d",n0_a) {
  /* Processing variable n1_a */
  if (n1_a_capi == Py_None) n1_a = shape(a,1); else
    f2py_success = int_from_pyobj(&n1_a,n1_a_capi,"STRUPHY_pusher.mapping_matrices() 4th keyword (n1_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,1)==n1_a,"shape(a,1)==n1_a","4th keyword n1_a","mapping_matrices:n1_a=%d",n1_a) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_q,q,&kind,&n0_params,params,&output,&n0_a,&n1_a,a);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(a,1)==n1_a)*/
  } /*if (f2py_success) of n1_a*/
  /* End of cleaning variable n1_a */
  } /*CHECKSCALAR(shape(a,0)==n0_a)*/
  } /*if (f2py_success) of n0_a*/
  /* End of cleaning variable n0_a */
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*CHECKSCALAR(len(q)>=n0_q)*/
  } /*if (f2py_success) of n0_q*/
  /* End of cleaning variable n0_q */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
  } /*if (f2py_success) of kind*/
  /* End of cleaning variable kind */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of output*/
  /* End of cleaning variable output */
  if((PyObject *)capi_q_tmp!=q_capi) {
    Py_XDECREF(capi_q_tmp); }
  }  /*if (capi_q_tmp == NULL) ... else of q*/
  /* End of cleaning variable q */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of mapping_matrices **************************/

/******************************* matrix_vector *******************************/
static char doc_f2py_rout_STRUPHY_pusher_matrix_vector[] = "\
matrix_vector(a,b,c,[n0_a,n1_a,n0_b,n0_c])\n\nWrapper for ``matrix_vector``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (n0_a,n1_a)\n"
"b : input rank-1 array('d') with bounds (n0_b)\n"
"c : in/output rank-1 array('d') with bounds (n0_c)\n"
"\nOther Parameters\n----------------\n"
"n0_a : input int, optional\n    Default: shape(a,0)\n"
"n1_a : input int, optional\n    Default: shape(a,1)\n"
"n0_b : input int, optional\n    Default: len(b)\n"
"n0_c : input int, optional\n    Default: len(c)";
/* extern void F_FUNC_US(matrix_vector,MATRIX_VECTOR)(int*,int*,double*,int*,double*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_matrix_vector(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,double*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_a = 0;
  PyObject *n0_a_capi = Py_None;
  int n1_a = 0;
  PyObject *n1_a_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int n0_b = 0;
  PyObject *n0_b_capi = Py_None;
  double *b = NULL;
  npy_intp b_Dims[1] = {-1};
  const int b_Rank = 1;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  int n0_c = 0;
  PyObject *n0_c_capi = Py_None;
  double *c = NULL;
  npy_intp c_Dims[1] = {-1};
  const int c_Rank = 1;
  PyArrayObject *capi_c_tmp = NULL;
  int capi_c_intent = 0;
  PyObject *c_capi = Py_None;
  static char *capi_kwlist[] = {"a","b","c","n0_a","n1_a","n0_b","n0_c",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OOOO:STRUPHY_pusher.matrix_vector",\
    capi_kwlist,&a_capi,&b_capi,&c_capi,&n0_a_capi,&n1_a_capi,&n0_b_capi,&n0_c_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable c */
  ;
  capi_c_intent |= F2PY_INTENT_INOUT;
  capi_c_tmp = array_from_pyobj(NPY_DOUBLE,c_Dims,c_Rank,capi_c_intent,c_capi);
  if (capi_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 3rd argument `c' of STRUPHY_pusher.matrix_vector to C/Fortran array" );
  } else {
    c = (double *)(PyArray_DATA(capi_c_tmp));

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 2nd argument `b' of STRUPHY_pusher.matrix_vector to C/Fortran array" );
  } else {
    b = (double *)(PyArray_DATA(capi_b_tmp));

  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `a' of STRUPHY_pusher.matrix_vector to C/Fortran array" );
  } else {
    a = (double *)(PyArray_DATA(capi_a_tmp));

  /* Processing variable n0_c */
  if (n0_c_capi == Py_None) n0_c = len(c); else
    f2py_success = int_from_pyobj(&n0_c,n0_c_capi,"STRUPHY_pusher.matrix_vector() 4th keyword (n0_c) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(c)>=n0_c,"len(c)>=n0_c","4th keyword n0_c","matrix_vector:n0_c=%d",n0_c) {
  /* Processing variable n0_a */
  if (n0_a_capi == Py_None) n0_a = shape(a,0); else
    f2py_success = int_from_pyobj(&n0_a,n0_a_capi,"STRUPHY_pusher.matrix_vector() 1st keyword (n0_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,0)==n0_a,"shape(a,0)==n0_a","1st keyword n0_a","matrix_vector:n0_a=%d",n0_a) {
  /* Processing variable n1_a */
  if (n1_a_capi == Py_None) n1_a = shape(a,1); else
    f2py_success = int_from_pyobj(&n1_a,n1_a_capi,"STRUPHY_pusher.matrix_vector() 2nd keyword (n1_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,1)==n1_a,"shape(a,1)==n1_a","2nd keyword n1_a","matrix_vector:n1_a=%d",n1_a) {
  /* Processing variable n0_b */
  if (n0_b_capi == Py_None) n0_b = len(b); else
    f2py_success = int_from_pyobj(&n0_b,n0_b_capi,"STRUPHY_pusher.matrix_vector() 3rd keyword (n0_b) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(b)>=n0_b,"len(b)>=n0_b","3rd keyword n0_b","matrix_vector:n0_b=%d",n0_b) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_a,&n1_a,a,&n0_b,b,&n0_c,c);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(b)>=n0_b)*/
  } /*if (f2py_success) of n0_b*/
  /* End of cleaning variable n0_b */
  } /*CHECKSCALAR(shape(a,1)==n1_a)*/
  } /*if (f2py_success) of n1_a*/
  /* End of cleaning variable n1_a */
  } /*CHECKSCALAR(shape(a,0)==n0_a)*/
  } /*if (f2py_success) of n0_a*/
  /* End of cleaning variable n0_a */
  } /*CHECKSCALAR(len(c)>=n0_c)*/
  } /*if (f2py_success) of n0_c*/
  /* End of cleaning variable n0_c */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_c_tmp!=c_capi) {
    Py_XDECREF(capi_c_tmp); }
  }  /*if (capi_c_tmp == NULL) ... else of c*/
  /* End of cleaning variable c */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of matrix_vector ****************************/

/******************************* matrix_matrix *******************************/
static char doc_f2py_rout_STRUPHY_pusher_matrix_matrix[] = "\
matrix_matrix(a,b,c,[n0_a,n1_a,n0_b,n1_b,n0_c,n1_c])\n\nWrapper for ``matrix_matrix``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (n0_a,n1_a)\n"
"b : input rank-2 array('d') with bounds (n0_b,n1_b)\n"
"c : in/output rank-2 array('d') with bounds (n0_c,n1_c)\n"
"\nOther Parameters\n----------------\n"
"n0_a : input int, optional\n    Default: shape(a,0)\n"
"n1_a : input int, optional\n    Default: shape(a,1)\n"
"n0_b : input int, optional\n    Default: shape(b,0)\n"
"n1_b : input int, optional\n    Default: shape(b,1)\n"
"n0_c : input int, optional\n    Default: shape(c,0)\n"
"n1_c : input int, optional\n    Default: shape(c,1)";
/* extern void F_FUNC_US(matrix_matrix,MATRIX_MATRIX)(int*,int*,double*,int*,int*,double*,int*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_matrix_matrix(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,int*,double*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_a = 0;
  PyObject *n0_a_capi = Py_None;
  int n1_a = 0;
  PyObject *n1_a_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int n0_b = 0;
  PyObject *n0_b_capi = Py_None;
  int n1_b = 0;
  PyObject *n1_b_capi = Py_None;
  double *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  int n0_c = 0;
  PyObject *n0_c_capi = Py_None;
  int n1_c = 0;
  PyObject *n1_c_capi = Py_None;
  double *c = NULL;
  npy_intp c_Dims[2] = {-1, -1};
  const int c_Rank = 2;
  PyArrayObject *capi_c_tmp = NULL;
  int capi_c_intent = 0;
  PyObject *c_capi = Py_None;
  static char *capi_kwlist[] = {"a","b","c","n0_a","n1_a","n0_b","n1_b","n0_c","n1_c",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OOOOOO:STRUPHY_pusher.matrix_matrix",\
    capi_kwlist,&a_capi,&b_capi,&c_capi,&n0_a_capi,&n1_a_capi,&n0_b_capi,&n1_b_capi,&n0_c_capi,&n1_c_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 2nd argument `b' of STRUPHY_pusher.matrix_matrix to C/Fortran array" );
  } else {
    b = (double *)(PyArray_DATA(capi_b_tmp));

  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `a' of STRUPHY_pusher.matrix_matrix to C/Fortran array" );
  } else {
    a = (double *)(PyArray_DATA(capi_a_tmp));

  /* Processing variable c */
  ;
  capi_c_intent |= F2PY_INTENT_INOUT;
  capi_c_tmp = array_from_pyobj(NPY_DOUBLE,c_Dims,c_Rank,capi_c_intent,c_capi);
  if (capi_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 3rd argument `c' of STRUPHY_pusher.matrix_matrix to C/Fortran array" );
  } else {
    c = (double *)(PyArray_DATA(capi_c_tmp));

  /* Processing variable n0_c */
  if (n0_c_capi == Py_None) n0_c = shape(c,0); else
    f2py_success = int_from_pyobj(&n0_c,n0_c_capi,"STRUPHY_pusher.matrix_matrix() 5th keyword (n0_c) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(c,0)==n0_c,"shape(c,0)==n0_c","5th keyword n0_c","matrix_matrix:n0_c=%d",n0_c) {
  /* Processing variable n1_c */
  if (n1_c_capi == Py_None) n1_c = shape(c,1); else
    f2py_success = int_from_pyobj(&n1_c,n1_c_capi,"STRUPHY_pusher.matrix_matrix() 6th keyword (n1_c) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(c,1)==n1_c,"shape(c,1)==n1_c","6th keyword n1_c","matrix_matrix:n1_c=%d",n1_c) {
  /* Processing variable n1_b */
  if (n1_b_capi == Py_None) n1_b = shape(b,1); else
    f2py_success = int_from_pyobj(&n1_b,n1_b_capi,"STRUPHY_pusher.matrix_matrix() 4th keyword (n1_b) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,1)==n1_b,"shape(b,1)==n1_b","4th keyword n1_b","matrix_matrix:n1_b=%d",n1_b) {
  /* Processing variable n0_b */
  if (n0_b_capi == Py_None) n0_b = shape(b,0); else
    f2py_success = int_from_pyobj(&n0_b,n0_b_capi,"STRUPHY_pusher.matrix_matrix() 3rd keyword (n0_b) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,0)==n0_b,"shape(b,0)==n0_b","3rd keyword n0_b","matrix_matrix:n0_b=%d",n0_b) {
  /* Processing variable n1_a */
  if (n1_a_capi == Py_None) n1_a = shape(a,1); else
    f2py_success = int_from_pyobj(&n1_a,n1_a_capi,"STRUPHY_pusher.matrix_matrix() 2nd keyword (n1_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,1)==n1_a,"shape(a,1)==n1_a","2nd keyword n1_a","matrix_matrix:n1_a=%d",n1_a) {
  /* Processing variable n0_a */
  if (n0_a_capi == Py_None) n0_a = shape(a,0); else
    f2py_success = int_from_pyobj(&n0_a,n0_a_capi,"STRUPHY_pusher.matrix_matrix() 1st keyword (n0_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,0)==n0_a,"shape(a,0)==n0_a","1st keyword n0_a","matrix_matrix:n0_a=%d",n0_a) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_a,&n1_a,a,&n0_b,&n1_b,b,&n0_c,&n1_c,c);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(a,0)==n0_a)*/
  } /*if (f2py_success) of n0_a*/
  /* End of cleaning variable n0_a */
  } /*CHECKSCALAR(shape(a,1)==n1_a)*/
  } /*if (f2py_success) of n1_a*/
  /* End of cleaning variable n1_a */
  } /*CHECKSCALAR(shape(b,0)==n0_b)*/
  } /*if (f2py_success) of n0_b*/
  /* End of cleaning variable n0_b */
  } /*CHECKSCALAR(shape(b,1)==n1_b)*/
  } /*if (f2py_success) of n1_b*/
  /* End of cleaning variable n1_b */
  } /*CHECKSCALAR(shape(c,1)==n1_c)*/
  } /*if (f2py_success) of n1_c*/
  /* End of cleaning variable n1_c */
  } /*CHECKSCALAR(shape(c,0)==n0_c)*/
  } /*if (f2py_success) of n0_c*/
  /* End of cleaning variable n0_c */
  if((PyObject *)capi_c_tmp!=c_capi) {
    Py_XDECREF(capi_c_tmp); }
  }  /*if (capi_c_tmp == NULL) ... else of c*/
  /* End of cleaning variable c */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of matrix_matrix ****************************/

/********************************* transpose *********************************/
static char doc_f2py_rout_STRUPHY_pusher_transpose[] = "\
transpose(a,b,[n0_a,n1_a,n0_b,n1_b])\n\nWrapper for ``transpose``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (n0_a,n1_a)\n"
"b : in/output rank-2 array('d') with bounds (n0_b,n1_b)\n"
"\nOther Parameters\n----------------\n"
"n0_a : input int, optional\n    Default: shape(a,0)\n"
"n1_a : input int, optional\n    Default: shape(a,1)\n"
"n0_b : input int, optional\n    Default: shape(b,0)\n"
"n1_b : input int, optional\n    Default: shape(b,1)";
/* extern void F_FUNC(transpose,TRANSPOSE)(int*,int*,double*,int*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_transpose(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_a = 0;
  PyObject *n0_a_capi = Py_None;
  int n1_a = 0;
  PyObject *n1_a_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int n0_b = 0;
  PyObject *n0_b_capi = Py_None;
  int n1_b = 0;
  PyObject *n1_b_capi = Py_None;
  double *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  static char *capi_kwlist[] = {"a","b","n0_a","n1_a","n0_b","n1_b",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|OOOO:STRUPHY_pusher.transpose",\
    capi_kwlist,&a_capi,&b_capi,&n0_a_capi,&n1_a_capi,&n0_b_capi,&n1_b_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `a' of STRUPHY_pusher.transpose to C/Fortran array" );
  } else {
    a = (double *)(PyArray_DATA(capi_a_tmp));

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_INOUT;
  capi_b_tmp = array_from_pyobj(NPY_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 2nd argument `b' of STRUPHY_pusher.transpose to C/Fortran array" );
  } else {
    b = (double *)(PyArray_DATA(capi_b_tmp));

  /* Processing variable n0_a */
  if (n0_a_capi == Py_None) n0_a = shape(a,0); else
    f2py_success = int_from_pyobj(&n0_a,n0_a_capi,"STRUPHY_pusher.transpose() 1st keyword (n0_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,0)==n0_a,"shape(a,0)==n0_a","1st keyword n0_a","transpose:n0_a=%d",n0_a) {
  /* Processing variable n0_b */
  if (n0_b_capi == Py_None) n0_b = shape(b,0); else
    f2py_success = int_from_pyobj(&n0_b,n0_b_capi,"STRUPHY_pusher.transpose() 3rd keyword (n0_b) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,0)==n0_b,"shape(b,0)==n0_b","3rd keyword n0_b","transpose:n0_b=%d",n0_b) {
  /* Processing variable n1_a */
  if (n1_a_capi == Py_None) n1_a = shape(a,1); else
    f2py_success = int_from_pyobj(&n1_a,n1_a_capi,"STRUPHY_pusher.transpose() 2nd keyword (n1_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,1)==n1_a,"shape(a,1)==n1_a","2nd keyword n1_a","transpose:n1_a=%d",n1_a) {
  /* Processing variable n1_b */
  if (n1_b_capi == Py_None) n1_b = shape(b,1); else
    f2py_success = int_from_pyobj(&n1_b,n1_b_capi,"STRUPHY_pusher.transpose() 4th keyword (n1_b) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,1)==n1_b,"shape(b,1)==n1_b","4th keyword n1_b","transpose:n1_b=%d",n1_b) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_a,&n1_a,a,&n0_b,&n1_b,b);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(b,1)==n1_b)*/
  } /*if (f2py_success) of n1_b*/
  /* End of cleaning variable n1_b */
  } /*CHECKSCALAR(shape(a,1)==n1_a)*/
  } /*if (f2py_success) of n1_a*/
  /* End of cleaning variable n1_a */
  } /*CHECKSCALAR(shape(b,0)==n0_b)*/
  } /*if (f2py_success) of n0_b*/
  /* End of cleaning variable n0_b */
  } /*CHECKSCALAR(shape(a,0)==n0_a)*/
  } /*if (f2py_success) of n0_a*/
  /* End of cleaning variable n0_a */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of transpose ******************************/

/************************************ det ************************************/
static char doc_f2py_rout_STRUPHY_pusher_det[] = "\
dummy_4220 = det(a,[n0_a,n1_a])\n\nWrapper for ``det``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (n0_a,n1_a)\n"
"\nOther Parameters\n----------------\n"
"n0_a : input int, optional\n    Default: shape(a,0)\n"
"n1_a : input int, optional\n    Default: shape(a,1)\n"
"\nReturns\n-------\n"
"dummy_4220 : float";
/* extern double F_FUNC(det,DET)(int*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_det(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double det_return_value=0;
  int n0_a = 0;
  PyObject *n0_a_capi = Py_None;
  int n1_a = 0;
  PyObject *n1_a_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  static char *capi_kwlist[] = {"a","n0_a","n1_a",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|OO:STRUPHY_pusher.det",\
    capi_kwlist,&a_capi,&n0_a_capi,&n1_a_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `a' of STRUPHY_pusher.det to C/Fortran array" );
  } else {
    a = (double *)(PyArray_DATA(capi_a_tmp));

  /* Processing variable n0_a */
  if (n0_a_capi == Py_None) n0_a = shape(a,0); else
    f2py_success = int_from_pyobj(&n0_a,n0_a_capi,"STRUPHY_pusher.det() 1st keyword (n0_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,0)==n0_a,"shape(a,0)==n0_a","1st keyword n0_a","det:n0_a=%d",n0_a) {
  /* Processing variable n1_a */
  if (n1_a_capi == Py_None) n1_a = shape(a,1); else
    f2py_success = int_from_pyobj(&n1_a,n1_a_capi,"STRUPHY_pusher.det() 2nd keyword (n1_a) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,1)==n1_a,"shape(a,1)==n1_a","2nd keyword n1_a","det:n1_a=%d",n1_a) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  det_return_value = (*f2py_func)(&n0_a,&n1_a,a);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",det_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(a,1)==n1_a)*/
  } /*if (f2py_success) of n1_a*/
  /* End of cleaning variable n1_a */
  } /*CHECKSCALAR(shape(a,0)==n0_a)*/
  } /*if (f2py_success) of n0_a*/
  /* End of cleaning variable n0_a */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of det *********************************/

/******************************** pusher_step3 ********************************/
static char doc_f2py_rout_STRUPHY_pusher_pusher_step3[] = "\
pusher_step3(particles,mapping,dt,b_part,u_part,[n0_particles,n1_particles,n0_mapping,n0_b_part,n1_b_part,n0_u_part,n1_u_part])\n\nWrapper for ``pusher_step3``.\
\n\nParameters\n----------\n"
"particles : in/output rank-2 array('d') with bounds (n0_particles,n1_particles)\n"
"mapping : input rank-1 array('d') with bounds (n0_mapping)\n"
"dt : input float\n"
"b_part : input rank-2 array('d') with bounds (n0_b_part,n1_b_part)\n"
"u_part : input rank-2 array('d') with bounds (n0_u_part,n1_u_part)\n"
"\nOther Parameters\n----------------\n"
"n0_particles : input int, optional\n    Default: shape(particles,0)\n"
"n1_particles : input int, optional\n    Default: shape(particles,1)\n"
"n0_mapping : input int, optional\n    Default: len(mapping)\n"
"n0_b_part : input int, optional\n    Default: shape(b_part,0)\n"
"n1_b_part : input int, optional\n    Default: shape(b_part,1)\n"
"n0_u_part : input int, optional\n    Default: shape(u_part,0)\n"
"n1_u_part : input int, optional\n    Default: shape(u_part,1)";
/* extern void F_FUNC_US(pusher_step3,PUSHER_STEP3)(int*,int*,double*,int*,double*,double*,int*,int*,double*,int*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_pusher_step3(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,double*,double*,int*,int*,double*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles = 0;
  PyObject *n0_particles_capi = Py_None;
  int n1_particles = 0;
  PyObject *n1_particles_capi = Py_None;
  double *particles = NULL;
  npy_intp particles_Dims[2] = {-1, -1};
  const int particles_Rank = 2;
  PyArrayObject *capi_particles_tmp = NULL;
  int capi_particles_intent = 0;
  PyObject *particles_capi = Py_None;
  int n0_mapping = 0;
  PyObject *n0_mapping_capi = Py_None;
  double *mapping = NULL;
  npy_intp mapping_Dims[1] = {-1};
  const int mapping_Rank = 1;
  PyArrayObject *capi_mapping_tmp = NULL;
  int capi_mapping_intent = 0;
  PyObject *mapping_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  int n0_b_part = 0;
  PyObject *n0_b_part_capi = Py_None;
  int n1_b_part = 0;
  PyObject *n1_b_part_capi = Py_None;
  double *b_part = NULL;
  npy_intp b_part_Dims[2] = {-1, -1};
  const int b_part_Rank = 2;
  PyArrayObject *capi_b_part_tmp = NULL;
  int capi_b_part_intent = 0;
  PyObject *b_part_capi = Py_None;
  int n0_u_part = 0;
  PyObject *n0_u_part_capi = Py_None;
  int n1_u_part = 0;
  PyObject *n1_u_part_capi = Py_None;
  double *u_part = NULL;
  npy_intp u_part_Dims[2] = {-1, -1};
  const int u_part_Rank = 2;
  PyArrayObject *capi_u_part_tmp = NULL;
  int capi_u_part_intent = 0;
  PyObject *u_part_capi = Py_None;
  static char *capi_kwlist[] = {"particles","mapping","dt","b_part","u_part","n0_particles","n1_particles","n0_mapping","n0_b_part","n1_b_part","n0_u_part","n1_u_part",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOOOOOO:STRUPHY_pusher.pusher_step3",\
    capi_kwlist,&particles_capi,&mapping_capi,&dt_capi,&b_part_capi,&u_part_capi,&n0_particles_capi,&n1_particles_capi,&n0_mapping_capi,&n0_b_part_capi,&n1_b_part_capi,&n0_u_part_capi,&n1_u_part_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable u_part */
  ;
  capi_u_part_intent |= F2PY_INTENT_IN;
  capi_u_part_tmp = array_from_pyobj(NPY_DOUBLE,u_part_Dims,u_part_Rank,capi_u_part_intent,u_part_capi);
  if (capi_u_part_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 5th argument `u_part' of STRUPHY_pusher.pusher_step3 to C/Fortran array" );
  } else {
    u_part = (double *)(PyArray_DATA(capi_u_part_tmp));

  /* Processing variable particles */
  ;
  capi_particles_intent |= F2PY_INTENT_INOUT;
  capi_particles_tmp = array_from_pyobj(NPY_DOUBLE,particles_Dims,particles_Rank,capi_particles_intent,particles_capi);
  if (capi_particles_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `particles' of STRUPHY_pusher.pusher_step3 to C/Fortran array" );
  } else {
    particles = (double *)(PyArray_DATA(capi_particles_tmp));

  /* Processing variable b_part */
  ;
  capi_b_part_intent |= F2PY_INTENT_IN;
  capi_b_part_tmp = array_from_pyobj(NPY_DOUBLE,b_part_Dims,b_part_Rank,capi_b_part_intent,b_part_capi);
  if (capi_b_part_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 4th argument `b_part' of STRUPHY_pusher.pusher_step3 to C/Fortran array" );
  } else {
    b_part = (double *)(PyArray_DATA(capi_b_part_tmp));

  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"STRUPHY_pusher.pusher_step3() 3rd argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable mapping */
  ;
  capi_mapping_intent |= F2PY_INTENT_IN;
  capi_mapping_tmp = array_from_pyobj(NPY_DOUBLE,mapping_Dims,mapping_Rank,capi_mapping_intent,mapping_capi);
  if (capi_mapping_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 2nd argument `mapping' of STRUPHY_pusher.pusher_step3 to C/Fortran array" );
  } else {
    mapping = (double *)(PyArray_DATA(capi_mapping_tmp));

  /* Processing variable n0_b_part */
  if (n0_b_part_capi == Py_None) n0_b_part = shape(b_part,0); else
    f2py_success = int_from_pyobj(&n0_b_part,n0_b_part_capi,"STRUPHY_pusher.pusher_step3() 4th keyword (n0_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,0)==n0_b_part,"shape(b_part,0)==n0_b_part","4th keyword n0_b_part","pusher_step3:n0_b_part=%d",n0_b_part) {
  /* Processing variable n0_particles */
  if (n0_particles_capi == Py_None) n0_particles = shape(particles,0); else
    f2py_success = int_from_pyobj(&n0_particles,n0_particles_capi,"STRUPHY_pusher.pusher_step3() 1st keyword (n0_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,0)==n0_particles,"shape(particles,0)==n0_particles","1st keyword n0_particles","pusher_step3:n0_particles=%d",n0_particles) {
  /* Processing variable n1_particles */
  if (n1_particles_capi == Py_None) n1_particles = shape(particles,1); else
    f2py_success = int_from_pyobj(&n1_particles,n1_particles_capi,"STRUPHY_pusher.pusher_step3() 2nd keyword (n1_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,1)==n1_particles,"shape(particles,1)==n1_particles","2nd keyword n1_particles","pusher_step3:n1_particles=%d",n1_particles) {
  /* Processing variable n0_u_part */
  if (n0_u_part_capi == Py_None) n0_u_part = shape(u_part,0); else
    f2py_success = int_from_pyobj(&n0_u_part,n0_u_part_capi,"STRUPHY_pusher.pusher_step3() 6th keyword (n0_u_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u_part,0)==n0_u_part,"shape(u_part,0)==n0_u_part","6th keyword n0_u_part","pusher_step3:n0_u_part=%d",n0_u_part) {
  /* Processing variable n0_mapping */
  if (n0_mapping_capi == Py_None) n0_mapping = len(mapping); else
    f2py_success = int_from_pyobj(&n0_mapping,n0_mapping_capi,"STRUPHY_pusher.pusher_step3() 3rd keyword (n0_mapping) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(mapping)>=n0_mapping,"len(mapping)>=n0_mapping","3rd keyword n0_mapping","pusher_step3:n0_mapping=%d",n0_mapping) {
  /* Processing variable n1_b_part */
  if (n1_b_part_capi == Py_None) n1_b_part = shape(b_part,1); else
    f2py_success = int_from_pyobj(&n1_b_part,n1_b_part_capi,"STRUPHY_pusher.pusher_step3() 5th keyword (n1_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,1)==n1_b_part,"shape(b_part,1)==n1_b_part","5th keyword n1_b_part","pusher_step3:n1_b_part=%d",n1_b_part) {
  /* Processing variable n1_u_part */
  if (n1_u_part_capi == Py_None) n1_u_part = shape(u_part,1); else
    f2py_success = int_from_pyobj(&n1_u_part,n1_u_part_capi,"STRUPHY_pusher.pusher_step3() 7th keyword (n1_u_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u_part,1)==n1_u_part,"shape(u_part,1)==n1_u_part","7th keyword n1_u_part","pusher_step3:n1_u_part=%d",n1_u_part) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles,&n1_particles,particles,&n0_mapping,mapping,&dt,&n0_b_part,&n1_b_part,b_part,&n0_u_part,&n1_u_part,u_part);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(u_part,1)==n1_u_part)*/
  } /*if (f2py_success) of n1_u_part*/
  /* End of cleaning variable n1_u_part */
  } /*CHECKSCALAR(shape(b_part,1)==n1_b_part)*/
  } /*if (f2py_success) of n1_b_part*/
  /* End of cleaning variable n1_b_part */
  } /*CHECKSCALAR(len(mapping)>=n0_mapping)*/
  } /*if (f2py_success) of n0_mapping*/
  /* End of cleaning variable n0_mapping */
  } /*CHECKSCALAR(shape(u_part,0)==n0_u_part)*/
  } /*if (f2py_success) of n0_u_part*/
  /* End of cleaning variable n0_u_part */
  } /*CHECKSCALAR(shape(particles,1)==n1_particles)*/
  } /*if (f2py_success) of n1_particles*/
  /* End of cleaning variable n1_particles */
  } /*CHECKSCALAR(shape(particles,0)==n0_particles)*/
  } /*if (f2py_success) of n0_particles*/
  /* End of cleaning variable n0_particles */
  } /*CHECKSCALAR(shape(b_part,0)==n0_b_part)*/
  } /*if (f2py_success) of n0_b_part*/
  /* End of cleaning variable n0_b_part */
  if((PyObject *)capi_mapping_tmp!=mapping_capi) {
    Py_XDECREF(capi_mapping_tmp); }
  }  /*if (capi_mapping_tmp == NULL) ... else of mapping*/
  /* End of cleaning variable mapping */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_b_part_tmp!=b_part_capi) {
    Py_XDECREF(capi_b_part_tmp); }
  }  /*if (capi_b_part_tmp == NULL) ... else of b_part*/
  /* End of cleaning variable b_part */
  if((PyObject *)capi_particles_tmp!=particles_capi) {
    Py_XDECREF(capi_particles_tmp); }
  }  /*if (capi_particles_tmp == NULL) ... else of particles*/
  /* End of cleaning variable particles */
  if((PyObject *)capi_u_part_tmp!=u_part_capi) {
    Py_XDECREF(capi_u_part_tmp); }
  }  /*if (capi_u_part_tmp == NULL) ... else of u_part*/
  /* End of cleaning variable u_part */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of pusher_step3 ****************************/

/******************************** pusher_step4 ********************************/
static char doc_f2py_rout_STRUPHY_pusher_pusher_step4[] = "\
pusher_step4(particles,mapping,dt,[n0_particles,n1_particles,n0_mapping])\n\nWrapper for ``pusher_step4``.\
\n\nParameters\n----------\n"
"particles : in/output rank-2 array('d') with bounds (n0_particles,n1_particles)\n"
"mapping : input rank-1 array('d') with bounds (n0_mapping)\n"
"dt : input float\n"
"\nOther Parameters\n----------------\n"
"n0_particles : input int, optional\n    Default: shape(particles,0)\n"
"n1_particles : input int, optional\n    Default: shape(particles,1)\n"
"n0_mapping : input int, optional\n    Default: len(mapping)";
/* extern void F_FUNC_US(pusher_step4,PUSHER_STEP4)(int*,int*,double*,int*,double*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_pusher_step4(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles = 0;
  PyObject *n0_particles_capi = Py_None;
  int n1_particles = 0;
  PyObject *n1_particles_capi = Py_None;
  double *particles = NULL;
  npy_intp particles_Dims[2] = {-1, -1};
  const int particles_Rank = 2;
  PyArrayObject *capi_particles_tmp = NULL;
  int capi_particles_intent = 0;
  PyObject *particles_capi = Py_None;
  int n0_mapping = 0;
  PyObject *n0_mapping_capi = Py_None;
  double *mapping = NULL;
  npy_intp mapping_Dims[1] = {-1};
  const int mapping_Rank = 1;
  PyArrayObject *capi_mapping_tmp = NULL;
  int capi_mapping_intent = 0;
  PyObject *mapping_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  static char *capi_kwlist[] = {"particles","mapping","dt","n0_particles","n1_particles","n0_mapping",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OOO:STRUPHY_pusher.pusher_step4",\
    capi_kwlist,&particles_capi,&mapping_capi,&dt_capi,&n0_particles_capi,&n1_particles_capi,&n0_mapping_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable particles */
  ;
  capi_particles_intent |= F2PY_INTENT_INOUT;
  capi_particles_tmp = array_from_pyobj(NPY_DOUBLE,particles_Dims,particles_Rank,capi_particles_intent,particles_capi);
  if (capi_particles_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `particles' of STRUPHY_pusher.pusher_step4 to C/Fortran array" );
  } else {
    particles = (double *)(PyArray_DATA(capi_particles_tmp));

  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"STRUPHY_pusher.pusher_step4() 3rd argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable mapping */
  ;
  capi_mapping_intent |= F2PY_INTENT_IN;
  capi_mapping_tmp = array_from_pyobj(NPY_DOUBLE,mapping_Dims,mapping_Rank,capi_mapping_intent,mapping_capi);
  if (capi_mapping_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 2nd argument `mapping' of STRUPHY_pusher.pusher_step4 to C/Fortran array" );
  } else {
    mapping = (double *)(PyArray_DATA(capi_mapping_tmp));

  /* Processing variable n0_particles */
  if (n0_particles_capi == Py_None) n0_particles = shape(particles,0); else
    f2py_success = int_from_pyobj(&n0_particles,n0_particles_capi,"STRUPHY_pusher.pusher_step4() 1st keyword (n0_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,0)==n0_particles,"shape(particles,0)==n0_particles","1st keyword n0_particles","pusher_step4:n0_particles=%d",n0_particles) {
  /* Processing variable n1_particles */
  if (n1_particles_capi == Py_None) n1_particles = shape(particles,1); else
    f2py_success = int_from_pyobj(&n1_particles,n1_particles_capi,"STRUPHY_pusher.pusher_step4() 2nd keyword (n1_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,1)==n1_particles,"shape(particles,1)==n1_particles","2nd keyword n1_particles","pusher_step4:n1_particles=%d",n1_particles) {
  /* Processing variable n0_mapping */
  if (n0_mapping_capi == Py_None) n0_mapping = len(mapping); else
    f2py_success = int_from_pyobj(&n0_mapping,n0_mapping_capi,"STRUPHY_pusher.pusher_step4() 3rd keyword (n0_mapping) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(mapping)>=n0_mapping,"len(mapping)>=n0_mapping","3rd keyword n0_mapping","pusher_step4:n0_mapping=%d",n0_mapping) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles,&n1_particles,particles,&n0_mapping,mapping,&dt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(mapping)>=n0_mapping)*/
  } /*if (f2py_success) of n0_mapping*/
  /* End of cleaning variable n0_mapping */
  } /*CHECKSCALAR(shape(particles,1)==n1_particles)*/
  } /*if (f2py_success) of n1_particles*/
  /* End of cleaning variable n1_particles */
  } /*CHECKSCALAR(shape(particles,0)==n0_particles)*/
  } /*if (f2py_success) of n0_particles*/
  /* End of cleaning variable n0_particles */
  if((PyObject *)capi_mapping_tmp!=mapping_capi) {
    Py_XDECREF(capi_mapping_tmp); }
  }  /*if (capi_mapping_tmp == NULL) ... else of mapping*/
  /* End of cleaning variable mapping */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_particles_tmp!=particles_capi) {
    Py_XDECREF(capi_particles_tmp); }
  }  /*if (capi_particles_tmp == NULL) ... else of particles*/
  /* End of cleaning variable particles */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of pusher_step4 ****************************/

/******************************** pusher_step5 ********************************/
static char doc_f2py_rout_STRUPHY_pusher_pusher_step5[] = "\
pusher_step5(particles,mapping,dt,b_part,[n0_particles,n1_particles,n0_mapping,n0_b_part,n1_b_part])\n\nWrapper for ``pusher_step5``.\
\n\nParameters\n----------\n"
"particles : in/output rank-2 array('d') with bounds (n0_particles,n1_particles)\n"
"mapping : input rank-1 array('d') with bounds (n0_mapping)\n"
"dt : input float\n"
"b_part : input rank-2 array('d') with bounds (n0_b_part,n1_b_part)\n"
"\nOther Parameters\n----------------\n"
"n0_particles : input int, optional\n    Default: shape(particles,0)\n"
"n1_particles : input int, optional\n    Default: shape(particles,1)\n"
"n0_mapping : input int, optional\n    Default: len(mapping)\n"
"n0_b_part : input int, optional\n    Default: shape(b_part,0)\n"
"n1_b_part : input int, optional\n    Default: shape(b_part,1)";
/* extern void F_FUNC_US(pusher_step5,PUSHER_STEP5)(int*,int*,double*,int*,double*,double*,int*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_pusher_step5(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,double*,double*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles = 0;
  PyObject *n0_particles_capi = Py_None;
  int n1_particles = 0;
  PyObject *n1_particles_capi = Py_None;
  double *particles = NULL;
  npy_intp particles_Dims[2] = {-1, -1};
  const int particles_Rank = 2;
  PyArrayObject *capi_particles_tmp = NULL;
  int capi_particles_intent = 0;
  PyObject *particles_capi = Py_None;
  int n0_mapping = 0;
  PyObject *n0_mapping_capi = Py_None;
  double *mapping = NULL;
  npy_intp mapping_Dims[1] = {-1};
  const int mapping_Rank = 1;
  PyArrayObject *capi_mapping_tmp = NULL;
  int capi_mapping_intent = 0;
  PyObject *mapping_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  int n0_b_part = 0;
  PyObject *n0_b_part_capi = Py_None;
  int n1_b_part = 0;
  PyObject *n1_b_part_capi = Py_None;
  double *b_part = NULL;
  npy_intp b_part_Dims[2] = {-1, -1};
  const int b_part_Rank = 2;
  PyArrayObject *capi_b_part_tmp = NULL;
  int capi_b_part_intent = 0;
  PyObject *b_part_capi = Py_None;
  static char *capi_kwlist[] = {"particles","mapping","dt","b_part","n0_particles","n1_particles","n0_mapping","n0_b_part","n1_b_part",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|OOOOO:STRUPHY_pusher.pusher_step5",\
    capi_kwlist,&particles_capi,&mapping_capi,&dt_capi,&b_part_capi,&n0_particles_capi,&n1_particles_capi,&n0_mapping_capi,&n0_b_part_capi,&n1_b_part_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable particles */
  ;
  capi_particles_intent |= F2PY_INTENT_INOUT;
  capi_particles_tmp = array_from_pyobj(NPY_DOUBLE,particles_Dims,particles_Rank,capi_particles_intent,particles_capi);
  if (capi_particles_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `particles' of STRUPHY_pusher.pusher_step5 to C/Fortran array" );
  } else {
    particles = (double *)(PyArray_DATA(capi_particles_tmp));

  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"STRUPHY_pusher.pusher_step5() 3rd argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable b_part */
  ;
  capi_b_part_intent |= F2PY_INTENT_IN;
  capi_b_part_tmp = array_from_pyobj(NPY_DOUBLE,b_part_Dims,b_part_Rank,capi_b_part_intent,b_part_capi);
  if (capi_b_part_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 4th argument `b_part' of STRUPHY_pusher.pusher_step5 to C/Fortran array" );
  } else {
    b_part = (double *)(PyArray_DATA(capi_b_part_tmp));

  /* Processing variable mapping */
  ;
  capi_mapping_intent |= F2PY_INTENT_IN;
  capi_mapping_tmp = array_from_pyobj(NPY_DOUBLE,mapping_Dims,mapping_Rank,capi_mapping_intent,mapping_capi);
  if (capi_mapping_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 2nd argument `mapping' of STRUPHY_pusher.pusher_step5 to C/Fortran array" );
  } else {
    mapping = (double *)(PyArray_DATA(capi_mapping_tmp));

  /* Processing variable n0_b_part */
  if (n0_b_part_capi == Py_None) n0_b_part = shape(b_part,0); else
    f2py_success = int_from_pyobj(&n0_b_part,n0_b_part_capi,"STRUPHY_pusher.pusher_step5() 4th keyword (n0_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,0)==n0_b_part,"shape(b_part,0)==n0_b_part","4th keyword n0_b_part","pusher_step5:n0_b_part=%d",n0_b_part) {
  /* Processing variable n1_particles */
  if (n1_particles_capi == Py_None) n1_particles = shape(particles,1); else
    f2py_success = int_from_pyobj(&n1_particles,n1_particles_capi,"STRUPHY_pusher.pusher_step5() 2nd keyword (n1_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,1)==n1_particles,"shape(particles,1)==n1_particles","2nd keyword n1_particles","pusher_step5:n1_particles=%d",n1_particles) {
  /* Processing variable n0_mapping */
  if (n0_mapping_capi == Py_None) n0_mapping = len(mapping); else
    f2py_success = int_from_pyobj(&n0_mapping,n0_mapping_capi,"STRUPHY_pusher.pusher_step5() 3rd keyword (n0_mapping) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(mapping)>=n0_mapping,"len(mapping)>=n0_mapping","3rd keyword n0_mapping","pusher_step5:n0_mapping=%d",n0_mapping) {
  /* Processing variable n0_particles */
  if (n0_particles_capi == Py_None) n0_particles = shape(particles,0); else
    f2py_success = int_from_pyobj(&n0_particles,n0_particles_capi,"STRUPHY_pusher.pusher_step5() 1st keyword (n0_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,0)==n0_particles,"shape(particles,0)==n0_particles","1st keyword n0_particles","pusher_step5:n0_particles=%d",n0_particles) {
  /* Processing variable n1_b_part */
  if (n1_b_part_capi == Py_None) n1_b_part = shape(b_part,1); else
    f2py_success = int_from_pyobj(&n1_b_part,n1_b_part_capi,"STRUPHY_pusher.pusher_step5() 5th keyword (n1_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,1)==n1_b_part,"shape(b_part,1)==n1_b_part","5th keyword n1_b_part","pusher_step5:n1_b_part=%d",n1_b_part) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles,&n1_particles,particles,&n0_mapping,mapping,&dt,&n0_b_part,&n1_b_part,b_part);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(b_part,1)==n1_b_part)*/
  } /*if (f2py_success) of n1_b_part*/
  /* End of cleaning variable n1_b_part */
  } /*CHECKSCALAR(shape(particles,0)==n0_particles)*/
  } /*if (f2py_success) of n0_particles*/
  /* End of cleaning variable n0_particles */
  } /*CHECKSCALAR(len(mapping)>=n0_mapping)*/
  } /*if (f2py_success) of n0_mapping*/
  /* End of cleaning variable n0_mapping */
  } /*CHECKSCALAR(shape(particles,1)==n1_particles)*/
  } /*if (f2py_success) of n1_particles*/
  /* End of cleaning variable n1_particles */
  } /*CHECKSCALAR(shape(b_part,0)==n0_b_part)*/
  } /*if (f2py_success) of n0_b_part*/
  /* End of cleaning variable n0_b_part */
  if((PyObject *)capi_mapping_tmp!=mapping_capi) {
    Py_XDECREF(capi_mapping_tmp); }
  }  /*if (capi_mapping_tmp == NULL) ... else of mapping*/
  /* End of cleaning variable mapping */
  if((PyObject *)capi_b_part_tmp!=b_part_capi) {
    Py_XDECREF(capi_b_part_tmp); }
  }  /*if (capi_b_part_tmp == NULL) ... else of b_part*/
  /* End of cleaning variable b_part */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_particles_tmp!=particles_capi) {
    Py_XDECREF(capi_particles_tmp); }
  }  /*if (capi_particles_tmp == NULL) ... else of particles*/
  /* End of cleaning variable particles */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of pusher_step5 ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"mapping_matrices",-1,{{-1}},0,(char *)F_FUNC_US(mapping_matrices,MAPPING_MATRICES),(f2py_init_func)f2py_rout_STRUPHY_pusher_mapping_matrices,doc_f2py_rout_STRUPHY_pusher_mapping_matrices},
  {"matrix_vector",-1,{{-1}},0,(char *)F_FUNC_US(matrix_vector,MATRIX_VECTOR),(f2py_init_func)f2py_rout_STRUPHY_pusher_matrix_vector,doc_f2py_rout_STRUPHY_pusher_matrix_vector},
  {"matrix_matrix",-1,{{-1}},0,(char *)F_FUNC_US(matrix_matrix,MATRIX_MATRIX),(f2py_init_func)f2py_rout_STRUPHY_pusher_matrix_matrix,doc_f2py_rout_STRUPHY_pusher_matrix_matrix},
  {"transpose",-1,{{-1}},0,(char *)F_FUNC(transpose,TRANSPOSE),(f2py_init_func)f2py_rout_STRUPHY_pusher_transpose,doc_f2py_rout_STRUPHY_pusher_transpose},
  {"det",-1,{{-1}},0,(char *)F_FUNC(det,DET),(f2py_init_func)f2py_rout_STRUPHY_pusher_det,doc_f2py_rout_STRUPHY_pusher_det},
  {"pusher_step3",-1,{{-1}},0,(char *)F_FUNC_US(pusher_step3,PUSHER_STEP3),(f2py_init_func)f2py_rout_STRUPHY_pusher_pusher_step3,doc_f2py_rout_STRUPHY_pusher_pusher_step3},
  {"pusher_step4",-1,{{-1}},0,(char *)F_FUNC_US(pusher_step4,PUSHER_STEP4),(f2py_init_func)f2py_rout_STRUPHY_pusher_pusher_step4,doc_f2py_rout_STRUPHY_pusher_pusher_step4},
  {"pusher_step5",-1,{{-1}},0,(char *)F_FUNC_US(pusher_step5,PUSHER_STEP5),(f2py_init_func)f2py_rout_STRUPHY_pusher_pusher_step5,doc_f2py_rout_STRUPHY_pusher_pusher_step5},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "STRUPHY_pusher",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_STRUPHY_pusher(void) {
#else
#define RETVAL
PyMODINIT_FUNC initSTRUPHY_pusher(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = STRUPHY_pusher_module = PyModule_Create(&moduledef);
#else
  m = STRUPHY_pusher_module = Py_InitModule("STRUPHY_pusher", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module STRUPHY_pusher (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'STRUPHY_pusher' is auto-generated with f2py (version:2).\nFunctions:\n"
"  mapping_matrices(q,kind,params,output,a,n0_q=len(q),n0_params=len(params),n0_a=shape(a,0),n1_a=shape(a,1))\n"
"  matrix_vector(a,b,c,n0_a=shape(a,0),n1_a=shape(a,1),n0_b=len(b),n0_c=len(c))\n"
"  matrix_matrix(a,b,c,n0_a=shape(a,0),n1_a=shape(a,1),n0_b=shape(b,0),n1_b=shape(b,1),n0_c=shape(c,0),n1_c=shape(c,1))\n"
"  transpose(a,b,n0_a=shape(a,0),n1_a=shape(a,1),n0_b=shape(b,0),n1_b=shape(b,1))\n"
"  dummy_4220 = det(a,n0_a=shape(a,0),n1_a=shape(a,1))\n"
"  pusher_step3(particles,mapping,dt,b_part,u_part,n0_particles=shape(particles,0),n1_particles=shape(particles,1),n0_mapping=len(mapping),n0_b_part=shape(b_part,0),n1_b_part=shape(b_part,1),n0_u_part=shape(u_part,0),n1_u_part=shape(u_part,1))\n"
"  pusher_step4(particles,mapping,dt,n0_particles=shape(particles,0),n1_particles=shape(particles,1),n0_mapping=len(mapping))\n"
"  pusher_step5(particles,mapping,dt,b_part,n0_particles=shape(particles,0),n1_particles=shape(particles,1),n0_mapping=len(mapping),n0_b_part=shape(b_part,0),n1_b_part=shape(b_part,1))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  STRUPHY_pusher_error = PyErr_NewException ("STRUPHY_pusher.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));








/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"STRUPHY_pusher");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
