/* File: STRUPHY_samplingmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon May 11 12:53:42 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *STRUPHY_sampling_error;
static PyObject *STRUPHY_sampling_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
#ifdef _WIN32
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(STRUPHY_sampling_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = STRUPHY_sampling_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int long_long_from_pyobj(long_long* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyLong_Check(obj)) {
        *v = PyLong_AsLongLong(obj);
        return (!PyErr_Occurred());
    }
    if (PyInt_Check(obj)) {
        *v = (long_long)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = PyLong_AsLongLong(tmp);
        Py_DECREF(tmp);
        return (!PyErr_Occurred());
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (long_long_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = STRUPHY_sampling_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(set_particles_symmetric,SET_PARTICLES_SYMMETRIC)(int*,int*,double*,int*,int*,double*);
extern void F_FUNC_US(compute_weights_ini,COMPUTE_WEIGHTS_INI)(int*,int*,double*,int*,double*,int*,double*,long_long*,int*,double*);
extern void F_FUNC_US(update_weights,UPDATE_WEIGHTS)(int*,int*,double*,int*,double*,int*,double*,long_long*,int*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************** set_particles_symmetric **************************/
static char doc_f2py_rout_STRUPHY_sampling_set_particles_symmetric[] = "\
set_particles_symmetric(numbers,particles,[n0_numbers,n1_numbers,n0_particles,n1_particles])\n\nWrapper for ``set_particles_symmetric``.\
\n\nParameters\n----------\n"
"numbers : input rank-2 array('d') with bounds (n0_numbers,n1_numbers)\n"
"particles : in/output rank-2 array('d') with bounds (n0_particles,n1_particles)\n"
"\nOther Parameters\n----------------\n"
"n0_numbers : input int, optional\n    Default: shape(numbers,0)\n"
"n1_numbers : input int, optional\n    Default: shape(numbers,1)\n"
"n0_particles : input int, optional\n    Default: shape(particles,0)\n"
"n1_particles : input int, optional\n    Default: shape(particles,1)";
/* extern void F_FUNC_US(set_particles_symmetric,SET_PARTICLES_SYMMETRIC)(int*,int*,double*,int*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_sampling_set_particles_symmetric(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_numbers = 0;
  PyObject *n0_numbers_capi = Py_None;
  int n1_numbers = 0;
  PyObject *n1_numbers_capi = Py_None;
  double *numbers = NULL;
  npy_intp numbers_Dims[2] = {-1, -1};
  const int numbers_Rank = 2;
  PyArrayObject *capi_numbers_tmp = NULL;
  int capi_numbers_intent = 0;
  PyObject *numbers_capi = Py_None;
  int n0_particles = 0;
  PyObject *n0_particles_capi = Py_None;
  int n1_particles = 0;
  PyObject *n1_particles_capi = Py_None;
  double *particles = NULL;
  npy_intp particles_Dims[2] = {-1, -1};
  const int particles_Rank = 2;
  PyArrayObject *capi_particles_tmp = NULL;
  int capi_particles_intent = 0;
  PyObject *particles_capi = Py_None;
  static char *capi_kwlist[] = {"numbers","particles","n0_numbers","n1_numbers","n0_particles","n1_particles",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|OOOO:STRUPHY_sampling.set_particles_symmetric",\
    capi_kwlist,&numbers_capi,&particles_capi,&n0_numbers_capi,&n1_numbers_capi,&n0_particles_capi,&n1_particles_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable particles */
  ;
  capi_particles_intent |= F2PY_INTENT_INOUT;
  capi_particles_tmp = array_from_pyobj(NPY_DOUBLE,particles_Dims,particles_Rank,capi_particles_intent,particles_capi);
  if (capi_particles_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 2nd argument `particles' of STRUPHY_sampling.set_particles_symmetric to C/Fortran array" );
  } else {
    particles = (double *)(PyArray_DATA(capi_particles_tmp));

  /* Processing variable numbers */
  ;
  capi_numbers_intent |= F2PY_INTENT_IN;
  capi_numbers_tmp = array_from_pyobj(NPY_DOUBLE,numbers_Dims,numbers_Rank,capi_numbers_intent,numbers_capi);
  if (capi_numbers_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 1st argument `numbers' of STRUPHY_sampling.set_particles_symmetric to C/Fortran array" );
  } else {
    numbers = (double *)(PyArray_DATA(capi_numbers_tmp));

  /* Processing variable n1_particles */
  if (n1_particles_capi == Py_None) n1_particles = shape(particles,1); else
    f2py_success = int_from_pyobj(&n1_particles,n1_particles_capi,"STRUPHY_sampling.set_particles_symmetric() 4th keyword (n1_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,1)==n1_particles,"shape(particles,1)==n1_particles","4th keyword n1_particles","set_particles_symmetric:n1_particles=%d",n1_particles) {
  /* Processing variable n1_numbers */
  if (n1_numbers_capi == Py_None) n1_numbers = shape(numbers,1); else
    f2py_success = int_from_pyobj(&n1_numbers,n1_numbers_capi,"STRUPHY_sampling.set_particles_symmetric() 2nd keyword (n1_numbers) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(numbers,1)==n1_numbers,"shape(numbers,1)==n1_numbers","2nd keyword n1_numbers","set_particles_symmetric:n1_numbers=%d",n1_numbers) {
  /* Processing variable n0_particles */
  if (n0_particles_capi == Py_None) n0_particles = shape(particles,0); else
    f2py_success = int_from_pyobj(&n0_particles,n0_particles_capi,"STRUPHY_sampling.set_particles_symmetric() 3rd keyword (n0_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,0)==n0_particles,"shape(particles,0)==n0_particles","3rd keyword n0_particles","set_particles_symmetric:n0_particles=%d",n0_particles) {
  /* Processing variable n0_numbers */
  if (n0_numbers_capi == Py_None) n0_numbers = shape(numbers,0); else
    f2py_success = int_from_pyobj(&n0_numbers,n0_numbers_capi,"STRUPHY_sampling.set_particles_symmetric() 1st keyword (n0_numbers) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(numbers,0)==n0_numbers,"shape(numbers,0)==n0_numbers","1st keyword n0_numbers","set_particles_symmetric:n0_numbers=%d",n0_numbers) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_numbers,&n1_numbers,numbers,&n0_particles,&n1_particles,particles);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(numbers,0)==n0_numbers)*/
  } /*if (f2py_success) of n0_numbers*/
  /* End of cleaning variable n0_numbers */
  } /*CHECKSCALAR(shape(particles,0)==n0_particles)*/
  } /*if (f2py_success) of n0_particles*/
  /* End of cleaning variable n0_particles */
  } /*CHECKSCALAR(shape(numbers,1)==n1_numbers)*/
  } /*if (f2py_success) of n1_numbers*/
  /* End of cleaning variable n1_numbers */
  } /*CHECKSCALAR(shape(particles,1)==n1_particles)*/
  } /*if (f2py_success) of n1_particles*/
  /* End of cleaning variable n1_particles */
  if((PyObject *)capi_numbers_tmp!=numbers_capi) {
    Py_XDECREF(capi_numbers_tmp); }
  }  /*if (capi_numbers_tmp == NULL) ... else of numbers*/
  /* End of cleaning variable numbers */
  if((PyObject *)capi_particles_tmp!=particles_capi) {
    Py_XDECREF(capi_particles_tmp); }
  }  /*if (capi_particles_tmp == NULL) ... else of particles*/
  /* End of cleaning variable particles */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*********************** end of set_particles_symmetric ***********************/

/**************************** compute_weights_ini ****************************/
static char doc_f2py_rout_STRUPHY_sampling_compute_weights_ini[] = "\
compute_weights_ini(particles,w0,g0,kind_map,params_map,[n0_particles,n1_particles,n0_w0,n0_g0,n0_params_map])\n\nWrapper for ``compute_weights_ini``.\
\n\nParameters\n----------\n"
"particles : input rank-2 array('d') with bounds (n0_particles,n1_particles)\n"
"w0 : in/output rank-1 array('d') with bounds (n0_w0)\n"
"g0 : in/output rank-1 array('d') with bounds (n0_g0)\n"
"kind_map : input long\n"
"params_map : input rank-1 array('d') with bounds (n0_params_map)\n"
"\nOther Parameters\n----------------\n"
"n0_particles : input int, optional\n    Default: shape(particles,0)\n"
"n1_particles : input int, optional\n    Default: shape(particles,1)\n"
"n0_w0 : input int, optional\n    Default: len(w0)\n"
"n0_g0 : input int, optional\n    Default: len(g0)\n"
"n0_params_map : input int, optional\n    Default: len(params_map)";
/* extern void F_FUNC_US(compute_weights_ini,COMPUTE_WEIGHTS_INI)(int*,int*,double*,int*,double*,int*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_sampling_compute_weights_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,double*,int*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles = 0;
  PyObject *n0_particles_capi = Py_None;
  int n1_particles = 0;
  PyObject *n1_particles_capi = Py_None;
  double *particles = NULL;
  npy_intp particles_Dims[2] = {-1, -1};
  const int particles_Rank = 2;
  PyArrayObject *capi_particles_tmp = NULL;
  int capi_particles_intent = 0;
  PyObject *particles_capi = Py_None;
  int n0_w0 = 0;
  PyObject *n0_w0_capi = Py_None;
  double *w0 = NULL;
  npy_intp w0_Dims[1] = {-1};
  const int w0_Rank = 1;
  PyArrayObject *capi_w0_tmp = NULL;
  int capi_w0_intent = 0;
  PyObject *w0_capi = Py_None;
  int n0_g0 = 0;
  PyObject *n0_g0_capi = Py_None;
  double *g0 = NULL;
  npy_intp g0_Dims[1] = {-1};
  const int g0_Rank = 1;
  PyArrayObject *capi_g0_tmp = NULL;
  int capi_g0_intent = 0;
  PyObject *g0_capi = Py_None;
  long_long kind_map = 0;
  PyObject *kind_map_capi = Py_None;
  int n0_params_map = 0;
  PyObject *n0_params_map_capi = Py_None;
  double *params_map = NULL;
  npy_intp params_map_Dims[1] = {-1};
  const int params_map_Rank = 1;
  PyArrayObject *capi_params_map_tmp = NULL;
  int capi_params_map_intent = 0;
  PyObject *params_map_capi = Py_None;
  static char *capi_kwlist[] = {"particles","w0","g0","kind_map","params_map","n0_particles","n1_particles","n0_w0","n0_g0","n0_params_map",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOOOO:STRUPHY_sampling.compute_weights_ini",\
    capi_kwlist,&particles_capi,&w0_capi,&g0_capi,&kind_map_capi,&params_map_capi,&n0_particles_capi,&n1_particles_capi,&n0_w0_capi,&n0_g0_capi,&n0_params_map_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable particles */
  ;
  capi_particles_intent |= F2PY_INTENT_IN;
  capi_particles_tmp = array_from_pyobj(NPY_DOUBLE,particles_Dims,particles_Rank,capi_particles_intent,particles_capi);
  if (capi_particles_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 1st argument `particles' of STRUPHY_sampling.compute_weights_ini to C/Fortran array" );
  } else {
    particles = (double *)(PyArray_DATA(capi_particles_tmp));

  /* Processing variable g0 */
  ;
  capi_g0_intent |= F2PY_INTENT_INOUT;
  capi_g0_tmp = array_from_pyobj(NPY_DOUBLE,g0_Dims,g0_Rank,capi_g0_intent,g0_capi);
  if (capi_g0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 3rd argument `g0' of STRUPHY_sampling.compute_weights_ini to C/Fortran array" );
  } else {
    g0 = (double *)(PyArray_DATA(capi_g0_tmp));

  /* Processing variable w0 */
  ;
  capi_w0_intent |= F2PY_INTENT_INOUT;
  capi_w0_tmp = array_from_pyobj(NPY_DOUBLE,w0_Dims,w0_Rank,capi_w0_intent,w0_capi);
  if (capi_w0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 2nd argument `w0' of STRUPHY_sampling.compute_weights_ini to C/Fortran array" );
  } else {
    w0 = (double *)(PyArray_DATA(capi_w0_tmp));

  /* Processing variable params_map */
  ;
  capi_params_map_intent |= F2PY_INTENT_IN;
  capi_params_map_tmp = array_from_pyobj(NPY_DOUBLE,params_map_Dims,params_map_Rank,capi_params_map_intent,params_map_capi);
  if (capi_params_map_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 5th argument `params_map' of STRUPHY_sampling.compute_weights_ini to C/Fortran array" );
  } else {
    params_map = (double *)(PyArray_DATA(capi_params_map_tmp));

  /* Processing variable kind_map */
    f2py_success = long_long_from_pyobj(&kind_map,kind_map_capi,"STRUPHY_sampling.compute_weights_ini() 4th argument (kind_map) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable n0_g0 */
  if (n0_g0_capi == Py_None) n0_g0 = len(g0); else
    f2py_success = int_from_pyobj(&n0_g0,n0_g0_capi,"STRUPHY_sampling.compute_weights_ini() 4th keyword (n0_g0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(g0)>=n0_g0,"len(g0)>=n0_g0","4th keyword n0_g0","compute_weights_ini:n0_g0=%d",n0_g0) {
  /* Processing variable n0_params_map */
  if (n0_params_map_capi == Py_None) n0_params_map = len(params_map); else
    f2py_success = int_from_pyobj(&n0_params_map,n0_params_map_capi,"STRUPHY_sampling.compute_weights_ini() 5th keyword (n0_params_map) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params_map)>=n0_params_map,"len(params_map)>=n0_params_map","5th keyword n0_params_map","compute_weights_ini:n0_params_map=%d",n0_params_map) {
  /* Processing variable n1_particles */
  if (n1_particles_capi == Py_None) n1_particles = shape(particles,1); else
    f2py_success = int_from_pyobj(&n1_particles,n1_particles_capi,"STRUPHY_sampling.compute_weights_ini() 2nd keyword (n1_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,1)==n1_particles,"shape(particles,1)==n1_particles","2nd keyword n1_particles","compute_weights_ini:n1_particles=%d",n1_particles) {
  /* Processing variable n0_w0 */
  if (n0_w0_capi == Py_None) n0_w0 = len(w0); else
    f2py_success = int_from_pyobj(&n0_w0,n0_w0_capi,"STRUPHY_sampling.compute_weights_ini() 3rd keyword (n0_w0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(w0)>=n0_w0,"len(w0)>=n0_w0","3rd keyword n0_w0","compute_weights_ini:n0_w0=%d",n0_w0) {
  /* Processing variable n0_particles */
  if (n0_particles_capi == Py_None) n0_particles = shape(particles,0); else
    f2py_success = int_from_pyobj(&n0_particles,n0_particles_capi,"STRUPHY_sampling.compute_weights_ini() 1st keyword (n0_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,0)==n0_particles,"shape(particles,0)==n0_particles","1st keyword n0_particles","compute_weights_ini:n0_particles=%d",n0_particles) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles,&n1_particles,particles,&n0_w0,w0,&n0_g0,g0,&kind_map,&n0_params_map,params_map);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(particles,0)==n0_particles)*/
  } /*if (f2py_success) of n0_particles*/
  /* End of cleaning variable n0_particles */
  } /*CHECKSCALAR(len(w0)>=n0_w0)*/
  } /*if (f2py_success) of n0_w0*/
  /* End of cleaning variable n0_w0 */
  } /*CHECKSCALAR(shape(particles,1)==n1_particles)*/
  } /*if (f2py_success) of n1_particles*/
  /* End of cleaning variable n1_particles */
  } /*CHECKSCALAR(len(params_map)>=n0_params_map)*/
  } /*if (f2py_success) of n0_params_map*/
  /* End of cleaning variable n0_params_map */
  } /*CHECKSCALAR(len(g0)>=n0_g0)*/
  } /*if (f2py_success) of n0_g0*/
  /* End of cleaning variable n0_g0 */
  } /*if (f2py_success) of kind_map*/
  /* End of cleaning variable kind_map */
  if((PyObject *)capi_params_map_tmp!=params_map_capi) {
    Py_XDECREF(capi_params_map_tmp); }
  }  /*if (capi_params_map_tmp == NULL) ... else of params_map*/
  /* End of cleaning variable params_map */
  if((PyObject *)capi_w0_tmp!=w0_capi) {
    Py_XDECREF(capi_w0_tmp); }
  }  /*if (capi_w0_tmp == NULL) ... else of w0*/
  /* End of cleaning variable w0 */
  if((PyObject *)capi_g0_tmp!=g0_capi) {
    Py_XDECREF(capi_g0_tmp); }
  }  /*if (capi_g0_tmp == NULL) ... else of g0*/
  /* End of cleaning variable g0 */
  if((PyObject *)capi_particles_tmp!=particles_capi) {
    Py_XDECREF(capi_particles_tmp); }
  }  /*if (capi_particles_tmp == NULL) ... else of particles*/
  /* End of cleaning variable particles */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************* end of compute_weights_ini *************************/

/******************************* update_weights *******************************/
static char doc_f2py_rout_STRUPHY_sampling_update_weights[] = "\
update_weights(particles,w0,g0,kind_map,params_map,[n0_particles,n1_particles,n0_w0,n0_g0,n0_params_map])\n\nWrapper for ``update_weights``.\
\n\nParameters\n----------\n"
"particles : in/output rank-2 array('d') with bounds (n0_particles,n1_particles)\n"
"w0 : input rank-1 array('d') with bounds (n0_w0)\n"
"g0 : input rank-1 array('d') with bounds (n0_g0)\n"
"kind_map : input long\n"
"params_map : input rank-1 array('d') with bounds (n0_params_map)\n"
"\nOther Parameters\n----------------\n"
"n0_particles : input int, optional\n    Default: shape(particles,0)\n"
"n1_particles : input int, optional\n    Default: shape(particles,1)\n"
"n0_w0 : input int, optional\n    Default: len(w0)\n"
"n0_g0 : input int, optional\n    Default: len(g0)\n"
"n0_params_map : input int, optional\n    Default: len(params_map)";
/* extern void F_FUNC_US(update_weights,UPDATE_WEIGHTS)(int*,int*,double*,int*,double*,int*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_sampling_update_weights(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,double*,int*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles = 0;
  PyObject *n0_particles_capi = Py_None;
  int n1_particles = 0;
  PyObject *n1_particles_capi = Py_None;
  double *particles = NULL;
  npy_intp particles_Dims[2] = {-1, -1};
  const int particles_Rank = 2;
  PyArrayObject *capi_particles_tmp = NULL;
  int capi_particles_intent = 0;
  PyObject *particles_capi = Py_None;
  int n0_w0 = 0;
  PyObject *n0_w0_capi = Py_None;
  double *w0 = NULL;
  npy_intp w0_Dims[1] = {-1};
  const int w0_Rank = 1;
  PyArrayObject *capi_w0_tmp = NULL;
  int capi_w0_intent = 0;
  PyObject *w0_capi = Py_None;
  int n0_g0 = 0;
  PyObject *n0_g0_capi = Py_None;
  double *g0 = NULL;
  npy_intp g0_Dims[1] = {-1};
  const int g0_Rank = 1;
  PyArrayObject *capi_g0_tmp = NULL;
  int capi_g0_intent = 0;
  PyObject *g0_capi = Py_None;
  long_long kind_map = 0;
  PyObject *kind_map_capi = Py_None;
  int n0_params_map = 0;
  PyObject *n0_params_map_capi = Py_None;
  double *params_map = NULL;
  npy_intp params_map_Dims[1] = {-1};
  const int params_map_Rank = 1;
  PyArrayObject *capi_params_map_tmp = NULL;
  int capi_params_map_intent = 0;
  PyObject *params_map_capi = Py_None;
  static char *capi_kwlist[] = {"particles","w0","g0","kind_map","params_map","n0_particles","n1_particles","n0_w0","n0_g0","n0_params_map",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOOOO:STRUPHY_sampling.update_weights",\
    capi_kwlist,&particles_capi,&w0_capi,&g0_capi,&kind_map_capi,&params_map_capi,&n0_particles_capi,&n1_particles_capi,&n0_w0_capi,&n0_g0_capi,&n0_params_map_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable particles */
  ;
  capi_particles_intent |= F2PY_INTENT_INOUT;
  capi_particles_tmp = array_from_pyobj(NPY_DOUBLE,particles_Dims,particles_Rank,capi_particles_intent,particles_capi);
  if (capi_particles_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 1st argument `particles' of STRUPHY_sampling.update_weights to C/Fortran array" );
  } else {
    particles = (double *)(PyArray_DATA(capi_particles_tmp));

  /* Processing variable g0 */
  ;
  capi_g0_intent |= F2PY_INTENT_IN;
  capi_g0_tmp = array_from_pyobj(NPY_DOUBLE,g0_Dims,g0_Rank,capi_g0_intent,g0_capi);
  if (capi_g0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 3rd argument `g0' of STRUPHY_sampling.update_weights to C/Fortran array" );
  } else {
    g0 = (double *)(PyArray_DATA(capi_g0_tmp));

  /* Processing variable w0 */
  ;
  capi_w0_intent |= F2PY_INTENT_IN;
  capi_w0_tmp = array_from_pyobj(NPY_DOUBLE,w0_Dims,w0_Rank,capi_w0_intent,w0_capi);
  if (capi_w0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 2nd argument `w0' of STRUPHY_sampling.update_weights to C/Fortran array" );
  } else {
    w0 = (double *)(PyArray_DATA(capi_w0_tmp));

  /* Processing variable params_map */
  ;
  capi_params_map_intent |= F2PY_INTENT_IN;
  capi_params_map_tmp = array_from_pyobj(NPY_DOUBLE,params_map_Dims,params_map_Rank,capi_params_map_intent,params_map_capi);
  if (capi_params_map_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_sampling_error,"failed in converting 5th argument `params_map' of STRUPHY_sampling.update_weights to C/Fortran array" );
  } else {
    params_map = (double *)(PyArray_DATA(capi_params_map_tmp));

  /* Processing variable kind_map */
    f2py_success = long_long_from_pyobj(&kind_map,kind_map_capi,"STRUPHY_sampling.update_weights() 4th argument (kind_map) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable n0_g0 */
  if (n0_g0_capi == Py_None) n0_g0 = len(g0); else
    f2py_success = int_from_pyobj(&n0_g0,n0_g0_capi,"STRUPHY_sampling.update_weights() 4th keyword (n0_g0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(g0)>=n0_g0,"len(g0)>=n0_g0","4th keyword n0_g0","update_weights:n0_g0=%d",n0_g0) {
  /* Processing variable n0_params_map */
  if (n0_params_map_capi == Py_None) n0_params_map = len(params_map); else
    f2py_success = int_from_pyobj(&n0_params_map,n0_params_map_capi,"STRUPHY_sampling.update_weights() 5th keyword (n0_params_map) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params_map)>=n0_params_map,"len(params_map)>=n0_params_map","5th keyword n0_params_map","update_weights:n0_params_map=%d",n0_params_map) {
  /* Processing variable n1_particles */
  if (n1_particles_capi == Py_None) n1_particles = shape(particles,1); else
    f2py_success = int_from_pyobj(&n1_particles,n1_particles_capi,"STRUPHY_sampling.update_weights() 2nd keyword (n1_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,1)==n1_particles,"shape(particles,1)==n1_particles","2nd keyword n1_particles","update_weights:n1_particles=%d",n1_particles) {
  /* Processing variable n0_w0 */
  if (n0_w0_capi == Py_None) n0_w0 = len(w0); else
    f2py_success = int_from_pyobj(&n0_w0,n0_w0_capi,"STRUPHY_sampling.update_weights() 3rd keyword (n0_w0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(w0)>=n0_w0,"len(w0)>=n0_w0","3rd keyword n0_w0","update_weights:n0_w0=%d",n0_w0) {
  /* Processing variable n0_particles */
  if (n0_particles_capi == Py_None) n0_particles = shape(particles,0); else
    f2py_success = int_from_pyobj(&n0_particles,n0_particles_capi,"STRUPHY_sampling.update_weights() 1st keyword (n0_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,0)==n0_particles,"shape(particles,0)==n0_particles","1st keyword n0_particles","update_weights:n0_particles=%d",n0_particles) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles,&n1_particles,particles,&n0_w0,w0,&n0_g0,g0,&kind_map,&n0_params_map,params_map);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(particles,0)==n0_particles)*/
  } /*if (f2py_success) of n0_particles*/
  /* End of cleaning variable n0_particles */
  } /*CHECKSCALAR(len(w0)>=n0_w0)*/
  } /*if (f2py_success) of n0_w0*/
  /* End of cleaning variable n0_w0 */
  } /*CHECKSCALAR(shape(particles,1)==n1_particles)*/
  } /*if (f2py_success) of n1_particles*/
  /* End of cleaning variable n1_particles */
  } /*CHECKSCALAR(len(params_map)>=n0_params_map)*/
  } /*if (f2py_success) of n0_params_map*/
  /* End of cleaning variable n0_params_map */
  } /*CHECKSCALAR(len(g0)>=n0_g0)*/
  } /*if (f2py_success) of n0_g0*/
  /* End of cleaning variable n0_g0 */
  } /*if (f2py_success) of kind_map*/
  /* End of cleaning variable kind_map */
  if((PyObject *)capi_params_map_tmp!=params_map_capi) {
    Py_XDECREF(capi_params_map_tmp); }
  }  /*if (capi_params_map_tmp == NULL) ... else of params_map*/
  /* End of cleaning variable params_map */
  if((PyObject *)capi_w0_tmp!=w0_capi) {
    Py_XDECREF(capi_w0_tmp); }
  }  /*if (capi_w0_tmp == NULL) ... else of w0*/
  /* End of cleaning variable w0 */
  if((PyObject *)capi_g0_tmp!=g0_capi) {
    Py_XDECREF(capi_g0_tmp); }
  }  /*if (capi_g0_tmp == NULL) ... else of g0*/
  /* End of cleaning variable g0 */
  if((PyObject *)capi_particles_tmp!=particles_capi) {
    Py_XDECREF(capi_particles_tmp); }
  }  /*if (capi_particles_tmp == NULL) ... else of particles*/
  /* End of cleaning variable particles */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of update_weights ***************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"set_particles_symmetric",-1,{{-1}},0,(char *)F_FUNC_US(set_particles_symmetric,SET_PARTICLES_SYMMETRIC),(f2py_init_func)f2py_rout_STRUPHY_sampling_set_particles_symmetric,doc_f2py_rout_STRUPHY_sampling_set_particles_symmetric},
  {"compute_weights_ini",-1,{{-1}},0,(char *)F_FUNC_US(compute_weights_ini,COMPUTE_WEIGHTS_INI),(f2py_init_func)f2py_rout_STRUPHY_sampling_compute_weights_ini,doc_f2py_rout_STRUPHY_sampling_compute_weights_ini},
  {"update_weights",-1,{{-1}},0,(char *)F_FUNC_US(update_weights,UPDATE_WEIGHTS),(f2py_init_func)f2py_rout_STRUPHY_sampling_update_weights,doc_f2py_rout_STRUPHY_sampling_update_weights},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "STRUPHY_sampling",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_STRUPHY_sampling(void) {
#else
#define RETVAL
PyMODINIT_FUNC initSTRUPHY_sampling(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = STRUPHY_sampling_module = PyModule_Create(&moduledef);
#else
  m = STRUPHY_sampling_module = Py_InitModule("STRUPHY_sampling", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module STRUPHY_sampling (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'STRUPHY_sampling' is auto-generated with f2py (version:2).\nFunctions:\n"
"  set_particles_symmetric(numbers,particles,n0_numbers=shape(numbers,0),n1_numbers=shape(numbers,1),n0_particles=shape(particles,0),n1_particles=shape(particles,1))\n"
"  compute_weights_ini(particles,w0,g0,kind_map,params_map,n0_particles=shape(particles,0),n1_particles=shape(particles,1),n0_w0=len(w0),n0_g0=len(g0),n0_params_map=len(params_map))\n"
"  update_weights(particles,w0,g0,kind_map,params_map,n0_particles=shape(particles,0),n1_particles=shape(particles,1),n0_w0=len(w0),n0_g0=len(g0),n0_params_map=len(params_map))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  STRUPHY_sampling_error = PyErr_NewException ("STRUPHY_sampling.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"STRUPHY_sampling");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
