/* File: STRUPHY_pushermodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sat Apr 25 15:46:11 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *STRUPHY_pusher_error;
static PyObject *STRUPHY_pusher_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
#ifdef _WIN32
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(STRUPHY_pusher_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = STRUPHY_pusher_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int long_long_from_pyobj(long_long* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyLong_Check(obj)) {
        *v = PyLong_AsLongLong(obj);
        return (!PyErr_Occurred());
    }
    if (PyInt_Check(obj)) {
        *v = (long_long)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = PyLong_AsLongLong(tmp);
        Py_DECREF(tmp);
        return (!PyErr_Occurred());
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (long_long_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = STRUPHY_pusher_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = STRUPHY_pusher_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(pusher_step3,PUSHER_STEP3)(int*,int*,double*,double*,int*,int*,double*,int*,int*,double*,long_long*,int*,double*);
extern void F_FUNC_US(pusher_step4,PUSHER_STEP4)(int*,int*,double*,double*,long_long*,int*,double*);
extern void F_FUNC_US(pusher_step5,PUSHER_STEP5)(int*,int*,double*,double*,int*,int*,double*,long_long*,int*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** pusher_step3 ********************************/
static char doc_f2py_rout_STRUPHY_pusher_pusher_step3[] = "\
pusher_step3(particles,dt,b_part,u_part,kind_map,params_map,[n0_particles,n1_particles,n0_b_part,n1_b_part,n0_u_part,n1_u_part,n0_params_map])\n\nWrapper for ``pusher_step3``.\
\n\nParameters\n----------\n"
"particles : in/output rank-2 array('d') with bounds (n0_particles,n1_particles)\n"
"dt : input float\n"
"b_part : input rank-2 array('d') with bounds (n0_b_part,n1_b_part)\n"
"u_part : input rank-2 array('d') with bounds (n0_u_part,n1_u_part)\n"
"kind_map : input long\n"
"params_map : input rank-1 array('d') with bounds (n0_params_map)\n"
"\nOther Parameters\n----------------\n"
"n0_particles : input int, optional\n    Default: shape(particles,0)\n"
"n1_particles : input int, optional\n    Default: shape(particles,1)\n"
"n0_b_part : input int, optional\n    Default: shape(b_part,0)\n"
"n1_b_part : input int, optional\n    Default: shape(b_part,1)\n"
"n0_u_part : input int, optional\n    Default: shape(u_part,0)\n"
"n1_u_part : input int, optional\n    Default: shape(u_part,1)\n"
"n0_params_map : input int, optional\n    Default: len(params_map)";
/* extern void F_FUNC_US(pusher_step3,PUSHER_STEP3)(int*,int*,double*,double*,int*,int*,double*,int*,int*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_pusher_step3(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,int*,int*,double*,int*,int*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles = 0;
  PyObject *n0_particles_capi = Py_None;
  int n1_particles = 0;
  PyObject *n1_particles_capi = Py_None;
  double *particles = NULL;
  npy_intp particles_Dims[2] = {-1, -1};
  const int particles_Rank = 2;
  PyArrayObject *capi_particles_tmp = NULL;
  int capi_particles_intent = 0;
  PyObject *particles_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  int n0_b_part = 0;
  PyObject *n0_b_part_capi = Py_None;
  int n1_b_part = 0;
  PyObject *n1_b_part_capi = Py_None;
  double *b_part = NULL;
  npy_intp b_part_Dims[2] = {-1, -1};
  const int b_part_Rank = 2;
  PyArrayObject *capi_b_part_tmp = NULL;
  int capi_b_part_intent = 0;
  PyObject *b_part_capi = Py_None;
  int n0_u_part = 0;
  PyObject *n0_u_part_capi = Py_None;
  int n1_u_part = 0;
  PyObject *n1_u_part_capi = Py_None;
  double *u_part = NULL;
  npy_intp u_part_Dims[2] = {-1, -1};
  const int u_part_Rank = 2;
  PyArrayObject *capi_u_part_tmp = NULL;
  int capi_u_part_intent = 0;
  PyObject *u_part_capi = Py_None;
  long_long kind_map = 0;
  PyObject *kind_map_capi = Py_None;
  int n0_params_map = 0;
  PyObject *n0_params_map_capi = Py_None;
  double *params_map = NULL;
  npy_intp params_map_Dims[1] = {-1};
  const int params_map_Rank = 1;
  PyArrayObject *capi_params_map_tmp = NULL;
  int capi_params_map_intent = 0;
  PyObject *params_map_capi = Py_None;
  static char *capi_kwlist[] = {"particles","dt","b_part","u_part","kind_map","params_map","n0_particles","n1_particles","n0_b_part","n1_b_part","n0_u_part","n1_u_part","n0_params_map",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OOOOOOO:STRUPHY_pusher.pusher_step3",\
    capi_kwlist,&particles_capi,&dt_capi,&b_part_capi,&u_part_capi,&kind_map_capi,&params_map_capi,&n0_particles_capi,&n1_particles_capi,&n0_b_part_capi,&n1_b_part_capi,&n0_u_part_capi,&n1_u_part_capi,&n0_params_map_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable particles */
  ;
  capi_particles_intent |= F2PY_INTENT_INOUT;
  capi_particles_tmp = array_from_pyobj(NPY_DOUBLE,particles_Dims,particles_Rank,capi_particles_intent,particles_capi);
  if (capi_particles_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `particles' of STRUPHY_pusher.pusher_step3 to C/Fortran array" );
  } else {
    particles = (double *)(PyArray_DATA(capi_particles_tmp));

  /* Processing variable u_part */
  ;
  capi_u_part_intent |= F2PY_INTENT_IN;
  capi_u_part_tmp = array_from_pyobj(NPY_DOUBLE,u_part_Dims,u_part_Rank,capi_u_part_intent,u_part_capi);
  if (capi_u_part_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 4th argument `u_part' of STRUPHY_pusher.pusher_step3 to C/Fortran array" );
  } else {
    u_part = (double *)(PyArray_DATA(capi_u_part_tmp));

  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"STRUPHY_pusher.pusher_step3() 2nd argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable params_map */
  ;
  capi_params_map_intent |= F2PY_INTENT_IN;
  capi_params_map_tmp = array_from_pyobj(NPY_DOUBLE,params_map_Dims,params_map_Rank,capi_params_map_intent,params_map_capi);
  if (capi_params_map_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 6th argument `params_map' of STRUPHY_pusher.pusher_step3 to C/Fortran array" );
  } else {
    params_map = (double *)(PyArray_DATA(capi_params_map_tmp));

  /* Processing variable b_part */
  ;
  capi_b_part_intent |= F2PY_INTENT_IN;
  capi_b_part_tmp = array_from_pyobj(NPY_DOUBLE,b_part_Dims,b_part_Rank,capi_b_part_intent,b_part_capi);
  if (capi_b_part_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 3rd argument `b_part' of STRUPHY_pusher.pusher_step3 to C/Fortran array" );
  } else {
    b_part = (double *)(PyArray_DATA(capi_b_part_tmp));

  /* Processing variable kind_map */
    f2py_success = long_long_from_pyobj(&kind_map,kind_map_capi,"STRUPHY_pusher.pusher_step3() 5th argument (kind_map) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable n1_u_part */
  if (n1_u_part_capi == Py_None) n1_u_part = shape(u_part,1); else
    f2py_success = int_from_pyobj(&n1_u_part,n1_u_part_capi,"STRUPHY_pusher.pusher_step3() 6th keyword (n1_u_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u_part,1)==n1_u_part,"shape(u_part,1)==n1_u_part","6th keyword n1_u_part","pusher_step3:n1_u_part=%d",n1_u_part) {
  /* Processing variable n0_particles */
  if (n0_particles_capi == Py_None) n0_particles = shape(particles,0); else
    f2py_success = int_from_pyobj(&n0_particles,n0_particles_capi,"STRUPHY_pusher.pusher_step3() 1st keyword (n0_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,0)==n0_particles,"shape(particles,0)==n0_particles","1st keyword n0_particles","pusher_step3:n0_particles=%d",n0_particles) {
  /* Processing variable n1_particles */
  if (n1_particles_capi == Py_None) n1_particles = shape(particles,1); else
    f2py_success = int_from_pyobj(&n1_particles,n1_particles_capi,"STRUPHY_pusher.pusher_step3() 2nd keyword (n1_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,1)==n1_particles,"shape(particles,1)==n1_particles","2nd keyword n1_particles","pusher_step3:n1_particles=%d",n1_particles) {
  /* Processing variable n0_params_map */
  if (n0_params_map_capi == Py_None) n0_params_map = len(params_map); else
    f2py_success = int_from_pyobj(&n0_params_map,n0_params_map_capi,"STRUPHY_pusher.pusher_step3() 7th keyword (n0_params_map) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params_map)>=n0_params_map,"len(params_map)>=n0_params_map","7th keyword n0_params_map","pusher_step3:n0_params_map=%d",n0_params_map) {
  /* Processing variable n1_b_part */
  if (n1_b_part_capi == Py_None) n1_b_part = shape(b_part,1); else
    f2py_success = int_from_pyobj(&n1_b_part,n1_b_part_capi,"STRUPHY_pusher.pusher_step3() 4th keyword (n1_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,1)==n1_b_part,"shape(b_part,1)==n1_b_part","4th keyword n1_b_part","pusher_step3:n1_b_part=%d",n1_b_part) {
  /* Processing variable n0_u_part */
  if (n0_u_part_capi == Py_None) n0_u_part = shape(u_part,0); else
    f2py_success = int_from_pyobj(&n0_u_part,n0_u_part_capi,"STRUPHY_pusher.pusher_step3() 5th keyword (n0_u_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u_part,0)==n0_u_part,"shape(u_part,0)==n0_u_part","5th keyword n0_u_part","pusher_step3:n0_u_part=%d",n0_u_part) {
  /* Processing variable n0_b_part */
  if (n0_b_part_capi == Py_None) n0_b_part = shape(b_part,0); else
    f2py_success = int_from_pyobj(&n0_b_part,n0_b_part_capi,"STRUPHY_pusher.pusher_step3() 3rd keyword (n0_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,0)==n0_b_part,"shape(b_part,0)==n0_b_part","3rd keyword n0_b_part","pusher_step3:n0_b_part=%d",n0_b_part) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles,&n1_particles,particles,&dt,&n0_b_part,&n1_b_part,b_part,&n0_u_part,&n1_u_part,u_part,&kind_map,&n0_params_map,params_map);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(b_part,0)==n0_b_part)*/
  } /*if (f2py_success) of n0_b_part*/
  /* End of cleaning variable n0_b_part */
  } /*CHECKSCALAR(shape(u_part,0)==n0_u_part)*/
  } /*if (f2py_success) of n0_u_part*/
  /* End of cleaning variable n0_u_part */
  } /*CHECKSCALAR(shape(b_part,1)==n1_b_part)*/
  } /*if (f2py_success) of n1_b_part*/
  /* End of cleaning variable n1_b_part */
  } /*CHECKSCALAR(len(params_map)>=n0_params_map)*/
  } /*if (f2py_success) of n0_params_map*/
  /* End of cleaning variable n0_params_map */
  } /*CHECKSCALAR(shape(particles,1)==n1_particles)*/
  } /*if (f2py_success) of n1_particles*/
  /* End of cleaning variable n1_particles */
  } /*CHECKSCALAR(shape(particles,0)==n0_particles)*/
  } /*if (f2py_success) of n0_particles*/
  /* End of cleaning variable n0_particles */
  } /*CHECKSCALAR(shape(u_part,1)==n1_u_part)*/
  } /*if (f2py_success) of n1_u_part*/
  /* End of cleaning variable n1_u_part */
  } /*if (f2py_success) of kind_map*/
  /* End of cleaning variable kind_map */
  if((PyObject *)capi_b_part_tmp!=b_part_capi) {
    Py_XDECREF(capi_b_part_tmp); }
  }  /*if (capi_b_part_tmp == NULL) ... else of b_part*/
  /* End of cleaning variable b_part */
  if((PyObject *)capi_params_map_tmp!=params_map_capi) {
    Py_XDECREF(capi_params_map_tmp); }
  }  /*if (capi_params_map_tmp == NULL) ... else of params_map*/
  /* End of cleaning variable params_map */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_u_part_tmp!=u_part_capi) {
    Py_XDECREF(capi_u_part_tmp); }
  }  /*if (capi_u_part_tmp == NULL) ... else of u_part*/
  /* End of cleaning variable u_part */
  if((PyObject *)capi_particles_tmp!=particles_capi) {
    Py_XDECREF(capi_particles_tmp); }
  }  /*if (capi_particles_tmp == NULL) ... else of particles*/
  /* End of cleaning variable particles */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of pusher_step3 ****************************/

/******************************** pusher_step4 ********************************/
static char doc_f2py_rout_STRUPHY_pusher_pusher_step4[] = "\
pusher_step4(particles,dt,kind_map,params_map,[n0_particles,n1_particles,n0_params_map])\n\nWrapper for ``pusher_step4``.\
\n\nParameters\n----------\n"
"particles : in/output rank-2 array('d') with bounds (n0_particles,n1_particles)\n"
"dt : input float\n"
"kind_map : input long\n"
"params_map : input rank-1 array('d') with bounds (n0_params_map)\n"
"\nOther Parameters\n----------------\n"
"n0_particles : input int, optional\n    Default: shape(particles,0)\n"
"n1_particles : input int, optional\n    Default: shape(particles,1)\n"
"n0_params_map : input int, optional\n    Default: len(params_map)";
/* extern void F_FUNC_US(pusher_step4,PUSHER_STEP4)(int*,int*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_pusher_step4(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles = 0;
  PyObject *n0_particles_capi = Py_None;
  int n1_particles = 0;
  PyObject *n1_particles_capi = Py_None;
  double *particles = NULL;
  npy_intp particles_Dims[2] = {-1, -1};
  const int particles_Rank = 2;
  PyArrayObject *capi_particles_tmp = NULL;
  int capi_particles_intent = 0;
  PyObject *particles_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  long_long kind_map = 0;
  PyObject *kind_map_capi = Py_None;
  int n0_params_map = 0;
  PyObject *n0_params_map_capi = Py_None;
  double *params_map = NULL;
  npy_intp params_map_Dims[1] = {-1};
  const int params_map_Rank = 1;
  PyArrayObject *capi_params_map_tmp = NULL;
  int capi_params_map_intent = 0;
  PyObject *params_map_capi = Py_None;
  static char *capi_kwlist[] = {"particles","dt","kind_map","params_map","n0_particles","n1_particles","n0_params_map",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|OOO:STRUPHY_pusher.pusher_step4",\
    capi_kwlist,&particles_capi,&dt_capi,&kind_map_capi,&params_map_capi,&n0_particles_capi,&n1_particles_capi,&n0_params_map_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable particles */
  ;
  capi_particles_intent |= F2PY_INTENT_INOUT;
  capi_particles_tmp = array_from_pyobj(NPY_DOUBLE,particles_Dims,particles_Rank,capi_particles_intent,particles_capi);
  if (capi_particles_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `particles' of STRUPHY_pusher.pusher_step4 to C/Fortran array" );
  } else {
    particles = (double *)(PyArray_DATA(capi_particles_tmp));

  /* Processing variable params_map */
  ;
  capi_params_map_intent |= F2PY_INTENT_IN;
  capi_params_map_tmp = array_from_pyobj(NPY_DOUBLE,params_map_Dims,params_map_Rank,capi_params_map_intent,params_map_capi);
  if (capi_params_map_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 4th argument `params_map' of STRUPHY_pusher.pusher_step4 to C/Fortran array" );
  } else {
    params_map = (double *)(PyArray_DATA(capi_params_map_tmp));

  /* Processing variable kind_map */
    f2py_success = long_long_from_pyobj(&kind_map,kind_map_capi,"STRUPHY_pusher.pusher_step4() 3rd argument (kind_map) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"STRUPHY_pusher.pusher_step4() 2nd argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n1_particles */
  if (n1_particles_capi == Py_None) n1_particles = shape(particles,1); else
    f2py_success = int_from_pyobj(&n1_particles,n1_particles_capi,"STRUPHY_pusher.pusher_step4() 2nd keyword (n1_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,1)==n1_particles,"shape(particles,1)==n1_particles","2nd keyword n1_particles","pusher_step4:n1_particles=%d",n1_particles) {
  /* Processing variable n0_params_map */
  if (n0_params_map_capi == Py_None) n0_params_map = len(params_map); else
    f2py_success = int_from_pyobj(&n0_params_map,n0_params_map_capi,"STRUPHY_pusher.pusher_step4() 3rd keyword (n0_params_map) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params_map)>=n0_params_map,"len(params_map)>=n0_params_map","3rd keyword n0_params_map","pusher_step4:n0_params_map=%d",n0_params_map) {
  /* Processing variable n0_particles */
  if (n0_particles_capi == Py_None) n0_particles = shape(particles,0); else
    f2py_success = int_from_pyobj(&n0_particles,n0_particles_capi,"STRUPHY_pusher.pusher_step4() 1st keyword (n0_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,0)==n0_particles,"shape(particles,0)==n0_particles","1st keyword n0_particles","pusher_step4:n0_particles=%d",n0_particles) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles,&n1_particles,particles,&dt,&kind_map,&n0_params_map,params_map);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(particles,0)==n0_particles)*/
  } /*if (f2py_success) of n0_particles*/
  /* End of cleaning variable n0_particles */
  } /*CHECKSCALAR(len(params_map)>=n0_params_map)*/
  } /*if (f2py_success) of n0_params_map*/
  /* End of cleaning variable n0_params_map */
  } /*CHECKSCALAR(shape(particles,1)==n1_particles)*/
  } /*if (f2py_success) of n1_particles*/
  /* End of cleaning variable n1_particles */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  } /*if (f2py_success) of kind_map*/
  /* End of cleaning variable kind_map */
  if((PyObject *)capi_params_map_tmp!=params_map_capi) {
    Py_XDECREF(capi_params_map_tmp); }
  }  /*if (capi_params_map_tmp == NULL) ... else of params_map*/
  /* End of cleaning variable params_map */
  if((PyObject *)capi_particles_tmp!=particles_capi) {
    Py_XDECREF(capi_particles_tmp); }
  }  /*if (capi_particles_tmp == NULL) ... else of particles*/
  /* End of cleaning variable particles */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of pusher_step4 ****************************/

/******************************** pusher_step5 ********************************/
static char doc_f2py_rout_STRUPHY_pusher_pusher_step5[] = "\
pusher_step5(particles,dt,b_part,kind_map,params_map,[n0_particles,n1_particles,n0_b_part,n1_b_part,n0_params_map])\n\nWrapper for ``pusher_step5``.\
\n\nParameters\n----------\n"
"particles : in/output rank-2 array('d') with bounds (n0_particles,n1_particles)\n"
"dt : input float\n"
"b_part : input rank-2 array('d') with bounds (n0_b_part,n1_b_part)\n"
"kind_map : input long\n"
"params_map : input rank-1 array('d') with bounds (n0_params_map)\n"
"\nOther Parameters\n----------------\n"
"n0_particles : input int, optional\n    Default: shape(particles,0)\n"
"n1_particles : input int, optional\n    Default: shape(particles,1)\n"
"n0_b_part : input int, optional\n    Default: shape(b_part,0)\n"
"n1_b_part : input int, optional\n    Default: shape(b_part,1)\n"
"n0_params_map : input int, optional\n    Default: len(params_map)";
/* extern void F_FUNC_US(pusher_step5,PUSHER_STEP5)(int*,int*,double*,double*,int*,int*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_pusher_pusher_step5(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,int*,int*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles = 0;
  PyObject *n0_particles_capi = Py_None;
  int n1_particles = 0;
  PyObject *n1_particles_capi = Py_None;
  double *particles = NULL;
  npy_intp particles_Dims[2] = {-1, -1};
  const int particles_Rank = 2;
  PyArrayObject *capi_particles_tmp = NULL;
  int capi_particles_intent = 0;
  PyObject *particles_capi = Py_None;
  double dt = 0;
  PyObject *dt_capi = Py_None;
  int n0_b_part = 0;
  PyObject *n0_b_part_capi = Py_None;
  int n1_b_part = 0;
  PyObject *n1_b_part_capi = Py_None;
  double *b_part = NULL;
  npy_intp b_part_Dims[2] = {-1, -1};
  const int b_part_Rank = 2;
  PyArrayObject *capi_b_part_tmp = NULL;
  int capi_b_part_intent = 0;
  PyObject *b_part_capi = Py_None;
  long_long kind_map = 0;
  PyObject *kind_map_capi = Py_None;
  int n0_params_map = 0;
  PyObject *n0_params_map_capi = Py_None;
  double *params_map = NULL;
  npy_intp params_map_Dims[1] = {-1};
  const int params_map_Rank = 1;
  PyArrayObject *capi_params_map_tmp = NULL;
  int capi_params_map_intent = 0;
  PyObject *params_map_capi = Py_None;
  static char *capi_kwlist[] = {"particles","dt","b_part","kind_map","params_map","n0_particles","n1_particles","n0_b_part","n1_b_part","n0_params_map",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOOOO:STRUPHY_pusher.pusher_step5",\
    capi_kwlist,&particles_capi,&dt_capi,&b_part_capi,&kind_map_capi,&params_map_capi,&n0_particles_capi,&n1_particles_capi,&n0_b_part_capi,&n1_b_part_capi,&n0_params_map_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable particles */
  ;
  capi_particles_intent |= F2PY_INTENT_INOUT;
  capi_particles_tmp = array_from_pyobj(NPY_DOUBLE,particles_Dims,particles_Rank,capi_particles_intent,particles_capi);
  if (capi_particles_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 1st argument `particles' of STRUPHY_pusher.pusher_step5 to C/Fortran array" );
  } else {
    particles = (double *)(PyArray_DATA(capi_particles_tmp));

  /* Processing variable dt */
    f2py_success = double_from_pyobj(&dt,dt_capi,"STRUPHY_pusher.pusher_step5() 2nd argument (dt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable params_map */
  ;
  capi_params_map_intent |= F2PY_INTENT_IN;
  capi_params_map_tmp = array_from_pyobj(NPY_DOUBLE,params_map_Dims,params_map_Rank,capi_params_map_intent,params_map_capi);
  if (capi_params_map_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 5th argument `params_map' of STRUPHY_pusher.pusher_step5 to C/Fortran array" );
  } else {
    params_map = (double *)(PyArray_DATA(capi_params_map_tmp));

  /* Processing variable b_part */
  ;
  capi_b_part_intent |= F2PY_INTENT_IN;
  capi_b_part_tmp = array_from_pyobj(NPY_DOUBLE,b_part_Dims,b_part_Rank,capi_b_part_intent,b_part_capi);
  if (capi_b_part_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_pusher_error,"failed in converting 3rd argument `b_part' of STRUPHY_pusher.pusher_step5 to C/Fortran array" );
  } else {
    b_part = (double *)(PyArray_DATA(capi_b_part_tmp));

  /* Processing variable kind_map */
    f2py_success = long_long_from_pyobj(&kind_map,kind_map_capi,"STRUPHY_pusher.pusher_step5() 4th argument (kind_map) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable n0_particles */
  if (n0_particles_capi == Py_None) n0_particles = shape(particles,0); else
    f2py_success = int_from_pyobj(&n0_particles,n0_particles_capi,"STRUPHY_pusher.pusher_step5() 1st keyword (n0_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,0)==n0_particles,"shape(particles,0)==n0_particles","1st keyword n0_particles","pusher_step5:n0_particles=%d",n0_particles) {
  /* Processing variable n1_particles */
  if (n1_particles_capi == Py_None) n1_particles = shape(particles,1); else
    f2py_success = int_from_pyobj(&n1_particles,n1_particles_capi,"STRUPHY_pusher.pusher_step5() 2nd keyword (n1_particles) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles,1)==n1_particles,"shape(particles,1)==n1_particles","2nd keyword n1_particles","pusher_step5:n1_particles=%d",n1_particles) {
  /* Processing variable n0_params_map */
  if (n0_params_map_capi == Py_None) n0_params_map = len(params_map); else
    f2py_success = int_from_pyobj(&n0_params_map,n0_params_map_capi,"STRUPHY_pusher.pusher_step5() 5th keyword (n0_params_map) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params_map)>=n0_params_map,"len(params_map)>=n0_params_map","5th keyword n0_params_map","pusher_step5:n0_params_map=%d",n0_params_map) {
  /* Processing variable n1_b_part */
  if (n1_b_part_capi == Py_None) n1_b_part = shape(b_part,1); else
    f2py_success = int_from_pyobj(&n1_b_part,n1_b_part_capi,"STRUPHY_pusher.pusher_step5() 4th keyword (n1_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,1)==n1_b_part,"shape(b_part,1)==n1_b_part","4th keyword n1_b_part","pusher_step5:n1_b_part=%d",n1_b_part) {
  /* Processing variable n0_b_part */
  if (n0_b_part_capi == Py_None) n0_b_part = shape(b_part,0); else
    f2py_success = int_from_pyobj(&n0_b_part,n0_b_part_capi,"STRUPHY_pusher.pusher_step5() 3rd keyword (n0_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,0)==n0_b_part,"shape(b_part,0)==n0_b_part","3rd keyword n0_b_part","pusher_step5:n0_b_part=%d",n0_b_part) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles,&n1_particles,particles,&dt,&n0_b_part,&n1_b_part,b_part,&kind_map,&n0_params_map,params_map);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(b_part,0)==n0_b_part)*/
  } /*if (f2py_success) of n0_b_part*/
  /* End of cleaning variable n0_b_part */
  } /*CHECKSCALAR(shape(b_part,1)==n1_b_part)*/
  } /*if (f2py_success) of n1_b_part*/
  /* End of cleaning variable n1_b_part */
  } /*CHECKSCALAR(len(params_map)>=n0_params_map)*/
  } /*if (f2py_success) of n0_params_map*/
  /* End of cleaning variable n0_params_map */
  } /*CHECKSCALAR(shape(particles,1)==n1_particles)*/
  } /*if (f2py_success) of n1_particles*/
  /* End of cleaning variable n1_particles */
  } /*CHECKSCALAR(shape(particles,0)==n0_particles)*/
  } /*if (f2py_success) of n0_particles*/
  /* End of cleaning variable n0_particles */
  } /*if (f2py_success) of kind_map*/
  /* End of cleaning variable kind_map */
  if((PyObject *)capi_b_part_tmp!=b_part_capi) {
    Py_XDECREF(capi_b_part_tmp); }
  }  /*if (capi_b_part_tmp == NULL) ... else of b_part*/
  /* End of cleaning variable b_part */
  if((PyObject *)capi_params_map_tmp!=params_map_capi) {
    Py_XDECREF(capi_params_map_tmp); }
  }  /*if (capi_params_map_tmp == NULL) ... else of params_map*/
  /* End of cleaning variable params_map */
  } /*if (f2py_success) of dt*/
  /* End of cleaning variable dt */
  if((PyObject *)capi_particles_tmp!=particles_capi) {
    Py_XDECREF(capi_particles_tmp); }
  }  /*if (capi_particles_tmp == NULL) ... else of particles*/
  /* End of cleaning variable particles */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of pusher_step5 ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"pusher_step3",-1,{{-1}},0,(char *)F_FUNC_US(pusher_step3,PUSHER_STEP3),(f2py_init_func)f2py_rout_STRUPHY_pusher_pusher_step3,doc_f2py_rout_STRUPHY_pusher_pusher_step3},
  {"pusher_step4",-1,{{-1}},0,(char *)F_FUNC_US(pusher_step4,PUSHER_STEP4),(f2py_init_func)f2py_rout_STRUPHY_pusher_pusher_step4,doc_f2py_rout_STRUPHY_pusher_pusher_step4},
  {"pusher_step5",-1,{{-1}},0,(char *)F_FUNC_US(pusher_step5,PUSHER_STEP5),(f2py_init_func)f2py_rout_STRUPHY_pusher_pusher_step5,doc_f2py_rout_STRUPHY_pusher_pusher_step5},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "STRUPHY_pusher",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_STRUPHY_pusher(void) {
#else
#define RETVAL
PyMODINIT_FUNC initSTRUPHY_pusher(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = STRUPHY_pusher_module = PyModule_Create(&moduledef);
#else
  m = STRUPHY_pusher_module = Py_InitModule("STRUPHY_pusher", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module STRUPHY_pusher (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'STRUPHY_pusher' is auto-generated with f2py (version:2).\nFunctions:\n"
"  pusher_step3(particles,dt,b_part,u_part,kind_map,params_map,n0_particles=shape(particles,0),n1_particles=shape(particles,1),n0_b_part=shape(b_part,0),n1_b_part=shape(b_part,1),n0_u_part=shape(u_part,0),n1_u_part=shape(u_part,1),n0_params_map=len(params_map))\n"
"  pusher_step4(particles,dt,kind_map,params_map,n0_particles=shape(particles,0),n1_particles=shape(particles,1),n0_params_map=len(params_map))\n"
"  pusher_step5(particles,dt,b_part,kind_map,params_map,n0_particles=shape(particles,0),n1_particles=shape(particles,1),n0_b_part=shape(b_part,0),n1_b_part=shape(b_part,1),n0_params_map=len(params_map))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  STRUPHY_pusher_error = PyErr_NewException ("STRUPHY_pusher.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"STRUPHY_pusher");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
