/* File: STRUPHY_fieldsmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Feb 18 12:06:41 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *STRUPHY_fields_error;
static PyObject *STRUPHY_fields_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(STRUPHY_fields_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = STRUPHY_fields_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(evaluate_1form,EVALUATE_1FORM)(int*,int*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,int*,int*,int*,double*,int*,int*,int*,double*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*);
extern void F_FUNC_US(evaluate_2form,EVALUATE_2FORM)(int*,int*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,int*,int*,int*,double*,int*,int*,int*,double*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* evaluate_1form *******************************/
static char doc_f2py_rout_STRUPHY_fields_evaluate_1form[] = "\
evaluate_1form(particles_pos,p0,spans0,nbase,np,u1,u2,u3,ueq,pp0_1,pp0_2,pp0_3,pp1_1,pp1_2,pp1_3,u_part,[n0_particles_pos,n1_particles_pos,n0_p0,n0_spans0,n1_spans0,n0_nbase,n0_u1,n1_u1,n2_u1,n0_u2,n1_u2,n2_u2,n0_u3,n1_u3,n2_u3,n0_ueq,n0_pp0_1,n1_pp0_1,n0_pp0_2,n1_pp0_2,n0_pp0_3,n1_pp0_3,n0_pp1_1,n1_pp1_1,n0_pp1_2,n1_pp1_2,n0_pp1_3,n1_pp1_3,n0_u_part,n1_u_part])\n\nWrapper for ``evaluate_1form``.\
\n\nParameters\n----------\n"
"particles_pos : input rank-2 array('d') with bounds (n0_particles_pos,n1_particles_pos)\n"
"p0 : input rank-1 array('i') with bounds (n0_p0)\n"
"spans0 : input rank-2 array('i') with bounds (n0_spans0,n1_spans0)\n"
"nbase : input rank-1 array('i') with bounds (n0_nbase)\n"
"np : input int\n"
"u1 : input rank-3 array('d') with bounds (n0_u1,n1_u1,n2_u1)\n"
"u2 : input rank-3 array('d') with bounds (n0_u2,n1_u2,n2_u2)\n"
"u3 : input rank-3 array('d') with bounds (n0_u3,n1_u3,n2_u3)\n"
"ueq : input rank-1 array('d') with bounds (n0_ueq)\n"
"pp0_1 : input rank-2 array('d') with bounds (n0_pp0_1,n1_pp0_1)\n"
"pp0_2 : input rank-2 array('d') with bounds (n0_pp0_2,n1_pp0_2)\n"
"pp0_3 : input rank-2 array('d') with bounds (n0_pp0_3,n1_pp0_3)\n"
"pp1_1 : input rank-2 array('d') with bounds (n0_pp1_1,n1_pp1_1)\n"
"pp1_2 : input rank-2 array('d') with bounds (n0_pp1_2,n1_pp1_2)\n"
"pp1_3 : input rank-2 array('d') with bounds (n0_pp1_3,n1_pp1_3)\n"
"u_part : in/output rank-2 array('d') with bounds (n0_u_part,n1_u_part)\n"
"\nOther Parameters\n----------------\n"
"n0_particles_pos : input int, optional\n    Default: shape(particles_pos,0)\n"
"n1_particles_pos : input int, optional\n    Default: shape(particles_pos,1)\n"
"n0_p0 : input int, optional\n    Default: len(p0)\n"
"n0_spans0 : input int, optional\n    Default: shape(spans0,0)\n"
"n1_spans0 : input int, optional\n    Default: shape(spans0,1)\n"
"n0_nbase : input int, optional\n    Default: len(nbase)\n"
"n0_u1 : input int, optional\n    Default: shape(u1,0)\n"
"n1_u1 : input int, optional\n    Default: shape(u1,1)\n"
"n2_u1 : input int, optional\n    Default: shape(u1,2)\n"
"n0_u2 : input int, optional\n    Default: shape(u2,0)\n"
"n1_u2 : input int, optional\n    Default: shape(u2,1)\n"
"n2_u2 : input int, optional\n    Default: shape(u2,2)\n"
"n0_u3 : input int, optional\n    Default: shape(u3,0)\n"
"n1_u3 : input int, optional\n    Default: shape(u3,1)\n"
"n2_u3 : input int, optional\n    Default: shape(u3,2)\n"
"n0_ueq : input int, optional\n    Default: len(ueq)\n"
"n0_pp0_1 : input int, optional\n    Default: shape(pp0_1,0)\n"
"n1_pp0_1 : input int, optional\n    Default: shape(pp0_1,1)\n"
"n0_pp0_2 : input int, optional\n    Default: shape(pp0_2,0)\n"
"n1_pp0_2 : input int, optional\n    Default: shape(pp0_2,1)\n"
"n0_pp0_3 : input int, optional\n    Default: shape(pp0_3,0)\n"
"n1_pp0_3 : input int, optional\n    Default: shape(pp0_3,1)\n"
"n0_pp1_1 : input int, optional\n    Default: shape(pp1_1,0)\n"
"n1_pp1_1 : input int, optional\n    Default: shape(pp1_1,1)\n"
"n0_pp1_2 : input int, optional\n    Default: shape(pp1_2,0)\n"
"n1_pp1_2 : input int, optional\n    Default: shape(pp1_2,1)\n"
"n0_pp1_3 : input int, optional\n    Default: shape(pp1_3,0)\n"
"n1_pp1_3 : input int, optional\n    Default: shape(pp1_3,1)\n"
"n0_u_part : input int, optional\n    Default: shape(u_part,0)\n"
"n1_u_part : input int, optional\n    Default: shape(u_part,1)";
/* extern void F_FUNC_US(evaluate_1form,EVALUATE_1FORM)(int*,int*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,int*,int*,int*,double*,int*,int*,int*,double*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_fields_evaluate_1form(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,int*,int*,int*,double*,int*,int*,int*,double*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles_pos = 0;
  PyObject *n0_particles_pos_capi = Py_None;
  int n1_particles_pos = 0;
  PyObject *n1_particles_pos_capi = Py_None;
  double *particles_pos = NULL;
  npy_intp particles_pos_Dims[2] = {-1, -1};
  const int particles_pos_Rank = 2;
  PyArrayObject *capi_particles_pos_tmp = NULL;
  int capi_particles_pos_intent = 0;
  PyObject *particles_pos_capi = Py_None;
  int n0_p0 = 0;
  PyObject *n0_p0_capi = Py_None;
  int *p0 = NULL;
  npy_intp p0_Dims[1] = {-1};
  const int p0_Rank = 1;
  PyArrayObject *capi_p0_tmp = NULL;
  int capi_p0_intent = 0;
  PyObject *p0_capi = Py_None;
  int n0_spans0 = 0;
  PyObject *n0_spans0_capi = Py_None;
  int n1_spans0 = 0;
  PyObject *n1_spans0_capi = Py_None;
  int *spans0 = NULL;
  npy_intp spans0_Dims[2] = {-1, -1};
  const int spans0_Rank = 2;
  PyArrayObject *capi_spans0_tmp = NULL;
  int capi_spans0_intent = 0;
  PyObject *spans0_capi = Py_None;
  int n0_nbase = 0;
  PyObject *n0_nbase_capi = Py_None;
  int *nbase = NULL;
  npy_intp nbase_Dims[1] = {-1};
  const int nbase_Rank = 1;
  PyArrayObject *capi_nbase_tmp = NULL;
  int capi_nbase_intent = 0;
  PyObject *nbase_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  int n0_u1 = 0;
  PyObject *n0_u1_capi = Py_None;
  int n1_u1 = 0;
  PyObject *n1_u1_capi = Py_None;
  int n2_u1 = 0;
  PyObject *n2_u1_capi = Py_None;
  double *u1 = NULL;
  npy_intp u1_Dims[3] = {-1, -1, -1};
  const int u1_Rank = 3;
  PyArrayObject *capi_u1_tmp = NULL;
  int capi_u1_intent = 0;
  PyObject *u1_capi = Py_None;
  int n0_u2 = 0;
  PyObject *n0_u2_capi = Py_None;
  int n1_u2 = 0;
  PyObject *n1_u2_capi = Py_None;
  int n2_u2 = 0;
  PyObject *n2_u2_capi = Py_None;
  double *u2 = NULL;
  npy_intp u2_Dims[3] = {-1, -1, -1};
  const int u2_Rank = 3;
  PyArrayObject *capi_u2_tmp = NULL;
  int capi_u2_intent = 0;
  PyObject *u2_capi = Py_None;
  int n0_u3 = 0;
  PyObject *n0_u3_capi = Py_None;
  int n1_u3 = 0;
  PyObject *n1_u3_capi = Py_None;
  int n2_u3 = 0;
  PyObject *n2_u3_capi = Py_None;
  double *u3 = NULL;
  npy_intp u3_Dims[3] = {-1, -1, -1};
  const int u3_Rank = 3;
  PyArrayObject *capi_u3_tmp = NULL;
  int capi_u3_intent = 0;
  PyObject *u3_capi = Py_None;
  int n0_ueq = 0;
  PyObject *n0_ueq_capi = Py_None;
  double *ueq = NULL;
  npy_intp ueq_Dims[1] = {-1};
  const int ueq_Rank = 1;
  PyArrayObject *capi_ueq_tmp = NULL;
  int capi_ueq_intent = 0;
  PyObject *ueq_capi = Py_None;
  int n0_pp0_1 = 0;
  PyObject *n0_pp0_1_capi = Py_None;
  int n1_pp0_1 = 0;
  PyObject *n1_pp0_1_capi = Py_None;
  double *pp0_1 = NULL;
  npy_intp pp0_1_Dims[2] = {-1, -1};
  const int pp0_1_Rank = 2;
  PyArrayObject *capi_pp0_1_tmp = NULL;
  int capi_pp0_1_intent = 0;
  PyObject *pp0_1_capi = Py_None;
  int n0_pp0_2 = 0;
  PyObject *n0_pp0_2_capi = Py_None;
  int n1_pp0_2 = 0;
  PyObject *n1_pp0_2_capi = Py_None;
  double *pp0_2 = NULL;
  npy_intp pp0_2_Dims[2] = {-1, -1};
  const int pp0_2_Rank = 2;
  PyArrayObject *capi_pp0_2_tmp = NULL;
  int capi_pp0_2_intent = 0;
  PyObject *pp0_2_capi = Py_None;
  int n0_pp0_3 = 0;
  PyObject *n0_pp0_3_capi = Py_None;
  int n1_pp0_3 = 0;
  PyObject *n1_pp0_3_capi = Py_None;
  double *pp0_3 = NULL;
  npy_intp pp0_3_Dims[2] = {-1, -1};
  const int pp0_3_Rank = 2;
  PyArrayObject *capi_pp0_3_tmp = NULL;
  int capi_pp0_3_intent = 0;
  PyObject *pp0_3_capi = Py_None;
  int n0_pp1_1 = 0;
  PyObject *n0_pp1_1_capi = Py_None;
  int n1_pp1_1 = 0;
  PyObject *n1_pp1_1_capi = Py_None;
  double *pp1_1 = NULL;
  npy_intp pp1_1_Dims[2] = {-1, -1};
  const int pp1_1_Rank = 2;
  PyArrayObject *capi_pp1_1_tmp = NULL;
  int capi_pp1_1_intent = 0;
  PyObject *pp1_1_capi = Py_None;
  int n0_pp1_2 = 0;
  PyObject *n0_pp1_2_capi = Py_None;
  int n1_pp1_2 = 0;
  PyObject *n1_pp1_2_capi = Py_None;
  double *pp1_2 = NULL;
  npy_intp pp1_2_Dims[2] = {-1, -1};
  const int pp1_2_Rank = 2;
  PyArrayObject *capi_pp1_2_tmp = NULL;
  int capi_pp1_2_intent = 0;
  PyObject *pp1_2_capi = Py_None;
  int n0_pp1_3 = 0;
  PyObject *n0_pp1_3_capi = Py_None;
  int n1_pp1_3 = 0;
  PyObject *n1_pp1_3_capi = Py_None;
  double *pp1_3 = NULL;
  npy_intp pp1_3_Dims[2] = {-1, -1};
  const int pp1_3_Rank = 2;
  PyArrayObject *capi_pp1_3_tmp = NULL;
  int capi_pp1_3_intent = 0;
  PyObject *pp1_3_capi = Py_None;
  int n0_u_part = 0;
  PyObject *n0_u_part_capi = Py_None;
  int n1_u_part = 0;
  PyObject *n1_u_part_capi = Py_None;
  double *u_part = NULL;
  npy_intp u_part_Dims[2] = {-1, -1};
  const int u_part_Rank = 2;
  PyArrayObject *capi_u_part_tmp = NULL;
  int capi_u_part_intent = 0;
  PyObject *u_part_capi = Py_None;
  static char *capi_kwlist[] = {"particles_pos","p0","spans0","nbase","np","u1","u2","u3","ueq","pp0_1","pp0_2","pp0_3","pp1_1","pp1_2","pp1_3","u_part","n0_particles_pos","n1_particles_pos","n0_p0","n0_spans0","n1_spans0","n0_nbase","n0_u1","n1_u1","n2_u1","n0_u2","n1_u2","n2_u2","n0_u3","n1_u3","n2_u3","n0_ueq","n0_pp0_1","n1_pp0_1","n0_pp0_2","n1_pp0_2","n0_pp0_3","n1_pp0_3","n0_pp1_1","n1_pp1_1","n0_pp1_2","n1_pp1_2","n0_pp1_3","n1_pp1_3","n0_u_part","n1_u_part",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO:STRUPHY_fields.evaluate_1form",\
    capi_kwlist,&particles_pos_capi,&p0_capi,&spans0_capi,&nbase_capi,&np_capi,&u1_capi,&u2_capi,&u3_capi,&ueq_capi,&pp0_1_capi,&pp0_2_capi,&pp0_3_capi,&pp1_1_capi,&pp1_2_capi,&pp1_3_capi,&u_part_capi,&n0_particles_pos_capi,&n1_particles_pos_capi,&n0_p0_capi,&n0_spans0_capi,&n1_spans0_capi,&n0_nbase_capi,&n0_u1_capi,&n1_u1_capi,&n2_u1_capi,&n0_u2_capi,&n1_u2_capi,&n2_u2_capi,&n0_u3_capi,&n1_u3_capi,&n2_u3_capi,&n0_ueq_capi,&n0_pp0_1_capi,&n1_pp0_1_capi,&n0_pp0_2_capi,&n1_pp0_2_capi,&n0_pp0_3_capi,&n1_pp0_3_capi,&n0_pp1_1_capi,&n1_pp1_1_capi,&n0_pp1_2_capi,&n1_pp1_2_capi,&n0_pp1_3_capi,&n1_pp1_3_capi,&n0_u_part_capi,&n1_u_part_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ueq */
  ;
  capi_ueq_intent |= F2PY_INTENT_IN;
  capi_ueq_tmp = array_from_pyobj(NPY_DOUBLE,ueq_Dims,ueq_Rank,capi_ueq_intent,ueq_capi);
  if (capi_ueq_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 9th argument `ueq' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    ueq = (double *)(PyArray_DATA(capi_ueq_tmp));

  /* Processing variable pp0_2 */
  ;
  capi_pp0_2_intent |= F2PY_INTENT_IN;
  capi_pp0_2_tmp = array_from_pyobj(NPY_DOUBLE,pp0_2_Dims,pp0_2_Rank,capi_pp0_2_intent,pp0_2_capi);
  if (capi_pp0_2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 11st argument `pp0_2' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    pp0_2 = (double *)(PyArray_DATA(capi_pp0_2_tmp));

  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"STRUPHY_fields.evaluate_1form() 5th argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pp0_1 */
  ;
  capi_pp0_1_intent |= F2PY_INTENT_IN;
  capi_pp0_1_tmp = array_from_pyobj(NPY_DOUBLE,pp0_1_Dims,pp0_1_Rank,capi_pp0_1_intent,pp0_1_capi);
  if (capi_pp0_1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 10th argument `pp0_1' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    pp0_1 = (double *)(PyArray_DATA(capi_pp0_1_tmp));

  /* Processing variable u2 */
  ;
  capi_u2_intent |= F2PY_INTENT_IN;
  capi_u2_tmp = array_from_pyobj(NPY_DOUBLE,u2_Dims,u2_Rank,capi_u2_intent,u2_capi);
  if (capi_u2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 7th argument `u2' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    u2 = (double *)(PyArray_DATA(capi_u2_tmp));

  /* Processing variable pp1_1 */
  ;
  capi_pp1_1_intent |= F2PY_INTENT_IN;
  capi_pp1_1_tmp = array_from_pyobj(NPY_DOUBLE,pp1_1_Dims,pp1_1_Rank,capi_pp1_1_intent,pp1_1_capi);
  if (capi_pp1_1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 13rd argument `pp1_1' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    pp1_1 = (double *)(PyArray_DATA(capi_pp1_1_tmp));

  /* Processing variable pp1_2 */
  ;
  capi_pp1_2_intent |= F2PY_INTENT_IN;
  capi_pp1_2_tmp = array_from_pyobj(NPY_DOUBLE,pp1_2_Dims,pp1_2_Rank,capi_pp1_2_intent,pp1_2_capi);
  if (capi_pp1_2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 14th argument `pp1_2' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    pp1_2 = (double *)(PyArray_DATA(capi_pp1_2_tmp));

  /* Processing variable pp1_3 */
  ;
  capi_pp1_3_intent |= F2PY_INTENT_IN;
  capi_pp1_3_tmp = array_from_pyobj(NPY_DOUBLE,pp1_3_Dims,pp1_3_Rank,capi_pp1_3_intent,pp1_3_capi);
  if (capi_pp1_3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 15th argument `pp1_3' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    pp1_3 = (double *)(PyArray_DATA(capi_pp1_3_tmp));

  /* Processing variable p0 */
  ;
  capi_p0_intent |= F2PY_INTENT_IN;
  capi_p0_tmp = array_from_pyobj(NPY_INT,p0_Dims,p0_Rank,capi_p0_intent,p0_capi);
  if (capi_p0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 2nd argument `p0' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    p0 = (int *)(PyArray_DATA(capi_p0_tmp));

  /* Processing variable nbase */
  ;
  capi_nbase_intent |= F2PY_INTENT_IN;
  capi_nbase_tmp = array_from_pyobj(NPY_INT,nbase_Dims,nbase_Rank,capi_nbase_intent,nbase_capi);
  if (capi_nbase_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 4th argument `nbase' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    nbase = (int *)(PyArray_DATA(capi_nbase_tmp));

  /* Processing variable u_part */
  ;
  capi_u_part_intent |= F2PY_INTENT_INOUT;
  capi_u_part_tmp = array_from_pyobj(NPY_DOUBLE,u_part_Dims,u_part_Rank,capi_u_part_intent,u_part_capi);
  if (capi_u_part_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 16th argument `u_part' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    u_part = (double *)(PyArray_DATA(capi_u_part_tmp));

  /* Processing variable particles_pos */
  ;
  capi_particles_pos_intent |= F2PY_INTENT_IN;
  capi_particles_pos_tmp = array_from_pyobj(NPY_DOUBLE,particles_pos_Dims,particles_pos_Rank,capi_particles_pos_intent,particles_pos_capi);
  if (capi_particles_pos_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 1st argument `particles_pos' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    particles_pos = (double *)(PyArray_DATA(capi_particles_pos_tmp));

  /* Processing variable spans0 */
  ;
  capi_spans0_intent |= F2PY_INTENT_IN;
  capi_spans0_tmp = array_from_pyobj(NPY_INT,spans0_Dims,spans0_Rank,capi_spans0_intent,spans0_capi);
  if (capi_spans0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 3rd argument `spans0' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    spans0 = (int *)(PyArray_DATA(capi_spans0_tmp));

  /* Processing variable pp0_3 */
  ;
  capi_pp0_3_intent |= F2PY_INTENT_IN;
  capi_pp0_3_tmp = array_from_pyobj(NPY_DOUBLE,pp0_3_Dims,pp0_3_Rank,capi_pp0_3_intent,pp0_3_capi);
  if (capi_pp0_3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 12nd argument `pp0_3' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    pp0_3 = (double *)(PyArray_DATA(capi_pp0_3_tmp));

  /* Processing variable u1 */
  ;
  capi_u1_intent |= F2PY_INTENT_IN;
  capi_u1_tmp = array_from_pyobj(NPY_DOUBLE,u1_Dims,u1_Rank,capi_u1_intent,u1_capi);
  if (capi_u1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 6th argument `u1' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    u1 = (double *)(PyArray_DATA(capi_u1_tmp));

  /* Processing variable u3 */
  ;
  capi_u3_intent |= F2PY_INTENT_IN;
  capi_u3_tmp = array_from_pyobj(NPY_DOUBLE,u3_Dims,u3_Rank,capi_u3_intent,u3_capi);
  if (capi_u3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 8th argument `u3' of STRUPHY_fields.evaluate_1form to C/Fortran array" );
  } else {
    u3 = (double *)(PyArray_DATA(capi_u3_tmp));

  /* Processing variable n0_ueq */
  if (n0_ueq_capi == Py_None) n0_ueq = len(ueq); else
    f2py_success = int_from_pyobj(&n0_ueq,n0_ueq_capi,"STRUPHY_fields.evaluate_1form() 16th keyword (n0_ueq) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(ueq)>=n0_ueq,"len(ueq)>=n0_ueq","16th keyword n0_ueq","evaluate_1form:n0_ueq=%d",n0_ueq) {
  /* Processing variable n1_u_part */
  if (n1_u_part_capi == Py_None) n1_u_part = shape(u_part,1); else
    f2py_success = int_from_pyobj(&n1_u_part,n1_u_part_capi,"STRUPHY_fields.evaluate_1form() 30th keyword (n1_u_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u_part,1)==n1_u_part,"shape(u_part,1)==n1_u_part","30th keyword n1_u_part","evaluate_1form:n1_u_part=%d",n1_u_part) {
  /* Processing variable n2_u1 */
  if (n2_u1_capi == Py_None) n2_u1 = shape(u1,2); else
    f2py_success = int_from_pyobj(&n2_u1,n2_u1_capi,"STRUPHY_fields.evaluate_1form() 9th keyword (n2_u1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u1,2)==n2_u1,"shape(u1,2)==n2_u1","9th keyword n2_u1","evaluate_1form:n2_u1=%d",n2_u1) {
  /* Processing variable n1_pp0_3 */
  if (n1_pp0_3_capi == Py_None) n1_pp0_3 = shape(pp0_3,1); else
    f2py_success = int_from_pyobj(&n1_pp0_3,n1_pp0_3_capi,"STRUPHY_fields.evaluate_1form() 22nd keyword (n1_pp0_3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_3,1)==n1_pp0_3,"shape(pp0_3,1)==n1_pp0_3","22nd keyword n1_pp0_3","evaluate_1form:n1_pp0_3=%d",n1_pp0_3) {
  /* Processing variable n1_particles_pos */
  if (n1_particles_pos_capi == Py_None) n1_particles_pos = shape(particles_pos,1); else
    f2py_success = int_from_pyobj(&n1_particles_pos,n1_particles_pos_capi,"STRUPHY_fields.evaluate_1form() 2nd keyword (n1_particles_pos) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles_pos,1)==n1_particles_pos,"shape(particles_pos,1)==n1_particles_pos","2nd keyword n1_particles_pos","evaluate_1form:n1_particles_pos=%d",n1_particles_pos) {
  /* Processing variable n0_nbase */
  if (n0_nbase_capi == Py_None) n0_nbase = len(nbase); else
    f2py_success = int_from_pyobj(&n0_nbase,n0_nbase_capi,"STRUPHY_fields.evaluate_1form() 6th keyword (n0_nbase) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(nbase)>=n0_nbase,"len(nbase)>=n0_nbase","6th keyword n0_nbase","evaluate_1form:n0_nbase=%d",n0_nbase) {
  /* Processing variable n2_u3 */
  if (n2_u3_capi == Py_None) n2_u3 = shape(u3,2); else
    f2py_success = int_from_pyobj(&n2_u3,n2_u3_capi,"STRUPHY_fields.evaluate_1form() 15th keyword (n2_u3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u3,2)==n2_u3,"shape(u3,2)==n2_u3","15th keyword n2_u3","evaluate_1form:n2_u3=%d",n2_u3) {
  /* Processing variable n1_pp1_3 */
  if (n1_pp1_3_capi == Py_None) n1_pp1_3 = shape(pp1_3,1); else
    f2py_success = int_from_pyobj(&n1_pp1_3,n1_pp1_3_capi,"STRUPHY_fields.evaluate_1form() 28th keyword (n1_pp1_3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_3,1)==n1_pp1_3,"shape(pp1_3,1)==n1_pp1_3","28th keyword n1_pp1_3","evaluate_1form:n1_pp1_3=%d",n1_pp1_3) {
  /* Processing variable n1_spans0 */
  if (n1_spans0_capi == Py_None) n1_spans0 = shape(spans0,1); else
    f2py_success = int_from_pyobj(&n1_spans0,n1_spans0_capi,"STRUPHY_fields.evaluate_1form() 5th keyword (n1_spans0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(spans0,1)==n1_spans0,"shape(spans0,1)==n1_spans0","5th keyword n1_spans0","evaluate_1form:n1_spans0=%d",n1_spans0) {
  /* Processing variable n0_pp0_3 */
  if (n0_pp0_3_capi == Py_None) n0_pp0_3 = shape(pp0_3,0); else
    f2py_success = int_from_pyobj(&n0_pp0_3,n0_pp0_3_capi,"STRUPHY_fields.evaluate_1form() 21st keyword (n0_pp0_3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_3,0)==n0_pp0_3,"shape(pp0_3,0)==n0_pp0_3","21st keyword n0_pp0_3","evaluate_1form:n0_pp0_3=%d",n0_pp0_3) {
  /* Processing variable n0_u1 */
  if (n0_u1_capi == Py_None) n0_u1 = shape(u1,0); else
    f2py_success = int_from_pyobj(&n0_u1,n0_u1_capi,"STRUPHY_fields.evaluate_1form() 7th keyword (n0_u1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u1,0)==n0_u1,"shape(u1,0)==n0_u1","7th keyword n0_u1","evaluate_1form:n0_u1=%d",n0_u1) {
  /* Processing variable n1_pp1_2 */
  if (n1_pp1_2_capi == Py_None) n1_pp1_2 = shape(pp1_2,1); else
    f2py_success = int_from_pyobj(&n1_pp1_2,n1_pp1_2_capi,"STRUPHY_fields.evaluate_1form() 26th keyword (n1_pp1_2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_2,1)==n1_pp1_2,"shape(pp1_2,1)==n1_pp1_2","26th keyword n1_pp1_2","evaluate_1form:n1_pp1_2=%d",n1_pp1_2) {
  /* Processing variable n1_u1 */
  if (n1_u1_capi == Py_None) n1_u1 = shape(u1,1); else
    f2py_success = int_from_pyobj(&n1_u1,n1_u1_capi,"STRUPHY_fields.evaluate_1form() 8th keyword (n1_u1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u1,1)==n1_u1,"shape(u1,1)==n1_u1","8th keyword n1_u1","evaluate_1form:n1_u1=%d",n1_u1) {
  /* Processing variable n1_pp0_2 */
  if (n1_pp0_2_capi == Py_None) n1_pp0_2 = shape(pp0_2,1); else
    f2py_success = int_from_pyobj(&n1_pp0_2,n1_pp0_2_capi,"STRUPHY_fields.evaluate_1form() 20th keyword (n1_pp0_2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_2,1)==n1_pp0_2,"shape(pp0_2,1)==n1_pp0_2","20th keyword n1_pp0_2","evaluate_1form:n1_pp0_2=%d",n1_pp0_2) {
  /* Processing variable n1_pp0_1 */
  if (n1_pp0_1_capi == Py_None) n1_pp0_1 = shape(pp0_1,1); else
    f2py_success = int_from_pyobj(&n1_pp0_1,n1_pp0_1_capi,"STRUPHY_fields.evaluate_1form() 18th keyword (n1_pp0_1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_1,1)==n1_pp0_1,"shape(pp0_1,1)==n1_pp0_1","18th keyword n1_pp0_1","evaluate_1form:n1_pp0_1=%d",n1_pp0_1) {
  /* Processing variable n1_pp1_1 */
  if (n1_pp1_1_capi == Py_None) n1_pp1_1 = shape(pp1_1,1); else
    f2py_success = int_from_pyobj(&n1_pp1_1,n1_pp1_1_capi,"STRUPHY_fields.evaluate_1form() 24th keyword (n1_pp1_1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_1,1)==n1_pp1_1,"shape(pp1_1,1)==n1_pp1_1","24th keyword n1_pp1_1","evaluate_1form:n1_pp1_1=%d",n1_pp1_1) {
  /* Processing variable n1_u3 */
  if (n1_u3_capi == Py_None) n1_u3 = shape(u3,1); else
    f2py_success = int_from_pyobj(&n1_u3,n1_u3_capi,"STRUPHY_fields.evaluate_1form() 14th keyword (n1_u3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u3,1)==n1_u3,"shape(u3,1)==n1_u3","14th keyword n1_u3","evaluate_1form:n1_u3=%d",n1_u3) {
  /* Processing variable n2_u2 */
  if (n2_u2_capi == Py_None) n2_u2 = shape(u2,2); else
    f2py_success = int_from_pyobj(&n2_u2,n2_u2_capi,"STRUPHY_fields.evaluate_1form() 12nd keyword (n2_u2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u2,2)==n2_u2,"shape(u2,2)==n2_u2","12nd keyword n2_u2","evaluate_1form:n2_u2=%d",n2_u2) {
  /* Processing variable n1_u2 */
  if (n1_u2_capi == Py_None) n1_u2 = shape(u2,1); else
    f2py_success = int_from_pyobj(&n1_u2,n1_u2_capi,"STRUPHY_fields.evaluate_1form() 11st keyword (n1_u2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u2,1)==n1_u2,"shape(u2,1)==n1_u2","11st keyword n1_u2","evaluate_1form:n1_u2=%d",n1_u2) {
  /* Processing variable n0_spans0 */
  if (n0_spans0_capi == Py_None) n0_spans0 = shape(spans0,0); else
    f2py_success = int_from_pyobj(&n0_spans0,n0_spans0_capi,"STRUPHY_fields.evaluate_1form() 4th keyword (n0_spans0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(spans0,0)==n0_spans0,"shape(spans0,0)==n0_spans0","4th keyword n0_spans0","evaluate_1form:n0_spans0=%d",n0_spans0) {
  /* Processing variable n0_pp1_3 */
  if (n0_pp1_3_capi == Py_None) n0_pp1_3 = shape(pp1_3,0); else
    f2py_success = int_from_pyobj(&n0_pp1_3,n0_pp1_3_capi,"STRUPHY_fields.evaluate_1form() 27th keyword (n0_pp1_3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_3,0)==n0_pp1_3,"shape(pp1_3,0)==n0_pp1_3","27th keyword n0_pp1_3","evaluate_1form:n0_pp1_3=%d",n0_pp1_3) {
  /* Processing variable n0_p0 */
  if (n0_p0_capi == Py_None) n0_p0 = len(p0); else
    f2py_success = int_from_pyobj(&n0_p0,n0_p0_capi,"STRUPHY_fields.evaluate_1form() 3rd keyword (n0_p0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(p0)>=n0_p0,"len(p0)>=n0_p0","3rd keyword n0_p0","evaluate_1form:n0_p0=%d",n0_p0) {
  /* Processing variable n0_pp1_1 */
  if (n0_pp1_1_capi == Py_None) n0_pp1_1 = shape(pp1_1,0); else
    f2py_success = int_from_pyobj(&n0_pp1_1,n0_pp1_1_capi,"STRUPHY_fields.evaluate_1form() 23rd keyword (n0_pp1_1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_1,0)==n0_pp1_1,"shape(pp1_1,0)==n0_pp1_1","23rd keyword n0_pp1_1","evaluate_1form:n0_pp1_1=%d",n0_pp1_1) {
  /* Processing variable n0_pp1_2 */
  if (n0_pp1_2_capi == Py_None) n0_pp1_2 = shape(pp1_2,0); else
    f2py_success = int_from_pyobj(&n0_pp1_2,n0_pp1_2_capi,"STRUPHY_fields.evaluate_1form() 25th keyword (n0_pp1_2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_2,0)==n0_pp1_2,"shape(pp1_2,0)==n0_pp1_2","25th keyword n0_pp1_2","evaluate_1form:n0_pp1_2=%d",n0_pp1_2) {
  /* Processing variable n0_pp0_1 */
  if (n0_pp0_1_capi == Py_None) n0_pp0_1 = shape(pp0_1,0); else
    f2py_success = int_from_pyobj(&n0_pp0_1,n0_pp0_1_capi,"STRUPHY_fields.evaluate_1form() 17th keyword (n0_pp0_1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_1,0)==n0_pp0_1,"shape(pp0_1,0)==n0_pp0_1","17th keyword n0_pp0_1","evaluate_1form:n0_pp0_1=%d",n0_pp0_1) {
  /* Processing variable n0_u2 */
  if (n0_u2_capi == Py_None) n0_u2 = shape(u2,0); else
    f2py_success = int_from_pyobj(&n0_u2,n0_u2_capi,"STRUPHY_fields.evaluate_1form() 10th keyword (n0_u2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u2,0)==n0_u2,"shape(u2,0)==n0_u2","10th keyword n0_u2","evaluate_1form:n0_u2=%d",n0_u2) {
  /* Processing variable n0_particles_pos */
  if (n0_particles_pos_capi == Py_None) n0_particles_pos = shape(particles_pos,0); else
    f2py_success = int_from_pyobj(&n0_particles_pos,n0_particles_pos_capi,"STRUPHY_fields.evaluate_1form() 1st keyword (n0_particles_pos) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles_pos,0)==n0_particles_pos,"shape(particles_pos,0)==n0_particles_pos","1st keyword n0_particles_pos","evaluate_1form:n0_particles_pos=%d",n0_particles_pos) {
  /* Processing variable n0_u_part */
  if (n0_u_part_capi == Py_None) n0_u_part = shape(u_part,0); else
    f2py_success = int_from_pyobj(&n0_u_part,n0_u_part_capi,"STRUPHY_fields.evaluate_1form() 29th keyword (n0_u_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u_part,0)==n0_u_part,"shape(u_part,0)==n0_u_part","29th keyword n0_u_part","evaluate_1form:n0_u_part=%d",n0_u_part) {
  /* Processing variable n0_u3 */
  if (n0_u3_capi == Py_None) n0_u3 = shape(u3,0); else
    f2py_success = int_from_pyobj(&n0_u3,n0_u3_capi,"STRUPHY_fields.evaluate_1form() 13rd keyword (n0_u3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(u3,0)==n0_u3,"shape(u3,0)==n0_u3","13rd keyword n0_u3","evaluate_1form:n0_u3=%d",n0_u3) {
  /* Processing variable n0_pp0_2 */
  if (n0_pp0_2_capi == Py_None) n0_pp0_2 = shape(pp0_2,0); else
    f2py_success = int_from_pyobj(&n0_pp0_2,n0_pp0_2_capi,"STRUPHY_fields.evaluate_1form() 19th keyword (n0_pp0_2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_2,0)==n0_pp0_2,"shape(pp0_2,0)==n0_pp0_2","19th keyword n0_pp0_2","evaluate_1form:n0_pp0_2=%d",n0_pp0_2) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles_pos,&n1_particles_pos,particles_pos,&n0_p0,p0,&n0_spans0,&n1_spans0,spans0,&n0_nbase,nbase,&np,&n0_u1,&n1_u1,&n2_u1,u1,&n0_u2,&n1_u2,&n2_u2,u2,&n0_u3,&n1_u3,&n2_u3,u3,&n0_ueq,ueq,&n0_pp0_1,&n1_pp0_1,pp0_1,&n0_pp0_2,&n1_pp0_2,pp0_2,&n0_pp0_3,&n1_pp0_3,pp0_3,&n0_pp1_1,&n1_pp1_1,pp1_1,&n0_pp1_2,&n1_pp1_2,pp1_2,&n0_pp1_3,&n1_pp1_3,pp1_3,&n0_u_part,&n1_u_part,u_part);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(pp0_2,0)==n0_pp0_2)*/
  } /*if (f2py_success) of n0_pp0_2*/
  /* End of cleaning variable n0_pp0_2 */
  } /*CHECKSCALAR(shape(u3,0)==n0_u3)*/
  } /*if (f2py_success) of n0_u3*/
  /* End of cleaning variable n0_u3 */
  } /*CHECKSCALAR(shape(u_part,0)==n0_u_part)*/
  } /*if (f2py_success) of n0_u_part*/
  /* End of cleaning variable n0_u_part */
  } /*CHECKSCALAR(shape(particles_pos,0)==n0_particles_pos)*/
  } /*if (f2py_success) of n0_particles_pos*/
  /* End of cleaning variable n0_particles_pos */
  } /*CHECKSCALAR(shape(u2,0)==n0_u2)*/
  } /*if (f2py_success) of n0_u2*/
  /* End of cleaning variable n0_u2 */
  } /*CHECKSCALAR(shape(pp0_1,0)==n0_pp0_1)*/
  } /*if (f2py_success) of n0_pp0_1*/
  /* End of cleaning variable n0_pp0_1 */
  } /*CHECKSCALAR(shape(pp1_2,0)==n0_pp1_2)*/
  } /*if (f2py_success) of n0_pp1_2*/
  /* End of cleaning variable n0_pp1_2 */
  } /*CHECKSCALAR(shape(pp1_1,0)==n0_pp1_1)*/
  } /*if (f2py_success) of n0_pp1_1*/
  /* End of cleaning variable n0_pp1_1 */
  } /*CHECKSCALAR(len(p0)>=n0_p0)*/
  } /*if (f2py_success) of n0_p0*/
  /* End of cleaning variable n0_p0 */
  } /*CHECKSCALAR(shape(pp1_3,0)==n0_pp1_3)*/
  } /*if (f2py_success) of n0_pp1_3*/
  /* End of cleaning variable n0_pp1_3 */
  } /*CHECKSCALAR(shape(spans0,0)==n0_spans0)*/
  } /*if (f2py_success) of n0_spans0*/
  /* End of cleaning variable n0_spans0 */
  } /*CHECKSCALAR(shape(u2,1)==n1_u2)*/
  } /*if (f2py_success) of n1_u2*/
  /* End of cleaning variable n1_u2 */
  } /*CHECKSCALAR(shape(u2,2)==n2_u2)*/
  } /*if (f2py_success) of n2_u2*/
  /* End of cleaning variable n2_u2 */
  } /*CHECKSCALAR(shape(u3,1)==n1_u3)*/
  } /*if (f2py_success) of n1_u3*/
  /* End of cleaning variable n1_u3 */
  } /*CHECKSCALAR(shape(pp1_1,1)==n1_pp1_1)*/
  } /*if (f2py_success) of n1_pp1_1*/
  /* End of cleaning variable n1_pp1_1 */
  } /*CHECKSCALAR(shape(pp0_1,1)==n1_pp0_1)*/
  } /*if (f2py_success) of n1_pp0_1*/
  /* End of cleaning variable n1_pp0_1 */
  } /*CHECKSCALAR(shape(pp0_2,1)==n1_pp0_2)*/
  } /*if (f2py_success) of n1_pp0_2*/
  /* End of cleaning variable n1_pp0_2 */
  } /*CHECKSCALAR(shape(u1,1)==n1_u1)*/
  } /*if (f2py_success) of n1_u1*/
  /* End of cleaning variable n1_u1 */
  } /*CHECKSCALAR(shape(pp1_2,1)==n1_pp1_2)*/
  } /*if (f2py_success) of n1_pp1_2*/
  /* End of cleaning variable n1_pp1_2 */
  } /*CHECKSCALAR(shape(u1,0)==n0_u1)*/
  } /*if (f2py_success) of n0_u1*/
  /* End of cleaning variable n0_u1 */
  } /*CHECKSCALAR(shape(pp0_3,0)==n0_pp0_3)*/
  } /*if (f2py_success) of n0_pp0_3*/
  /* End of cleaning variable n0_pp0_3 */
  } /*CHECKSCALAR(shape(spans0,1)==n1_spans0)*/
  } /*if (f2py_success) of n1_spans0*/
  /* End of cleaning variable n1_spans0 */
  } /*CHECKSCALAR(shape(pp1_3,1)==n1_pp1_3)*/
  } /*if (f2py_success) of n1_pp1_3*/
  /* End of cleaning variable n1_pp1_3 */
  } /*CHECKSCALAR(shape(u3,2)==n2_u3)*/
  } /*if (f2py_success) of n2_u3*/
  /* End of cleaning variable n2_u3 */
  } /*CHECKSCALAR(len(nbase)>=n0_nbase)*/
  } /*if (f2py_success) of n0_nbase*/
  /* End of cleaning variable n0_nbase */
  } /*CHECKSCALAR(shape(particles_pos,1)==n1_particles_pos)*/
  } /*if (f2py_success) of n1_particles_pos*/
  /* End of cleaning variable n1_particles_pos */
  } /*CHECKSCALAR(shape(pp0_3,1)==n1_pp0_3)*/
  } /*if (f2py_success) of n1_pp0_3*/
  /* End of cleaning variable n1_pp0_3 */
  } /*CHECKSCALAR(shape(u1,2)==n2_u1)*/
  } /*if (f2py_success) of n2_u1*/
  /* End of cleaning variable n2_u1 */
  } /*CHECKSCALAR(shape(u_part,1)==n1_u_part)*/
  } /*if (f2py_success) of n1_u_part*/
  /* End of cleaning variable n1_u_part */
  } /*CHECKSCALAR(len(ueq)>=n0_ueq)*/
  } /*if (f2py_success) of n0_ueq*/
  /* End of cleaning variable n0_ueq */
  if((PyObject *)capi_u3_tmp!=u3_capi) {
    Py_XDECREF(capi_u3_tmp); }
  }  /*if (capi_u3_tmp == NULL) ... else of u3*/
  /* End of cleaning variable u3 */
  if((PyObject *)capi_u1_tmp!=u1_capi) {
    Py_XDECREF(capi_u1_tmp); }
  }  /*if (capi_u1_tmp == NULL) ... else of u1*/
  /* End of cleaning variable u1 */
  if((PyObject *)capi_pp0_3_tmp!=pp0_3_capi) {
    Py_XDECREF(capi_pp0_3_tmp); }
  }  /*if (capi_pp0_3_tmp == NULL) ... else of pp0_3*/
  /* End of cleaning variable pp0_3 */
  if((PyObject *)capi_spans0_tmp!=spans0_capi) {
    Py_XDECREF(capi_spans0_tmp); }
  }  /*if (capi_spans0_tmp == NULL) ... else of spans0*/
  /* End of cleaning variable spans0 */
  if((PyObject *)capi_particles_pos_tmp!=particles_pos_capi) {
    Py_XDECREF(capi_particles_pos_tmp); }
  }  /*if (capi_particles_pos_tmp == NULL) ... else of particles_pos*/
  /* End of cleaning variable particles_pos */
  if((PyObject *)capi_u_part_tmp!=u_part_capi) {
    Py_XDECREF(capi_u_part_tmp); }
  }  /*if (capi_u_part_tmp == NULL) ... else of u_part*/
  /* End of cleaning variable u_part */
  if((PyObject *)capi_nbase_tmp!=nbase_capi) {
    Py_XDECREF(capi_nbase_tmp); }
  }  /*if (capi_nbase_tmp == NULL) ... else of nbase*/
  /* End of cleaning variable nbase */
  if((PyObject *)capi_p0_tmp!=p0_capi) {
    Py_XDECREF(capi_p0_tmp); }
  }  /*if (capi_p0_tmp == NULL) ... else of p0*/
  /* End of cleaning variable p0 */
  if((PyObject *)capi_pp1_3_tmp!=pp1_3_capi) {
    Py_XDECREF(capi_pp1_3_tmp); }
  }  /*if (capi_pp1_3_tmp == NULL) ... else of pp1_3*/
  /* End of cleaning variable pp1_3 */
  if((PyObject *)capi_pp1_2_tmp!=pp1_2_capi) {
    Py_XDECREF(capi_pp1_2_tmp); }
  }  /*if (capi_pp1_2_tmp == NULL) ... else of pp1_2*/
  /* End of cleaning variable pp1_2 */
  if((PyObject *)capi_pp1_1_tmp!=pp1_1_capi) {
    Py_XDECREF(capi_pp1_1_tmp); }
  }  /*if (capi_pp1_1_tmp == NULL) ... else of pp1_1*/
  /* End of cleaning variable pp1_1 */
  if((PyObject *)capi_u2_tmp!=u2_capi) {
    Py_XDECREF(capi_u2_tmp); }
  }  /*if (capi_u2_tmp == NULL) ... else of u2*/
  /* End of cleaning variable u2 */
  if((PyObject *)capi_pp0_1_tmp!=pp0_1_capi) {
    Py_XDECREF(capi_pp0_1_tmp); }
  }  /*if (capi_pp0_1_tmp == NULL) ... else of pp0_1*/
  /* End of cleaning variable pp0_1 */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_pp0_2_tmp!=pp0_2_capi) {
    Py_XDECREF(capi_pp0_2_tmp); }
  }  /*if (capi_pp0_2_tmp == NULL) ... else of pp0_2*/
  /* End of cleaning variable pp0_2 */
  if((PyObject *)capi_ueq_tmp!=ueq_capi) {
    Py_XDECREF(capi_ueq_tmp); }
  }  /*if (capi_ueq_tmp == NULL) ... else of ueq*/
  /* End of cleaning variable ueq */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of evaluate_1form ***************************/

/******************************* evaluate_2form *******************************/
static char doc_f2py_rout_STRUPHY_fields_evaluate_2form[] = "\
evaluate_2form(particles_pos,p0,spans0,nbase,np,b1,b2,b3,beq,pp0_1,pp0_2,pp0_3,pp1_1,pp1_2,pp1_3,b_part,[n0_particles_pos,n1_particles_pos,n0_p0,n0_spans0,n1_spans0,n0_nbase,n0_b1,n1_b1,n2_b1,n0_b2,n1_b2,n2_b2,n0_b3,n1_b3,n2_b3,n0_beq,n0_pp0_1,n1_pp0_1,n0_pp0_2,n1_pp0_2,n0_pp0_3,n1_pp0_3,n0_pp1_1,n1_pp1_1,n0_pp1_2,n1_pp1_2,n0_pp1_3,n1_pp1_3,n0_b_part,n1_b_part])\n\nWrapper for ``evaluate_2form``.\
\n\nParameters\n----------\n"
"particles_pos : input rank-2 array('d') with bounds (n0_particles_pos,n1_particles_pos)\n"
"p0 : input rank-1 array('i') with bounds (n0_p0)\n"
"spans0 : input rank-2 array('i') with bounds (n0_spans0,n1_spans0)\n"
"nbase : input rank-1 array('i') with bounds (n0_nbase)\n"
"np : input int\n"
"b1 : input rank-3 array('d') with bounds (n0_b1,n1_b1,n2_b1)\n"
"b2 : input rank-3 array('d') with bounds (n0_b2,n1_b2,n2_b2)\n"
"b3 : input rank-3 array('d') with bounds (n0_b3,n1_b3,n2_b3)\n"
"beq : input rank-1 array('d') with bounds (n0_beq)\n"
"pp0_1 : input rank-2 array('d') with bounds (n0_pp0_1,n1_pp0_1)\n"
"pp0_2 : input rank-2 array('d') with bounds (n0_pp0_2,n1_pp0_2)\n"
"pp0_3 : input rank-2 array('d') with bounds (n0_pp0_3,n1_pp0_3)\n"
"pp1_1 : input rank-2 array('d') with bounds (n0_pp1_1,n1_pp1_1)\n"
"pp1_2 : input rank-2 array('d') with bounds (n0_pp1_2,n1_pp1_2)\n"
"pp1_3 : input rank-2 array('d') with bounds (n0_pp1_3,n1_pp1_3)\n"
"b_part : in/output rank-2 array('d') with bounds (n0_b_part,n1_b_part)\n"
"\nOther Parameters\n----------------\n"
"n0_particles_pos : input int, optional\n    Default: shape(particles_pos,0)\n"
"n1_particles_pos : input int, optional\n    Default: shape(particles_pos,1)\n"
"n0_p0 : input int, optional\n    Default: len(p0)\n"
"n0_spans0 : input int, optional\n    Default: shape(spans0,0)\n"
"n1_spans0 : input int, optional\n    Default: shape(spans0,1)\n"
"n0_nbase : input int, optional\n    Default: len(nbase)\n"
"n0_b1 : input int, optional\n    Default: shape(b1,0)\n"
"n1_b1 : input int, optional\n    Default: shape(b1,1)\n"
"n2_b1 : input int, optional\n    Default: shape(b1,2)\n"
"n0_b2 : input int, optional\n    Default: shape(b2,0)\n"
"n1_b2 : input int, optional\n    Default: shape(b2,1)\n"
"n2_b2 : input int, optional\n    Default: shape(b2,2)\n"
"n0_b3 : input int, optional\n    Default: shape(b3,0)\n"
"n1_b3 : input int, optional\n    Default: shape(b3,1)\n"
"n2_b3 : input int, optional\n    Default: shape(b3,2)\n"
"n0_beq : input int, optional\n    Default: len(beq)\n"
"n0_pp0_1 : input int, optional\n    Default: shape(pp0_1,0)\n"
"n1_pp0_1 : input int, optional\n    Default: shape(pp0_1,1)\n"
"n0_pp0_2 : input int, optional\n    Default: shape(pp0_2,0)\n"
"n1_pp0_2 : input int, optional\n    Default: shape(pp0_2,1)\n"
"n0_pp0_3 : input int, optional\n    Default: shape(pp0_3,0)\n"
"n1_pp0_3 : input int, optional\n    Default: shape(pp0_3,1)\n"
"n0_pp1_1 : input int, optional\n    Default: shape(pp1_1,0)\n"
"n1_pp1_1 : input int, optional\n    Default: shape(pp1_1,1)\n"
"n0_pp1_2 : input int, optional\n    Default: shape(pp1_2,0)\n"
"n1_pp1_2 : input int, optional\n    Default: shape(pp1_2,1)\n"
"n0_pp1_3 : input int, optional\n    Default: shape(pp1_3,0)\n"
"n1_pp1_3 : input int, optional\n    Default: shape(pp1_3,1)\n"
"n0_b_part : input int, optional\n    Default: shape(b_part,0)\n"
"n1_b_part : input int, optional\n    Default: shape(b_part,1)";
/* extern void F_FUNC_US(evaluate_2form,EVALUATE_2FORM)(int*,int*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,int*,int*,int*,double*,int*,int*,int*,double*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*); */
static PyObject *f2py_rout_STRUPHY_fields_evaluate_2form(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,int*,int*,int*,double*,int*,int*,int*,double*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_particles_pos = 0;
  PyObject *n0_particles_pos_capi = Py_None;
  int n1_particles_pos = 0;
  PyObject *n1_particles_pos_capi = Py_None;
  double *particles_pos = NULL;
  npy_intp particles_pos_Dims[2] = {-1, -1};
  const int particles_pos_Rank = 2;
  PyArrayObject *capi_particles_pos_tmp = NULL;
  int capi_particles_pos_intent = 0;
  PyObject *particles_pos_capi = Py_None;
  int n0_p0 = 0;
  PyObject *n0_p0_capi = Py_None;
  int *p0 = NULL;
  npy_intp p0_Dims[1] = {-1};
  const int p0_Rank = 1;
  PyArrayObject *capi_p0_tmp = NULL;
  int capi_p0_intent = 0;
  PyObject *p0_capi = Py_None;
  int n0_spans0 = 0;
  PyObject *n0_spans0_capi = Py_None;
  int n1_spans0 = 0;
  PyObject *n1_spans0_capi = Py_None;
  int *spans0 = NULL;
  npy_intp spans0_Dims[2] = {-1, -1};
  const int spans0_Rank = 2;
  PyArrayObject *capi_spans0_tmp = NULL;
  int capi_spans0_intent = 0;
  PyObject *spans0_capi = Py_None;
  int n0_nbase = 0;
  PyObject *n0_nbase_capi = Py_None;
  int *nbase = NULL;
  npy_intp nbase_Dims[1] = {-1};
  const int nbase_Rank = 1;
  PyArrayObject *capi_nbase_tmp = NULL;
  int capi_nbase_intent = 0;
  PyObject *nbase_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  int n0_b1 = 0;
  PyObject *n0_b1_capi = Py_None;
  int n1_b1 = 0;
  PyObject *n1_b1_capi = Py_None;
  int n2_b1 = 0;
  PyObject *n2_b1_capi = Py_None;
  double *b1 = NULL;
  npy_intp b1_Dims[3] = {-1, -1, -1};
  const int b1_Rank = 3;
  PyArrayObject *capi_b1_tmp = NULL;
  int capi_b1_intent = 0;
  PyObject *b1_capi = Py_None;
  int n0_b2 = 0;
  PyObject *n0_b2_capi = Py_None;
  int n1_b2 = 0;
  PyObject *n1_b2_capi = Py_None;
  int n2_b2 = 0;
  PyObject *n2_b2_capi = Py_None;
  double *b2 = NULL;
  npy_intp b2_Dims[3] = {-1, -1, -1};
  const int b2_Rank = 3;
  PyArrayObject *capi_b2_tmp = NULL;
  int capi_b2_intent = 0;
  PyObject *b2_capi = Py_None;
  int n0_b3 = 0;
  PyObject *n0_b3_capi = Py_None;
  int n1_b3 = 0;
  PyObject *n1_b3_capi = Py_None;
  int n2_b3 = 0;
  PyObject *n2_b3_capi = Py_None;
  double *b3 = NULL;
  npy_intp b3_Dims[3] = {-1, -1, -1};
  const int b3_Rank = 3;
  PyArrayObject *capi_b3_tmp = NULL;
  int capi_b3_intent = 0;
  PyObject *b3_capi = Py_None;
  int n0_beq = 0;
  PyObject *n0_beq_capi = Py_None;
  double *beq = NULL;
  npy_intp beq_Dims[1] = {-1};
  const int beq_Rank = 1;
  PyArrayObject *capi_beq_tmp = NULL;
  int capi_beq_intent = 0;
  PyObject *beq_capi = Py_None;
  int n0_pp0_1 = 0;
  PyObject *n0_pp0_1_capi = Py_None;
  int n1_pp0_1 = 0;
  PyObject *n1_pp0_1_capi = Py_None;
  double *pp0_1 = NULL;
  npy_intp pp0_1_Dims[2] = {-1, -1};
  const int pp0_1_Rank = 2;
  PyArrayObject *capi_pp0_1_tmp = NULL;
  int capi_pp0_1_intent = 0;
  PyObject *pp0_1_capi = Py_None;
  int n0_pp0_2 = 0;
  PyObject *n0_pp0_2_capi = Py_None;
  int n1_pp0_2 = 0;
  PyObject *n1_pp0_2_capi = Py_None;
  double *pp0_2 = NULL;
  npy_intp pp0_2_Dims[2] = {-1, -1};
  const int pp0_2_Rank = 2;
  PyArrayObject *capi_pp0_2_tmp = NULL;
  int capi_pp0_2_intent = 0;
  PyObject *pp0_2_capi = Py_None;
  int n0_pp0_3 = 0;
  PyObject *n0_pp0_3_capi = Py_None;
  int n1_pp0_3 = 0;
  PyObject *n1_pp0_3_capi = Py_None;
  double *pp0_3 = NULL;
  npy_intp pp0_3_Dims[2] = {-1, -1};
  const int pp0_3_Rank = 2;
  PyArrayObject *capi_pp0_3_tmp = NULL;
  int capi_pp0_3_intent = 0;
  PyObject *pp0_3_capi = Py_None;
  int n0_pp1_1 = 0;
  PyObject *n0_pp1_1_capi = Py_None;
  int n1_pp1_1 = 0;
  PyObject *n1_pp1_1_capi = Py_None;
  double *pp1_1 = NULL;
  npy_intp pp1_1_Dims[2] = {-1, -1};
  const int pp1_1_Rank = 2;
  PyArrayObject *capi_pp1_1_tmp = NULL;
  int capi_pp1_1_intent = 0;
  PyObject *pp1_1_capi = Py_None;
  int n0_pp1_2 = 0;
  PyObject *n0_pp1_2_capi = Py_None;
  int n1_pp1_2 = 0;
  PyObject *n1_pp1_2_capi = Py_None;
  double *pp1_2 = NULL;
  npy_intp pp1_2_Dims[2] = {-1, -1};
  const int pp1_2_Rank = 2;
  PyArrayObject *capi_pp1_2_tmp = NULL;
  int capi_pp1_2_intent = 0;
  PyObject *pp1_2_capi = Py_None;
  int n0_pp1_3 = 0;
  PyObject *n0_pp1_3_capi = Py_None;
  int n1_pp1_3 = 0;
  PyObject *n1_pp1_3_capi = Py_None;
  double *pp1_3 = NULL;
  npy_intp pp1_3_Dims[2] = {-1, -1};
  const int pp1_3_Rank = 2;
  PyArrayObject *capi_pp1_3_tmp = NULL;
  int capi_pp1_3_intent = 0;
  PyObject *pp1_3_capi = Py_None;
  int n0_b_part = 0;
  PyObject *n0_b_part_capi = Py_None;
  int n1_b_part = 0;
  PyObject *n1_b_part_capi = Py_None;
  double *b_part = NULL;
  npy_intp b_part_Dims[2] = {-1, -1};
  const int b_part_Rank = 2;
  PyArrayObject *capi_b_part_tmp = NULL;
  int capi_b_part_intent = 0;
  PyObject *b_part_capi = Py_None;
  static char *capi_kwlist[] = {"particles_pos","p0","spans0","nbase","np","b1","b2","b3","beq","pp0_1","pp0_2","pp0_3","pp1_1","pp1_2","pp1_3","b_part","n0_particles_pos","n1_particles_pos","n0_p0","n0_spans0","n1_spans0","n0_nbase","n0_b1","n1_b1","n2_b1","n0_b2","n1_b2","n2_b2","n0_b3","n1_b3","n2_b3","n0_beq","n0_pp0_1","n1_pp0_1","n0_pp0_2","n1_pp0_2","n0_pp0_3","n1_pp0_3","n0_pp1_1","n1_pp1_1","n0_pp1_2","n1_pp1_2","n0_pp1_3","n1_pp1_3","n0_b_part","n1_b_part",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOO|OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO:STRUPHY_fields.evaluate_2form",\
    capi_kwlist,&particles_pos_capi,&p0_capi,&spans0_capi,&nbase_capi,&np_capi,&b1_capi,&b2_capi,&b3_capi,&beq_capi,&pp0_1_capi,&pp0_2_capi,&pp0_3_capi,&pp1_1_capi,&pp1_2_capi,&pp1_3_capi,&b_part_capi,&n0_particles_pos_capi,&n1_particles_pos_capi,&n0_p0_capi,&n0_spans0_capi,&n1_spans0_capi,&n0_nbase_capi,&n0_b1_capi,&n1_b1_capi,&n2_b1_capi,&n0_b2_capi,&n1_b2_capi,&n2_b2_capi,&n0_b3_capi,&n1_b3_capi,&n2_b3_capi,&n0_beq_capi,&n0_pp0_1_capi,&n1_pp0_1_capi,&n0_pp0_2_capi,&n1_pp0_2_capi,&n0_pp0_3_capi,&n1_pp0_3_capi,&n0_pp1_1_capi,&n1_pp1_1_capi,&n0_pp1_2_capi,&n1_pp1_2_capi,&n0_pp1_3_capi,&n1_pp1_3_capi,&n0_b_part_capi,&n1_b_part_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable b1 */
  ;
  capi_b1_intent |= F2PY_INTENT_IN;
  capi_b1_tmp = array_from_pyobj(NPY_DOUBLE,b1_Dims,b1_Rank,capi_b1_intent,b1_capi);
  if (capi_b1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 6th argument `b1' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    b1 = (double *)(PyArray_DATA(capi_b1_tmp));

  /* Processing variable b3 */
  ;
  capi_b3_intent |= F2PY_INTENT_IN;
  capi_b3_tmp = array_from_pyobj(NPY_DOUBLE,b3_Dims,b3_Rank,capi_b3_intent,b3_capi);
  if (capi_b3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 8th argument `b3' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    b3 = (double *)(PyArray_DATA(capi_b3_tmp));

  /* Processing variable b_part */
  ;
  capi_b_part_intent |= F2PY_INTENT_INOUT;
  capi_b_part_tmp = array_from_pyobj(NPY_DOUBLE,b_part_Dims,b_part_Rank,capi_b_part_intent,b_part_capi);
  if (capi_b_part_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 16th argument `b_part' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    b_part = (double *)(PyArray_DATA(capi_b_part_tmp));

  /* Processing variable pp0_2 */
  ;
  capi_pp0_2_intent |= F2PY_INTENT_IN;
  capi_pp0_2_tmp = array_from_pyobj(NPY_DOUBLE,pp0_2_Dims,pp0_2_Rank,capi_pp0_2_intent,pp0_2_capi);
  if (capi_pp0_2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 11st argument `pp0_2' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    pp0_2 = (double *)(PyArray_DATA(capi_pp0_2_tmp));

  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"STRUPHY_fields.evaluate_2form() 5th argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable pp0_1 */
  ;
  capi_pp0_1_intent |= F2PY_INTENT_IN;
  capi_pp0_1_tmp = array_from_pyobj(NPY_DOUBLE,pp0_1_Dims,pp0_1_Rank,capi_pp0_1_intent,pp0_1_capi);
  if (capi_pp0_1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 10th argument `pp0_1' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    pp0_1 = (double *)(PyArray_DATA(capi_pp0_1_tmp));

  /* Processing variable pp1_1 */
  ;
  capi_pp1_1_intent |= F2PY_INTENT_IN;
  capi_pp1_1_tmp = array_from_pyobj(NPY_DOUBLE,pp1_1_Dims,pp1_1_Rank,capi_pp1_1_intent,pp1_1_capi);
  if (capi_pp1_1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 13rd argument `pp1_1' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    pp1_1 = (double *)(PyArray_DATA(capi_pp1_1_tmp));

  /* Processing variable pp1_2 */
  ;
  capi_pp1_2_intent |= F2PY_INTENT_IN;
  capi_pp1_2_tmp = array_from_pyobj(NPY_DOUBLE,pp1_2_Dims,pp1_2_Rank,capi_pp1_2_intent,pp1_2_capi);
  if (capi_pp1_2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 14th argument `pp1_2' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    pp1_2 = (double *)(PyArray_DATA(capi_pp1_2_tmp));

  /* Processing variable pp1_3 */
  ;
  capi_pp1_3_intent |= F2PY_INTENT_IN;
  capi_pp1_3_tmp = array_from_pyobj(NPY_DOUBLE,pp1_3_Dims,pp1_3_Rank,capi_pp1_3_intent,pp1_3_capi);
  if (capi_pp1_3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 15th argument `pp1_3' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    pp1_3 = (double *)(PyArray_DATA(capi_pp1_3_tmp));

  /* Processing variable b2 */
  ;
  capi_b2_intent |= F2PY_INTENT_IN;
  capi_b2_tmp = array_from_pyobj(NPY_DOUBLE,b2_Dims,b2_Rank,capi_b2_intent,b2_capi);
  if (capi_b2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 7th argument `b2' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    b2 = (double *)(PyArray_DATA(capi_b2_tmp));

  /* Processing variable p0 */
  ;
  capi_p0_intent |= F2PY_INTENT_IN;
  capi_p0_tmp = array_from_pyobj(NPY_INT,p0_Dims,p0_Rank,capi_p0_intent,p0_capi);
  if (capi_p0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 2nd argument `p0' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    p0 = (int *)(PyArray_DATA(capi_p0_tmp));

  /* Processing variable nbase */
  ;
  capi_nbase_intent |= F2PY_INTENT_IN;
  capi_nbase_tmp = array_from_pyobj(NPY_INT,nbase_Dims,nbase_Rank,capi_nbase_intent,nbase_capi);
  if (capi_nbase_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 4th argument `nbase' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    nbase = (int *)(PyArray_DATA(capi_nbase_tmp));

  /* Processing variable beq */
  ;
  capi_beq_intent |= F2PY_INTENT_IN;
  capi_beq_tmp = array_from_pyobj(NPY_DOUBLE,beq_Dims,beq_Rank,capi_beq_intent,beq_capi);
  if (capi_beq_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 9th argument `beq' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    beq = (double *)(PyArray_DATA(capi_beq_tmp));

  /* Processing variable particles_pos */
  ;
  capi_particles_pos_intent |= F2PY_INTENT_IN;
  capi_particles_pos_tmp = array_from_pyobj(NPY_DOUBLE,particles_pos_Dims,particles_pos_Rank,capi_particles_pos_intent,particles_pos_capi);
  if (capi_particles_pos_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 1st argument `particles_pos' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    particles_pos = (double *)(PyArray_DATA(capi_particles_pos_tmp));

  /* Processing variable spans0 */
  ;
  capi_spans0_intent |= F2PY_INTENT_IN;
  capi_spans0_tmp = array_from_pyobj(NPY_INT,spans0_Dims,spans0_Rank,capi_spans0_intent,spans0_capi);
  if (capi_spans0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 3rd argument `spans0' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    spans0 = (int *)(PyArray_DATA(capi_spans0_tmp));

  /* Processing variable pp0_3 */
  ;
  capi_pp0_3_intent |= F2PY_INTENT_IN;
  capi_pp0_3_tmp = array_from_pyobj(NPY_DOUBLE,pp0_3_Dims,pp0_3_Rank,capi_pp0_3_intent,pp0_3_capi);
  if (capi_pp0_3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(STRUPHY_fields_error,"failed in converting 12nd argument `pp0_3' of STRUPHY_fields.evaluate_2form to C/Fortran array" );
  } else {
    pp0_3 = (double *)(PyArray_DATA(capi_pp0_3_tmp));

  /* Processing variable n1_b_part */
  if (n1_b_part_capi == Py_None) n1_b_part = shape(b_part,1); else
    f2py_success = int_from_pyobj(&n1_b_part,n1_b_part_capi,"STRUPHY_fields.evaluate_2form() 30th keyword (n1_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,1)==n1_b_part,"shape(b_part,1)==n1_b_part","30th keyword n1_b_part","evaluate_2form:n1_b_part=%d",n1_b_part) {
  /* Processing variable n1_pp0_3 */
  if (n1_pp0_3_capi == Py_None) n1_pp0_3 = shape(pp0_3,1); else
    f2py_success = int_from_pyobj(&n1_pp0_3,n1_pp0_3_capi,"STRUPHY_fields.evaluate_2form() 22nd keyword (n1_pp0_3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_3,1)==n1_pp0_3,"shape(pp0_3,1)==n1_pp0_3","22nd keyword n1_pp0_3","evaluate_2form:n1_pp0_3=%d",n1_pp0_3) {
  /* Processing variable n1_particles_pos */
  if (n1_particles_pos_capi == Py_None) n1_particles_pos = shape(particles_pos,1); else
    f2py_success = int_from_pyobj(&n1_particles_pos,n1_particles_pos_capi,"STRUPHY_fields.evaluate_2form() 2nd keyword (n1_particles_pos) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles_pos,1)==n1_particles_pos,"shape(particles_pos,1)==n1_particles_pos","2nd keyword n1_particles_pos","evaluate_2form:n1_particles_pos=%d",n1_particles_pos) {
  /* Processing variable n1_b2 */
  if (n1_b2_capi == Py_None) n1_b2 = shape(b2,1); else
    f2py_success = int_from_pyobj(&n1_b2,n1_b2_capi,"STRUPHY_fields.evaluate_2form() 11st keyword (n1_b2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b2,1)==n1_b2,"shape(b2,1)==n1_b2","11st keyword n1_b2","evaluate_2form:n1_b2=%d",n1_b2) {
  /* Processing variable n1_pp1_3 */
  if (n1_pp1_3_capi == Py_None) n1_pp1_3 = shape(pp1_3,1); else
    f2py_success = int_from_pyobj(&n1_pp1_3,n1_pp1_3_capi,"STRUPHY_fields.evaluate_2form() 28th keyword (n1_pp1_3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_3,1)==n1_pp1_3,"shape(pp1_3,1)==n1_pp1_3","28th keyword n1_pp1_3","evaluate_2form:n1_pp1_3=%d",n1_pp1_3) {
  /* Processing variable n2_b3 */
  if (n2_b3_capi == Py_None) n2_b3 = shape(b3,2); else
    f2py_success = int_from_pyobj(&n2_b3,n2_b3_capi,"STRUPHY_fields.evaluate_2form() 15th keyword (n2_b3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b3,2)==n2_b3,"shape(b3,2)==n2_b3","15th keyword n2_b3","evaluate_2form:n2_b3=%d",n2_b3) {
  /* Processing variable n1_spans0 */
  if (n1_spans0_capi == Py_None) n1_spans0 = shape(spans0,1); else
    f2py_success = int_from_pyobj(&n1_spans0,n1_spans0_capi,"STRUPHY_fields.evaluate_2form() 5th keyword (n1_spans0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(spans0,1)==n1_spans0,"shape(spans0,1)==n1_spans0","5th keyword n1_spans0","evaluate_2form:n1_spans0=%d",n1_spans0) {
  /* Processing variable n0_pp0_3 */
  if (n0_pp0_3_capi == Py_None) n0_pp0_3 = shape(pp0_3,0); else
    f2py_success = int_from_pyobj(&n0_pp0_3,n0_pp0_3_capi,"STRUPHY_fields.evaluate_2form() 21st keyword (n0_pp0_3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_3,0)==n0_pp0_3,"shape(pp0_3,0)==n0_pp0_3","21st keyword n0_pp0_3","evaluate_2form:n0_pp0_3=%d",n0_pp0_3) {
  /* Processing variable n1_pp1_2 */
  if (n1_pp1_2_capi == Py_None) n1_pp1_2 = shape(pp1_2,1); else
    f2py_success = int_from_pyobj(&n1_pp1_2,n1_pp1_2_capi,"STRUPHY_fields.evaluate_2form() 26th keyword (n1_pp1_2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_2,1)==n1_pp1_2,"shape(pp1_2,1)==n1_pp1_2","26th keyword n1_pp1_2","evaluate_2form:n1_pp1_2=%d",n1_pp1_2) {
  /* Processing variable n1_b1 */
  if (n1_b1_capi == Py_None) n1_b1 = shape(b1,1); else
    f2py_success = int_from_pyobj(&n1_b1,n1_b1_capi,"STRUPHY_fields.evaluate_2form() 8th keyword (n1_b1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b1,1)==n1_b1,"shape(b1,1)==n1_b1","8th keyword n1_b1","evaluate_2form:n1_b1=%d",n1_b1) {
  /* Processing variable n0_beq */
  if (n0_beq_capi == Py_None) n0_beq = len(beq); else
    f2py_success = int_from_pyobj(&n0_beq,n0_beq_capi,"STRUPHY_fields.evaluate_2form() 16th keyword (n0_beq) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(beq)>=n0_beq,"len(beq)>=n0_beq","16th keyword n0_beq","evaluate_2form:n0_beq=%d",n0_beq) {
  /* Processing variable n1_b3 */
  if (n1_b3_capi == Py_None) n1_b3 = shape(b3,1); else
    f2py_success = int_from_pyobj(&n1_b3,n1_b3_capi,"STRUPHY_fields.evaluate_2form() 14th keyword (n1_b3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b3,1)==n1_b3,"shape(b3,1)==n1_b3","14th keyword n1_b3","evaluate_2form:n1_b3=%d",n1_b3) {
  /* Processing variable n1_pp0_1 */
  if (n1_pp0_1_capi == Py_None) n1_pp0_1 = shape(pp0_1,1); else
    f2py_success = int_from_pyobj(&n1_pp0_1,n1_pp0_1_capi,"STRUPHY_fields.evaluate_2form() 18th keyword (n1_pp0_1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_1,1)==n1_pp0_1,"shape(pp0_1,1)==n1_pp0_1","18th keyword n1_pp0_1","evaluate_2form:n1_pp0_1=%d",n1_pp0_1) {
  /* Processing variable n1_pp1_1 */
  if (n1_pp1_1_capi == Py_None) n1_pp1_1 = shape(pp1_1,1); else
    f2py_success = int_from_pyobj(&n1_pp1_1,n1_pp1_1_capi,"STRUPHY_fields.evaluate_2form() 24th keyword (n1_pp1_1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_1,1)==n1_pp1_1,"shape(pp1_1,1)==n1_pp1_1","24th keyword n1_pp1_1","evaluate_2form:n1_pp1_1=%d",n1_pp1_1) {
  /* Processing variable n0_b1 */
  if (n0_b1_capi == Py_None) n0_b1 = shape(b1,0); else
    f2py_success = int_from_pyobj(&n0_b1,n0_b1_capi,"STRUPHY_fields.evaluate_2form() 7th keyword (n0_b1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b1,0)==n0_b1,"shape(b1,0)==n0_b1","7th keyword n0_b1","evaluate_2form:n0_b1=%d",n0_b1) {
  /* Processing variable n0_b2 */
  if (n0_b2_capi == Py_None) n0_b2 = shape(b2,0); else
    f2py_success = int_from_pyobj(&n0_b2,n0_b2_capi,"STRUPHY_fields.evaluate_2form() 10th keyword (n0_b2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b2,0)==n0_b2,"shape(b2,0)==n0_b2","10th keyword n0_b2","evaluate_2form:n0_b2=%d",n0_b2) {
  /* Processing variable n1_pp0_2 */
  if (n1_pp0_2_capi == Py_None) n1_pp0_2 = shape(pp0_2,1); else
    f2py_success = int_from_pyobj(&n1_pp0_2,n1_pp0_2_capi,"STRUPHY_fields.evaluate_2form() 20th keyword (n1_pp0_2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_2,1)==n1_pp0_2,"shape(pp0_2,1)==n1_pp0_2","20th keyword n1_pp0_2","evaluate_2form:n1_pp0_2=%d",n1_pp0_2) {
  /* Processing variable n0_nbase */
  if (n0_nbase_capi == Py_None) n0_nbase = len(nbase); else
    f2py_success = int_from_pyobj(&n0_nbase,n0_nbase_capi,"STRUPHY_fields.evaluate_2form() 6th keyword (n0_nbase) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(nbase)>=n0_nbase,"len(nbase)>=n0_nbase","6th keyword n0_nbase","evaluate_2form:n0_nbase=%d",n0_nbase) {
  /* Processing variable n0_spans0 */
  if (n0_spans0_capi == Py_None) n0_spans0 = shape(spans0,0); else
    f2py_success = int_from_pyobj(&n0_spans0,n0_spans0_capi,"STRUPHY_fields.evaluate_2form() 4th keyword (n0_spans0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(spans0,0)==n0_spans0,"shape(spans0,0)==n0_spans0","4th keyword n0_spans0","evaluate_2form:n0_spans0=%d",n0_spans0) {
  /* Processing variable n0_pp1_3 */
  if (n0_pp1_3_capi == Py_None) n0_pp1_3 = shape(pp1_3,0); else
    f2py_success = int_from_pyobj(&n0_pp1_3,n0_pp1_3_capi,"STRUPHY_fields.evaluate_2form() 27th keyword (n0_pp1_3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_3,0)==n0_pp1_3,"shape(pp1_3,0)==n0_pp1_3","27th keyword n0_pp1_3","evaluate_2form:n0_pp1_3=%d",n0_pp1_3) {
  /* Processing variable n0_p0 */
  if (n0_p0_capi == Py_None) n0_p0 = len(p0); else
    f2py_success = int_from_pyobj(&n0_p0,n0_p0_capi,"STRUPHY_fields.evaluate_2form() 3rd keyword (n0_p0) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(p0)>=n0_p0,"len(p0)>=n0_p0","3rd keyword n0_p0","evaluate_2form:n0_p0=%d",n0_p0) {
  /* Processing variable n0_pp1_1 */
  if (n0_pp1_1_capi == Py_None) n0_pp1_1 = shape(pp1_1,0); else
    f2py_success = int_from_pyobj(&n0_pp1_1,n0_pp1_1_capi,"STRUPHY_fields.evaluate_2form() 23rd keyword (n0_pp1_1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_1,0)==n0_pp1_1,"shape(pp1_1,0)==n0_pp1_1","23rd keyword n0_pp1_1","evaluate_2form:n0_pp1_1=%d",n0_pp1_1) {
  /* Processing variable n0_pp1_2 */
  if (n0_pp1_2_capi == Py_None) n0_pp1_2 = shape(pp1_2,0); else
    f2py_success = int_from_pyobj(&n0_pp1_2,n0_pp1_2_capi,"STRUPHY_fields.evaluate_2form() 25th keyword (n0_pp1_2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp1_2,0)==n0_pp1_2,"shape(pp1_2,0)==n0_pp1_2","25th keyword n0_pp1_2","evaluate_2form:n0_pp1_2=%d",n0_pp1_2) {
  /* Processing variable n0_pp0_1 */
  if (n0_pp0_1_capi == Py_None) n0_pp0_1 = shape(pp0_1,0); else
    f2py_success = int_from_pyobj(&n0_pp0_1,n0_pp0_1_capi,"STRUPHY_fields.evaluate_2form() 17th keyword (n0_pp0_1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_1,0)==n0_pp0_1,"shape(pp0_1,0)==n0_pp0_1","17th keyword n0_pp0_1","evaluate_2form:n0_pp0_1=%d",n0_pp0_1) {
  /* Processing variable n0_b3 */
  if (n0_b3_capi == Py_None) n0_b3 = shape(b3,0); else
    f2py_success = int_from_pyobj(&n0_b3,n0_b3_capi,"STRUPHY_fields.evaluate_2form() 13rd keyword (n0_b3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b3,0)==n0_b3,"shape(b3,0)==n0_b3","13rd keyword n0_b3","evaluate_2form:n0_b3=%d",n0_b3) {
  /* Processing variable n0_particles_pos */
  if (n0_particles_pos_capi == Py_None) n0_particles_pos = shape(particles_pos,0); else
    f2py_success = int_from_pyobj(&n0_particles_pos,n0_particles_pos_capi,"STRUPHY_fields.evaluate_2form() 1st keyword (n0_particles_pos) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(particles_pos,0)==n0_particles_pos,"shape(particles_pos,0)==n0_particles_pos","1st keyword n0_particles_pos","evaluate_2form:n0_particles_pos=%d",n0_particles_pos) {
  /* Processing variable n2_b1 */
  if (n2_b1_capi == Py_None) n2_b1 = shape(b1,2); else
    f2py_success = int_from_pyobj(&n2_b1,n2_b1_capi,"STRUPHY_fields.evaluate_2form() 9th keyword (n2_b1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b1,2)==n2_b1,"shape(b1,2)==n2_b1","9th keyword n2_b1","evaluate_2form:n2_b1=%d",n2_b1) {
  /* Processing variable n0_pp0_2 */
  if (n0_pp0_2_capi == Py_None) n0_pp0_2 = shape(pp0_2,0); else
    f2py_success = int_from_pyobj(&n0_pp0_2,n0_pp0_2_capi,"STRUPHY_fields.evaluate_2form() 19th keyword (n0_pp0_2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(pp0_2,0)==n0_pp0_2,"shape(pp0_2,0)==n0_pp0_2","19th keyword n0_pp0_2","evaluate_2form:n0_pp0_2=%d",n0_pp0_2) {
  /* Processing variable n2_b2 */
  if (n2_b2_capi == Py_None) n2_b2 = shape(b2,2); else
    f2py_success = int_from_pyobj(&n2_b2,n2_b2_capi,"STRUPHY_fields.evaluate_2form() 12nd keyword (n2_b2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b2,2)==n2_b2,"shape(b2,2)==n2_b2","12nd keyword n2_b2","evaluate_2form:n2_b2=%d",n2_b2) {
  /* Processing variable n0_b_part */
  if (n0_b_part_capi == Py_None) n0_b_part = shape(b_part,0); else
    f2py_success = int_from_pyobj(&n0_b_part,n0_b_part_capi,"STRUPHY_fields.evaluate_2form() 29th keyword (n0_b_part) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b_part,0)==n0_b_part,"shape(b_part,0)==n0_b_part","29th keyword n0_b_part","evaluate_2form:n0_b_part=%d",n0_b_part) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_particles_pos,&n1_particles_pos,particles_pos,&n0_p0,p0,&n0_spans0,&n1_spans0,spans0,&n0_nbase,nbase,&np,&n0_b1,&n1_b1,&n2_b1,b1,&n0_b2,&n1_b2,&n2_b2,b2,&n0_b3,&n1_b3,&n2_b3,b3,&n0_beq,beq,&n0_pp0_1,&n1_pp0_1,pp0_1,&n0_pp0_2,&n1_pp0_2,pp0_2,&n0_pp0_3,&n1_pp0_3,pp0_3,&n0_pp1_1,&n1_pp1_1,pp1_1,&n0_pp1_2,&n1_pp1_2,pp1_2,&n0_pp1_3,&n1_pp1_3,pp1_3,&n0_b_part,&n1_b_part,b_part);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(b_part,0)==n0_b_part)*/
  } /*if (f2py_success) of n0_b_part*/
  /* End of cleaning variable n0_b_part */
  } /*CHECKSCALAR(shape(b2,2)==n2_b2)*/
  } /*if (f2py_success) of n2_b2*/
  /* End of cleaning variable n2_b2 */
  } /*CHECKSCALAR(shape(pp0_2,0)==n0_pp0_2)*/
  } /*if (f2py_success) of n0_pp0_2*/
  /* End of cleaning variable n0_pp0_2 */
  } /*CHECKSCALAR(shape(b1,2)==n2_b1)*/
  } /*if (f2py_success) of n2_b1*/
  /* End of cleaning variable n2_b1 */
  } /*CHECKSCALAR(shape(particles_pos,0)==n0_particles_pos)*/
  } /*if (f2py_success) of n0_particles_pos*/
  /* End of cleaning variable n0_particles_pos */
  } /*CHECKSCALAR(shape(b3,0)==n0_b3)*/
  } /*if (f2py_success) of n0_b3*/
  /* End of cleaning variable n0_b3 */
  } /*CHECKSCALAR(shape(pp0_1,0)==n0_pp0_1)*/
  } /*if (f2py_success) of n0_pp0_1*/
  /* End of cleaning variable n0_pp0_1 */
  } /*CHECKSCALAR(shape(pp1_2,0)==n0_pp1_2)*/
  } /*if (f2py_success) of n0_pp1_2*/
  /* End of cleaning variable n0_pp1_2 */
  } /*CHECKSCALAR(shape(pp1_1,0)==n0_pp1_1)*/
  } /*if (f2py_success) of n0_pp1_1*/
  /* End of cleaning variable n0_pp1_1 */
  } /*CHECKSCALAR(len(p0)>=n0_p0)*/
  } /*if (f2py_success) of n0_p0*/
  /* End of cleaning variable n0_p0 */
  } /*CHECKSCALAR(shape(pp1_3,0)==n0_pp1_3)*/
  } /*if (f2py_success) of n0_pp1_3*/
  /* End of cleaning variable n0_pp1_3 */
  } /*CHECKSCALAR(shape(spans0,0)==n0_spans0)*/
  } /*if (f2py_success) of n0_spans0*/
  /* End of cleaning variable n0_spans0 */
  } /*CHECKSCALAR(len(nbase)>=n0_nbase)*/
  } /*if (f2py_success) of n0_nbase*/
  /* End of cleaning variable n0_nbase */
  } /*CHECKSCALAR(shape(pp0_2,1)==n1_pp0_2)*/
  } /*if (f2py_success) of n1_pp0_2*/
  /* End of cleaning variable n1_pp0_2 */
  } /*CHECKSCALAR(shape(b2,0)==n0_b2)*/
  } /*if (f2py_success) of n0_b2*/
  /* End of cleaning variable n0_b2 */
  } /*CHECKSCALAR(shape(b1,0)==n0_b1)*/
  } /*if (f2py_success) of n0_b1*/
  /* End of cleaning variable n0_b1 */
  } /*CHECKSCALAR(shape(pp1_1,1)==n1_pp1_1)*/
  } /*if (f2py_success) of n1_pp1_1*/
  /* End of cleaning variable n1_pp1_1 */
  } /*CHECKSCALAR(shape(pp0_1,1)==n1_pp0_1)*/
  } /*if (f2py_success) of n1_pp0_1*/
  /* End of cleaning variable n1_pp0_1 */
  } /*CHECKSCALAR(shape(b3,1)==n1_b3)*/
  } /*if (f2py_success) of n1_b3*/
  /* End of cleaning variable n1_b3 */
  } /*CHECKSCALAR(len(beq)>=n0_beq)*/
  } /*if (f2py_success) of n0_beq*/
  /* End of cleaning variable n0_beq */
  } /*CHECKSCALAR(shape(b1,1)==n1_b1)*/
  } /*if (f2py_success) of n1_b1*/
  /* End of cleaning variable n1_b1 */
  } /*CHECKSCALAR(shape(pp1_2,1)==n1_pp1_2)*/
  } /*if (f2py_success) of n1_pp1_2*/
  /* End of cleaning variable n1_pp1_2 */
  } /*CHECKSCALAR(shape(pp0_3,0)==n0_pp0_3)*/
  } /*if (f2py_success) of n0_pp0_3*/
  /* End of cleaning variable n0_pp0_3 */
  } /*CHECKSCALAR(shape(spans0,1)==n1_spans0)*/
  } /*if (f2py_success) of n1_spans0*/
  /* End of cleaning variable n1_spans0 */
  } /*CHECKSCALAR(shape(b3,2)==n2_b3)*/
  } /*if (f2py_success) of n2_b3*/
  /* End of cleaning variable n2_b3 */
  } /*CHECKSCALAR(shape(pp1_3,1)==n1_pp1_3)*/
  } /*if (f2py_success) of n1_pp1_3*/
  /* End of cleaning variable n1_pp1_3 */
  } /*CHECKSCALAR(shape(b2,1)==n1_b2)*/
  } /*if (f2py_success) of n1_b2*/
  /* End of cleaning variable n1_b2 */
  } /*CHECKSCALAR(shape(particles_pos,1)==n1_particles_pos)*/
  } /*if (f2py_success) of n1_particles_pos*/
  /* End of cleaning variable n1_particles_pos */
  } /*CHECKSCALAR(shape(pp0_3,1)==n1_pp0_3)*/
  } /*if (f2py_success) of n1_pp0_3*/
  /* End of cleaning variable n1_pp0_3 */
  } /*CHECKSCALAR(shape(b_part,1)==n1_b_part)*/
  } /*if (f2py_success) of n1_b_part*/
  /* End of cleaning variable n1_b_part */
  if((PyObject *)capi_pp0_3_tmp!=pp0_3_capi) {
    Py_XDECREF(capi_pp0_3_tmp); }
  }  /*if (capi_pp0_3_tmp == NULL) ... else of pp0_3*/
  /* End of cleaning variable pp0_3 */
  if((PyObject *)capi_spans0_tmp!=spans0_capi) {
    Py_XDECREF(capi_spans0_tmp); }
  }  /*if (capi_spans0_tmp == NULL) ... else of spans0*/
  /* End of cleaning variable spans0 */
  if((PyObject *)capi_particles_pos_tmp!=particles_pos_capi) {
    Py_XDECREF(capi_particles_pos_tmp); }
  }  /*if (capi_particles_pos_tmp == NULL) ... else of particles_pos*/
  /* End of cleaning variable particles_pos */
  if((PyObject *)capi_beq_tmp!=beq_capi) {
    Py_XDECREF(capi_beq_tmp); }
  }  /*if (capi_beq_tmp == NULL) ... else of beq*/
  /* End of cleaning variable beq */
  if((PyObject *)capi_nbase_tmp!=nbase_capi) {
    Py_XDECREF(capi_nbase_tmp); }
  }  /*if (capi_nbase_tmp == NULL) ... else of nbase*/
  /* End of cleaning variable nbase */
  if((PyObject *)capi_p0_tmp!=p0_capi) {
    Py_XDECREF(capi_p0_tmp); }
  }  /*if (capi_p0_tmp == NULL) ... else of p0*/
  /* End of cleaning variable p0 */
  if((PyObject *)capi_b2_tmp!=b2_capi) {
    Py_XDECREF(capi_b2_tmp); }
  }  /*if (capi_b2_tmp == NULL) ... else of b2*/
  /* End of cleaning variable b2 */
  if((PyObject *)capi_pp1_3_tmp!=pp1_3_capi) {
    Py_XDECREF(capi_pp1_3_tmp); }
  }  /*if (capi_pp1_3_tmp == NULL) ... else of pp1_3*/
  /* End of cleaning variable pp1_3 */
  if((PyObject *)capi_pp1_2_tmp!=pp1_2_capi) {
    Py_XDECREF(capi_pp1_2_tmp); }
  }  /*if (capi_pp1_2_tmp == NULL) ... else of pp1_2*/
  /* End of cleaning variable pp1_2 */
  if((PyObject *)capi_pp1_1_tmp!=pp1_1_capi) {
    Py_XDECREF(capi_pp1_1_tmp); }
  }  /*if (capi_pp1_1_tmp == NULL) ... else of pp1_1*/
  /* End of cleaning variable pp1_1 */
  if((PyObject *)capi_pp0_1_tmp!=pp0_1_capi) {
    Py_XDECREF(capi_pp0_1_tmp); }
  }  /*if (capi_pp0_1_tmp == NULL) ... else of pp0_1*/
  /* End of cleaning variable pp0_1 */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_pp0_2_tmp!=pp0_2_capi) {
    Py_XDECREF(capi_pp0_2_tmp); }
  }  /*if (capi_pp0_2_tmp == NULL) ... else of pp0_2*/
  /* End of cleaning variable pp0_2 */
  if((PyObject *)capi_b_part_tmp!=b_part_capi) {
    Py_XDECREF(capi_b_part_tmp); }
  }  /*if (capi_b_part_tmp == NULL) ... else of b_part*/
  /* End of cleaning variable b_part */
  if((PyObject *)capi_b3_tmp!=b3_capi) {
    Py_XDECREF(capi_b3_tmp); }
  }  /*if (capi_b3_tmp == NULL) ... else of b3*/
  /* End of cleaning variable b3 */
  if((PyObject *)capi_b1_tmp!=b1_capi) {
    Py_XDECREF(capi_b1_tmp); }
  }  /*if (capi_b1_tmp == NULL) ... else of b1*/
  /* End of cleaning variable b1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of evaluate_2form ***************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"evaluate_1form",-1,{{-1}},0,(char *)F_FUNC_US(evaluate_1form,EVALUATE_1FORM),(f2py_init_func)f2py_rout_STRUPHY_fields_evaluate_1form,doc_f2py_rout_STRUPHY_fields_evaluate_1form},
  {"evaluate_2form",-1,{{-1}},0,(char *)F_FUNC_US(evaluate_2form,EVALUATE_2FORM),(f2py_init_func)f2py_rout_STRUPHY_fields_evaluate_2form,doc_f2py_rout_STRUPHY_fields_evaluate_2form},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "STRUPHY_fields",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_STRUPHY_fields(void) {
#else
#define RETVAL
PyMODINIT_FUNC initSTRUPHY_fields(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = STRUPHY_fields_module = PyModule_Create(&moduledef);
#else
  m = STRUPHY_fields_module = Py_InitModule("STRUPHY_fields", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module STRUPHY_fields (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'STRUPHY_fields' is auto-generated with f2py (version:2).\nFunctions:\n"
"  evaluate_1form(particles_pos,p0,spans0,nbase,np,u1,u2,u3,ueq,pp0_1,pp0_2,pp0_3,pp1_1,pp1_2,pp1_3,u_part,n0_particles_pos=shape(particles_pos,0),n1_particles_pos=shape(particles_pos,1),n0_p0=len(p0),n0_spans0=shape(spans0,0),n1_spans0=shape(spans0,1),n0_nbase=len(nbase),n0_u1=shape(u1,0),n1_u1=shape(u1,1),n2_u1=shape(u1,2),n0_u2=shape(u2,0),n1_u2=shape(u2,1),n2_u2=shape(u2,2),n0_u3=shape(u3,0),n1_u3=shape(u3,1),n2_u3=shape(u3,2),n0_ueq=len(ueq),n0_pp0_1=shape(pp0_1,0),n1_pp0_1=shape(pp0_1,1),n0_pp0_2=shape(pp0_2,0),n1_pp0_2=shape(pp0_2,1),n0_pp0_3=shape(pp0_3,0),n1_pp0_3=shape(pp0_3,1),n0_pp1_1=shape(pp1_1,0),n1_pp1_1=shape(pp1_1,1),n0_pp1_2=shape(pp1_2,0),n1_pp1_2=shape(pp1_2,1),n0_pp1_3=shape(pp1_3,0),n1_pp1_3=shape(pp1_3,1),n0_u_part=shape(u_part,0),n1_u_part=shape(u_part,1))\n"
"  evaluate_2form(particles_pos,p0,spans0,nbase,np,b1,b2,b3,beq,pp0_1,pp0_2,pp0_3,pp1_1,pp1_2,pp1_3,b_part,n0_particles_pos=shape(particles_pos,0),n1_particles_pos=shape(particles_pos,1),n0_p0=len(p0),n0_spans0=shape(spans0,0),n1_spans0=shape(spans0,1),n0_nbase=len(nbase),n0_b1=shape(b1,0),n1_b1=shape(b1,1),n2_b1=shape(b1,2),n0_b2=shape(b2,0),n1_b2=shape(b2,1),n2_b2=shape(b2,2),n0_b3=shape(b3,0),n1_b3=shape(b3,1),n2_b3=shape(b3,2),n0_beq=len(beq),n0_pp0_1=shape(pp0_1,0),n1_pp0_1=shape(pp0_1,1),n0_pp0_2=shape(pp0_2,0),n1_pp0_2=shape(pp0_2,1),n0_pp0_3=shape(pp0_3,0),n1_pp0_3=shape(pp0_3,1),n0_pp1_1=shape(pp1_1,0),n1_pp1_1=shape(pp1_1,1),n0_pp1_2=shape(pp1_2,0),n1_pp1_2=shape(pp1_2,1),n0_pp1_3=shape(pp1_3,0),n1_pp1_3=shape(pp1_3,1),n0_b_part=shape(b_part,0),n1_b_part=shape(b_part,1))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  STRUPHY_fields_error = PyErr_NewException ("STRUPHY_fields.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"STRUPHY_fields");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
