name: "Install Struphy in Container"

runs:
  using: composite
  steps:
    - name: Git branch name
      id: git-branch-name
      uses: EthanSK/git-branch-name-action@v1
    - name: Echo the branch name
      run: echo "Branch name ${GIT_BRANCH_NAME}"
    - name: Install struphy
      shell: bash
      run: |
          ls / -a
          which python3
          cd /struphy_c_
          git status
          git fetch origin
          echo ${GIT_BRANCH_NAME}
          git checkout ${GIT_BRANCH_NAME}
          git pull
          source env_c_/bin/activate
          which python3
          struphy -p
          pip install -e ".[phys,mpi,doc]"