name: "Install struphy in env"

inputs:
  optional-deps:
    required: true
    default: 'dev'

runs:
  using: composite
  steps:

    - name: Install struphy
      shell: bash
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install ".[${{ inputs.optional-deps }}]"
        pip list
        struphy -h
        struphy --refresh-models
