name: "Clone and install struphy"

runs:
  using: composite
  steps:

    - name: Install struphy
      shell: bash
      run: |
        pip install --upgrade pip
        pip install ".[phys,mpi,doc]"
        pip list
        struphy -h
        struphy --refresh-models
