name: "Install struphy in Python environment"

description: 

inputs:
  env-name:
    required: true
    default: ""
  optional-deps:
    required: true
    default: 'dev'

runs:
  using: composite
  steps:
    - name: Install struphy
      shell: bash
      run: |
        source ${{ inputs.env-name }}/bin/activate || true
        which python
        pip install --upgrade pip
        pip install ".[${{ inputs.optional-deps }}]"
        pip list
        struphy -h
