name: "Clone and install struphy"

runs:
  using: composite
  steps:

    - name: Install struphy
      shell: bash
      run: |
        pip install --upgrade pip
        pip uninstall -y gvec
        pip install ".[phys,mpi]"
        pip list
        struphy -h
        struphy --refresh-models
