name: Load modules
description: Load modules in a login shell

inputs:
  modules:
    description: Space-separated list of modules to load
    required: true

runs:
  using: composite
  steps:
    - name: Load modules
      shell: bash -l
      run: |
        module purge
        module load ${{ inputs.modules }}
        module list
