// Generated by cunumpy.arguments.CudaStruct from the Python definition; do not edit.
#ifndef STRUPHY_LOCAL_PROJECTORS_ARGS_CUH
#define STRUPHY_LOCAL_PROJECTORS_ARGS_CUH

#include "cunumpy/array_view.cuh"

struct LocalProjectorsArgs {
    int space_key;
    bool* IoH;
    long long* shift;
    long long* original_size;
    long long* index_translation1;
    long long* index_translation2;
    long long* index_translation3;
    long long* starts;
    long long* ends;
    long long* pds;
    long long* B_nbasis;
    bool* periodic;
    long long* degree;
    Array2D<double> wij0;
    Array2D<double> wij1;
    Array2D<double> wij2;
    Array2D<double> wts0;
    Array2D<double> wts1;
    Array2D<double> wts2;
    long long* inv_index_translation0;
    long long* inv_index_translation1;
    long long* inv_index_translation2;
};

#endif  // STRUPHY_LOCAL_PROJECTORS_ARGS_CUH
