// Generated by cunumpy.cuda.CudaStruct from the Python definition; do not edit.
#ifndef STRUPHY_PUSHER_ARGS_CUH
#define STRUPHY_PUSHER_ARGS_CUH

struct MarkerArgs {
    double* markers;
    bool* valid_mks;
    int n_markers;
    int n_cols;
    int Np;
    int vdim;
    int weight_idx;
    int first_diagnostics_idx;
    int first_init_idx;
    int first_shift_idx;
    int residual_idx;
    int first_free_idx;
    int mu_idx;
    long long* bc_type;
};

struct DerhamArgs {
    long long* pn;
    double* tn1;
    double* tn2;
    double* tn3;
    long long* starts;
    int nt1;
    int nt2;
    int nt3;
};

struct DomainArgs {
    int kind_map;
    double* params;
    long long* degree;
    double* t1;
    double* t2;
    double* t3;
    long long* ind1;
    long long* ind2;
    long long* ind3;
    double* cx;
    double* cy;
    double* cz;
};

#endif  // STRUPHY_PUSHER_ARGS_CUH

#define MARKER(args, ip, j) ((args).markers[(long long)(ip) * (args).n_cols + (j)])
