// Generated by cunumpy.arguments.CudaStruct from the Python definition; do not edit.
#ifndef STRUPHY_PUSHER_ARGS_CUH
#define STRUPHY_PUSHER_ARGS_CUH

#include "cunumpy/array_view.cuh"

struct MarkerArgs {
    Array2D<double> markers;
    bool* valid_mks;
    int n_markers;
    int Np;
    int vdim;
    int weight_idx;
    int first_diagnostics_idx;
    int first_init_idx;
    int first_shift_idx;
    int residual_idx;
    int first_free_idx;
    int mu_idx;
    long long* bc_type;
};

struct DerhamArgs {
    long long* pn;
    double* tn1;
    double* tn2;
    double* tn3;
    long long* starts;
    int nt1;
    int nt2;
    int nt3;
};

struct DomainArgs {
    int kind_map;
    double* params;
    long long* degree;
    Array1D<double> t1;
    Array1D<double> t2;
    Array1D<double> t3;
    Array2D<long long> ind1;
    Array2D<long long> ind2;
    Array2D<long long> ind3;
    Array3D<double> cx;
    Array3D<double> cy;
    Array3D<double> cz;
};

#endif  // STRUPHY_PUSHER_ARGS_CUH
