// Generated by cunumpy.arguments.CudaStruct from the Python definition; do not edit.
#ifndef STRUPHY_SPLINE_ARGS_CUH
#define STRUPHY_SPLINE_ARGS_CUH

#include "cunumpy/array_view.cuh"

struct SplineArgs {
    long long* kind;
    long long* pn;
    Array1D<double> tn1;
    Array1D<double> tn2;
    Array1D<double> tn3;
    long long* starts;
};

#endif  // STRUPHY_SPLINE_ARGS_CUH
