name: "Clone and install struphy"

runs:
  using: composite
  steps:

    - name: Install struphy
      shell: bash
      run: |
        pip install --upgrade pip
        pip uninstall -y gvec
        pip install -e ".[dev,mpi,doc]"
        pip list
        struphy -h
