#!/bin/bash

PYTHON=python3

struphy -r maxwell -i 'parameters_example_1d_fft.yml' -o examples/maxwell_1d_fft

path_lib=$($PYTHON -c 'import sysconfig; print(sysconfig.get_path("platlib"))')/struphy/

path_examples=${path_lib}examples/
folder_out=${path_lib}io/out/examples/maxwell_1d_fft/

if [ -e ${folder_out}eval_data.hdf5 ]; then
    rm ${folder_out}eval_data.hdf5
    echo 'eval_data.hdf5 in' folder_out 'deleted.'
fi

$PYTHON ${path_examples}example_maxwell_1d_fft.py
