#!/bin/bash -e

PYTHON=python3

# run
struphy run Maxwell -i examples/params_maxwell.yml -o sim_1

# post process
struphy pproc sim_1

# Struphy path
STRUPHY=
li=$(pip show struphy)
#echo $li
take=false
for i in $li; do

    if [ "$take" = "true" ]; then
        #echo $take
        STRUPHY=$i/struphy
        break
    fi
    #echo "$i"
    if [ "$i" = "Location:" ]; then
        #echo "$i"
        take=true
    fi
done

path_e=$STRUPHY/examples
$PYTHON ${path_e}/example_diagnostics_1dfft_maxwell.py $STRUPHY/io/out/sim_1
