#!/bin/bash -e

# Python interpreter
PYTHON=python3

# Struphy path
STRUPHY=
li=$(pip show struphy)
#echo $li
take=false
for i in $li; do

    if [ "$take" = "true" ]; then
        #echo $take
        STRUPHY=$i/struphy
        break
    fi
    #echo "$i"
    if [ "$i" = "Location:" ]; then
        #echo "$i"
        take=true
    fi
done

# Defaults
RUN=false
COMPILE=false 
PROFILE=false
PPROC=false
PROFILE_ALL=false    
CFLAGS=--openmp    
CODE=                                 
INPUT=parameters.yml            
INPUT_ABS=        
OUTPUT=sim_1           
OUTPUT_ABS=   
BATCH=false            
BATCH_SCRIPT=     
BATCH_SCRIPT_ABS=         
RESTART_FOLDER=          
MPI_SIZE=
PPCELL=1
RUN_CMD=$PYTHON

function help {
    echo
    echo -e "\e[1mNAME\e[0m"
    echo "      struphy - Structure-preserving hybrid codes for plasma physics."
    echo
    echo -e "\e[1mSYNOPSIS\e[0m"
    echo -e "       \e[4mstruphy\e[0m [<options>]"
    echo -e "       \e[4mstruphy\e[0m \e[4mcompile\e[0m [<compile options>]"
    echo -e "       \e[4mstruphy\e[0m \e[4mrun\e[0m <model> [<run options>]"
    echo -e "       \e[4mstruphy\e[0m \e[4mprofile\e[0m [<profile options>] <sim1> [<sim2> ...] "
    echo -e "       \e[4mstruphy\e[0m \e[4mpproc\e[0m [<post processing options>] <sim1> [<sim2> ...] "
    echo 
    echo -e "\e[1mDESCRIPTION\e[0m"
    echo -e "      Compiles struphy kernels, runs a struphy model, profiles finished runs or post processs struphy data. 
      Can run locally with mpi (for testing) or submit a batch script to SLURM.
      For more info see https://clapp.pages.mpcdf.de/hylife/index.html ."
    echo
    echo -e "\e[1mSTRUPHY MODELS\e[0m"
    echo "      See https://clapp.pages.mpcdf.de/hylife/sections/models.html for available models. Valid inputs for <model>
      are the listed class names, as in struphy.models.models.<model>. For example, 'Maxwell'."
    echo
    echo -e "\e[1mOPTIONS\e[0m "
    echo "      -h, --help                 Display struphy help."
    echo "      -p, --path                 Display possible struphy installation paths: platform- and user-specific."
    echo
    echo -e "\e[1mCOMPILE OPTIONS\e[0m "
    echo "      --no-openmp                Compile without OpenMP."
    echo "      --delete                   Remove Fortran and .so files."
    echo
    echo -e "\e[1mRUN OPTIONS\e[0m "
    echo "      -i, --input <filename>     Parameter file (.yml), path is relative to <install_path>/struphy/io/inp/<model>/;"
    echo "                                 the default is 'parameters.yml'"
    echo "      --input-abs <filename>     Parameter file (.yml), absolute path."
    echo "      -o, --output <folder>      Output folder, path is relative to <install_path>/struphy/io/out/; the  default is 'sim_1'."  
    echo "      --output-abs <folder>      Output folder, absolute path."  
    echo "      -b, --batch  <filename>    Batch script, path is relative to <install_path>/struphy/io/batch/."
    echo "      --batch-abs  <filename>    Batch script, absolute path."
    echo "      -r, --restart <folder>     Run with restart, give absolute path to restart folder."
    echo "      --mpi <int>                Use mpirun -n <int>."
    echo
    echo -e "\e[1mPROFILE OPTIONS\e[0m "
    echo "      -a, --all                  Do not specify specific strings to profile, profile all called functions."
    echo "                                 If not given, struphy profiles only functions including 
                                 strings stated in file:///home/spossann/git_repos/struphy/doc/_build/html/sections/userguide.html#code-profiling"
    echo "      <sim1>, <sim2>             Folder names of finished simulations, relative to <install_path>/struphy/io/out/."
    echo
    echo -e "\e[1mPOST PROCESSING OPTIONS\e[0m "
    echo "      --ppcell <int>             Points per cell for field evaluation, default=1."
    echo ""
}

# No arguments - display help and exit
if [ $# -eq 0 ]; then
    help
    exit 0
fi

# Scan arguments
POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      help
      exit 0
      ;;
    -p|--path)
      echo "Struphy installation path:" $STRUPHY
      echo "default input:            " $STRUPHY/io/inp 
      echo "default output:           " $STRUPHY/io/out
      echo "template batch scripts:   " $STRUPHY/io/batch
      exit 0
      ;;
    run) 
      RUN=true
      CODE="$2"
      shift
      shift
      ;;
    compile)
      COMPILE=true
      shift
      ;;
    profile)
      PROFILE=true
      shift
      ;;
    pproc)
      PPROC=true
      shift
      ;;
    -a|--all)
      PROFILE_ALL=true
      shift
      ;;
    --no-openmp)
      CFLAGS=
      shift 
      ;;
    --delete)
      CLEAN=true
      shift 
      ;;
    -i|--input)
      INPUT="$2"
      shift
      shift
      ;;
    --input-abs)
      INPUT_ABS="$2"
      shift
      shift
      ;;
    -o|--output)
      OUTPUT="$2"
      shift
      shift
      ;;
    --output-abs)
      OUTPUT_ABS="$2"
      shift
      shift
      ;;
    -b|--batch)
      BATCH=true
      BATCH_SCRIPT="$2"
      shift
      shift
      ;;
    --batch-abs)
      BATCH=true
      BATCH_SCRIPT_ABS="$2"
      shift
      shift
      ;;
    -r|--restart)
      RESTART_FOLDER="$2"
      shift
      shift
      ;;
    --mpi)
      MPI_SIZE="$2"
      shift
      shift
      ;;
    --ppcell)
      PPCELL="$2"
      shift
      shift
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

# Struphy path
echo "STRUPHY = ${STRUPHY}"

# Code compilation
if [ "$COMPILE" = true ]; then

  # Print parameters
  echo "Makefile: $STRUPHY/compile_struphy.mk"
  echo "COMPILE = ${COMPILE}"
  echo "CFLAGS  = ${CFLAGS}"
  echo "CLEAN   = ${CLEAN}"

  if [ "$CLEAN" = true ]; then
    echo "Start cleaning up struphy..."
    cd .. # change dir not be in source path
    command make clean -f $STRUPHY/compile_struphy.mk flag_path=$STRUPHY 
    exit 0
  else
    echo "Start compiling struphy..."
    cd .. # change dir not be in source path
    command make -f $STRUPHY/compile_struphy.mk flag_path=$STRUPHY flags_openmp_pic=$CFLAGS
    exit 0
  fi

fi

# Run
if [ "$RUN" = true ] ; then

  # Restart
  if [ $RESTART_FOLDER ]; then
    echo "Restart not yet implemented."
    exit 0
  fi

  # In-/output paths
  if [ -z $INPUT_ABS ]; then
    INPUT_ABS=$STRUPHY/io/inp/$INPUT
  fi

  if [ -z $OUTPUT_ABS ]; then
    OUTPUT_ABS=$STRUPHY/io/out/$OUTPUT
  fi

  # delete output folder if it exists
  rm -rf $OUTPUT_ABS

  # Create ouput folder and copy parameters there
  mkdir $OUTPUT_ABS
  cp $INPUT_ABS $OUTPUT_ABS/parameters.yml 
  METAFILE=$OUTPUT_ABS/meta.txt 

  # Run flags
  CPROFILE="-m cProfile -o $OUTPUT_ABS/profile_tmp -s time $STRUPHY/main.py"
  ARGS="$CODE $INPUT_ABS $OUTPUT_ABS/ None $METAFILE $RESTART_FOLDER"

  # Normal run  
  RUN_CMD="$PYTHON $CPROFILE $ARGS"  

  # MPI mode
  if [ "$MPI_SIZE" ]; then
    RUN_CMD="mpirun -n $MPI_SIZE $PYTHON $CPROFILE $ARGS"
  fi

  # Batch mode
  if [ "$BATCH" = true ]; then

    if [ -z $BATCH_SCRIPT_ABS ]; then
      BATCH_SCRIPT_ABS=$STRUPHY/io/batch/$BATCH_SCRIPT
    fi

    chmod +x $BATCH_SCRIPT_ABS

    # Check if batch script already has an "srun" command; if yes, remove
    LASTLINE=$(tail -1 $BATCH_SCRIPT_ABS)

    if [[ $LASTLINE == *"srun"* ]]; then
      sed -i '$ d' $BATCH_SCRIPT_ABS
      sed -i '$ d' $BATCH_SCRIPT_ABS
    elif [ "$LASTLINE" ]; then
      echo -e "\n" >> $BATCH_SCRIPT_ABS 
    fi

    # Append run command to batch script
    echo "# Run command added by Struphy" >> $BATCH_SCRIPT_ABS
    echo "srun $PYTHON $CPROFILE $ARGS> $OUTPUT_ABS/struphy.out" >> $BATCH_SCRIPT_ABS

    RUN_CMD="sbatch $BATCH_SCRIPT_ABS"

  fi

  # Print parameters
  echo "RUN              = ${RUN}"
  echo "CODE             = ${CODE}"
  echo "RESTART_FOLDER   = ${RESTART_FOLDER}"
  echo "MPI_SIZE         = ${MPI_SIZE}"
  echo "INPUT_ABS        = ${INPUT_ABS}"
  echo "OUTPUT_ABS       = ${OUTPUT_ABS}"
  echo "BATCH_SCRIPT_ABS = ${BATCH_SCRIPT_ABS}"
  echo "RUN_CMD          = ${RUN_CMD}"
  echo "METAFILE         = ${METAFILE}"

  # Write to meta.txt
  echo "STRUPHY          = ${STRUPHY}" >> $METAFILE
  echo "CODE             = ${CODE}" >> $METAFILE
  echo "RESTART_FOLDER   = ${RESTART_FOLDER}" >> $METAFILE
  echo "MPI_SIZE         = ${MPI_SIZE}" >> $METAFILE
  echo "INPUT_ABS        = ${INPUT_ABS}" >> $METAFILE
  echo "OUTPUT_ABS       = ${OUTPUT_ABS}" >> $METAFILE
  echo "BATCH_SCRIPT_ABS = ${BATCH_SCRIPT_ABS}" >> $METAFILE
  echo "RUN_CMD          = ${RUN_CMD}" >> $METAFILE
  echo "METAFILE         = ${METAFILE}" >> $METAFILE

  # Start code
  $RUN_CMD

fi

# Profile runs
if [ "$PROFILE" = true ]; then

  if (( ${#POSITIONAL_ARGS[@]} == 0 )); then

    echo "  ERROR: no simulation folders to profile specified."
    exit 1

  else

    folders=()
    for i in ${POSITIONAL_ARGS[@]}; do
      folders+=($STRUPHY/io/out/$i/)
    done

    # Print parameters
    echo "Executing $STRUPHY/diagnostics/profile_struphy.py"
    echo "PROFILE_ALL = $PROFILE_ALL"
    echo "folders  = ${folders[*]}"

    $PYTHON $STRUPHY/diagnostics/profile_struphy.py $PROFILE_ALL ${folders[@]}

  fi

fi

# Post processing
if [ "$PPROC" = true ]; then

  if (( ${#POSITIONAL_ARGS[@]} == 0 )); then

    echo "  ERROR: no simulation folders to post process specified."
    exit 1

  else

    folders=()
    for i in ${POSITIONAL_ARGS[@]}; do
      folders+=($STRUPHY/io/out/$i/)
    done

    # Print parameters
    echo "Executing $STRUPHY/diagnostics/pproc_struphy.py"
    echo "PPCELL = $PPCELL"
    echo "folders  = ${folders[*]}"

    $PYTHON $STRUPHY/diagnostics/pproc_struphy.py $PPCELL ${folders[@]}

  fi

fi


