#!/bin/bash

# defaults:
code=lin_mhd 
file=parameters.yml 
out=sim_1 
batch=
mode=w # restart: 'a', new start: 'w' (default)
num_threads=1 # number of openmp threads (pyccel, not needed for numba)

PYTHON=python3

path_lib=$($PYTHON -c 'import sysconfig; print(sysconfig.get_path("platlib"))')/struphy/
folder_inp=${path_lib}io/inp/
folder_out=${path_lib}io/out/
folder_batch=${path_lib}io/batch/
path_code=${path_lib}models/codes/

while getopts ":hpstcr:i:o:b:m:n:" opt; do
    case "${opt}" in
        h)
            echo Script name: $0
            echo "Options:"
            echo "   -h                 Display help."
            echo "   -p                 Display paths to input/output/batch files."
            echo "   -s                 Display platform information."
            echo "   -t                 Display struphy tree (package directories)."
            echo "   -c                 Compile struphy kernels (pyccel)."
            echo "   -r <code>          Specify code to run. Available codes are:"
            echo "                                * lin_mhd (linear MHD) -> default"
            echo "                                * lin_mhd_MF (matrix-free linear MHD)"
            echo "                                * cc_lin_mhd_6d (current coupling MHD-full Vlasov)"
            echo "                                * cc_lin_mhd_6d_MF (matrix-free current coupling MHD-full Vlasov)"
            echo "                                * pc_lin_mhd_6d_MF_full (matrix-free pressure coupling MHD-full Vlasov with full pressure tensor)"
            echo "                                * pc_lin_mhd_6d_MF_perp (matrix-free pressure coupling MHD-full Vlasov with pressure tensor perpendicular to B)"
            echo "                                * massless_extended (full Vlasov, massless fluid electrons, extended Ohm's law)"
            echo "   -i <filename>      Parameter file (.yml), default is 'parameters.yml'."
            echo "   -o <filename>      Output folder, default is 'sim_1'."    
            echo "   -b <filename>      Batch script, default is 'None'."
            echo "   -m <a|w>           Restart (a) or clean start (w), default is w."
            echo "   -n <number>        Number of omp threads, default is 1."
            exit 0
            ;;
        p)
            echo "Parameter files (.yml) are in    " ${folder_inp}
            echo "Output files (.hdf5, .txt) are in" ${folder_out}
            echo "Your batch script are in         " ${folder_batch}
            exit 0
            ;;
        s)  
            echo $($PYTHON -c 'import sysconfig; print(sysconfig.get_platform())')
            echo $($PYTHON --version)
            exit 0
            ;;
        t)
            echo "The struphy package is in" $path_lib
            echo "Package content:"
            echo
            cd $path_lib
            tree -d -I '__pycache__|__pyccel__'
            exit 0
            ;;
        c)
            echo "Start compiling struphy..."
            cd ..
            make -f ${path_lib}compile_struphy.mk
            cd -
            exit 0
            ;;
        r)
            code=${OPTARG}
            ;;
        i)
            file=${OPTARG}
            ;;
        o)
            out=${OPTARG}
            ;;
        b)
            batch=${OPTARG}
            ;;
        m)
            mode=${OPTARG}
            ;;
        n)
            num_threads=${OPTARG}
            ;;
        \? ) 
            echo "Invalid Option: -$OPTARG" 1>&2
            exit 1
    esac
done
shift $((OPTIND-1))

file_inp=${folder_inp}$code/$file
path_out=${folder_out}$out/
mkdir -p ${path_out} # create output folder
file_meta=${path_out}sim_meta_data.txt

echo ""
echo "Starting struphy ..."
echo "code:" $code
echo "input parameters:" ${file_inp}
echo "output folder:" ${path_out}
echo "batch script:" $batch
echo "omp threads:" $num_threads
echo "restart:" $mode

cp ${file_inp} ${path_out}/parameters.yml

echo "Copied parameter file to output folder."

# remove existing files when no restart
if [ $mode = w ] && [ -e ${path_out}data.hdf5 ]; then

    # ask user to confirm: 
    #echo 'Are you sure you want to delete data.hdf5 in' /$out '([y]/n)?'
    #read check_user

    if [ -z $check_user ] || [$check_user = y]; then
        rm ${path_out}data.hdf5
        rm ${path_out}sim_meta_data.txt
        echo 'data.hdf5 in' /$out 'deleted.'
    fi

fi

# call exec.py
if [ -z $batch ]; then
    
    export OMP_NUM_THREADS=$num_threads
    $PYTHON -m cProfile -o ${path_out}profile_tmp -s time ${path_code}exec.py $code $file_inp $path_out None $file_meta $mode

else

    chmod +x ${folder_batch}$batch
    ${folder_batch}$batch

fi






