/* File: initial_conditions_MHDmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Apr  8 06:30:09 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *initial_conditions_MHD_error;
static PyObject *initial_conditions_MHD_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
#ifdef _WIN32
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(initial_conditions_MHD_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = initial_conditions_MHD_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int long_long_from_pyobj(long_long* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyLong_Check(obj)) {
        *v = PyLong_AsLongLong(obj);
        return (!PyErr_Occurred());
    }
    if (PyInt_Check(obj)) {
        *v = (long_long)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = PyLong_AsLongLong(tmp);
        Py_DECREF(tmp);
        return (!PyErr_Occurred());
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (long_long_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = initial_conditions_MHD_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = initial_conditions_MHD_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern double F_FUNC_US(p_ini_phys,P_INI_PHYS)(double*,double*,double*);
extern double F_FUNC_US(ux_ini,UX_INI)(double*,double*,double*);
extern double F_FUNC_US(uy_ini,UY_INI)(double*,double*,double*);
extern double F_FUNC_US(uz_ini,UZ_INI)(double*,double*,double*);
extern double F_FUNC_US(bx_ini,BX_INI)(double*,double*,double*);
extern double F_FUNC_US(by_ini,BY_INI)(double*,double*,double*);
extern double F_FUNC_US(bz_ini,BZ_INI)(double*,double*,double*);
extern double F_FUNC_US(rho_ini_phys,RHO_INI_PHYS)(double*,double*,double*);
extern double F_FUNC_US(p_ini,P_INI)(double*,double*,double*,long_long*,int*,double*);
extern double F_FUNC_US(u1_ini,U1_INI)(double*,double*,double*,long_long*,int*,double*);
extern double F_FUNC_US(u2_ini,U2_INI)(double*,double*,double*,long_long*,int*,double*);
extern double F_FUNC_US(u3_ini,U3_INI)(double*,double*,double*,long_long*,int*,double*);
extern double F_FUNC_US(b1_ini,B1_INI)(double*,double*,double*,long_long*,int*,double*);
extern double F_FUNC_US(b2_ini,B2_INI)(double*,double*,double*,long_long*,int*,double*);
extern double F_FUNC_US(b3_ini,B3_INI)(double*,double*,double*,long_long*,int*,double*);
extern double F_FUNC_US(rho_ini,RHO_INI)(double*,double*,double*,long_long*,int*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* p_ini_phys *********************************/
static char doc_f2py_rout_initial_conditions_MHD_p_ini_phys[] = "\
p_phys = p_ini_phys(x,y,z)\n\nWrapper for ``p_ini_phys``.\
\n\nParameters\n----------\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"\nReturns\n-------\n"
"p_phys : float";
/* extern double F_FUNC_US(p_ini_phys,P_INI_PHYS)(double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_p_ini_phys(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double p_ini_phys_return_value=0;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:initial_conditions_MHD.p_ini_phys",\
    capi_kwlist,&x_capi,&y_capi,&z_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"initial_conditions_MHD.p_ini_phys() 2nd argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"initial_conditions_MHD.p_ini_phys() 3rd argument (z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"initial_conditions_MHD.p_ini_phys() 1st argument (x) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  p_ini_phys_return_value = (*f2py_func)(&x,&y,&z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",p_ini_phys_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of p_ini_phys *****************************/

/*********************************** ux_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_ux_ini[] = "\
ux = ux_ini(x,y,z)\n\nWrapper for ``ux_ini``.\
\n\nParameters\n----------\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"\nReturns\n-------\n"
"ux : float";
/* extern double F_FUNC_US(ux_ini,UX_INI)(double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_ux_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double ux_ini_return_value=0;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:initial_conditions_MHD.ux_ini",\
    capi_kwlist,&x_capi,&y_capi,&z_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"initial_conditions_MHD.ux_ini() 2nd argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"initial_conditions_MHD.ux_ini() 3rd argument (z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"initial_conditions_MHD.ux_ini() 1st argument (x) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  ux_ini_return_value = (*f2py_func)(&x,&y,&z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",ux_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of ux_ini *******************************/

/*********************************** uy_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_uy_ini[] = "\
uy = uy_ini(x,y,z)\n\nWrapper for ``uy_ini``.\
\n\nParameters\n----------\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"\nReturns\n-------\n"
"uy : float";
/* extern double F_FUNC_US(uy_ini,UY_INI)(double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_uy_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double uy_ini_return_value=0;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:initial_conditions_MHD.uy_ini",\
    capi_kwlist,&x_capi,&y_capi,&z_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"initial_conditions_MHD.uy_ini() 2nd argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"initial_conditions_MHD.uy_ini() 3rd argument (z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"initial_conditions_MHD.uy_ini() 1st argument (x) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  uy_ini_return_value = (*f2py_func)(&x,&y,&z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",uy_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of uy_ini *******************************/

/*********************************** uz_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_uz_ini[] = "\
uz = uz_ini(x,y,z)\n\nWrapper for ``uz_ini``.\
\n\nParameters\n----------\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"\nReturns\n-------\n"
"uz : float";
/* extern double F_FUNC_US(uz_ini,UZ_INI)(double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_uz_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double uz_ini_return_value=0;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:initial_conditions_MHD.uz_ini",\
    capi_kwlist,&x_capi,&y_capi,&z_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"initial_conditions_MHD.uz_ini() 2nd argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"initial_conditions_MHD.uz_ini() 3rd argument (z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"initial_conditions_MHD.uz_ini() 1st argument (x) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  uz_ini_return_value = (*f2py_func)(&x,&y,&z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",uz_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of uz_ini *******************************/

/*********************************** bx_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_bx_ini[] = "\
bx = bx_ini(x,y,z)\n\nWrapper for ``bx_ini``.\
\n\nParameters\n----------\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"\nReturns\n-------\n"
"bx : float";
/* extern double F_FUNC_US(bx_ini,BX_INI)(double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_bx_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double bx_ini_return_value=0;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:initial_conditions_MHD.bx_ini",\
    capi_kwlist,&x_capi,&y_capi,&z_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"initial_conditions_MHD.bx_ini() 2nd argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"initial_conditions_MHD.bx_ini() 3rd argument (z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"initial_conditions_MHD.bx_ini() 1st argument (x) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  bx_ini_return_value = (*f2py_func)(&x,&y,&z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",bx_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of bx_ini *******************************/

/*********************************** by_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_by_ini[] = "\
by = by_ini(x,y,z)\n\nWrapper for ``by_ini``.\
\n\nParameters\n----------\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"\nReturns\n-------\n"
"by : float";
/* extern double F_FUNC_US(by_ini,BY_INI)(double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_by_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double by_ini_return_value=0;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:initial_conditions_MHD.by_ini",\
    capi_kwlist,&x_capi,&y_capi,&z_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"initial_conditions_MHD.by_ini() 2nd argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"initial_conditions_MHD.by_ini() 3rd argument (z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"initial_conditions_MHD.by_ini() 1st argument (x) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  by_ini_return_value = (*f2py_func)(&x,&y,&z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",by_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of by_ini *******************************/

/*********************************** bz_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_bz_ini[] = "\
bz = bz_ini(x,y,z)\n\nWrapper for ``bz_ini``.\
\n\nParameters\n----------\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"\nReturns\n-------\n"
"bz : float";
/* extern double F_FUNC_US(bz_ini,BZ_INI)(double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_bz_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double bz_ini_return_value=0;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:initial_conditions_MHD.bz_ini",\
    capi_kwlist,&x_capi,&y_capi,&z_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"initial_conditions_MHD.bz_ini() 2nd argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"initial_conditions_MHD.bz_ini() 3rd argument (z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"initial_conditions_MHD.bz_ini() 1st argument (x) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  bz_ini_return_value = (*f2py_func)(&x,&y,&z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",bz_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of bz_ini *******************************/

/******************************** rho_ini_phys ********************************/
static char doc_f2py_rout_initial_conditions_MHD_rho_ini_phys[] = "\
rho_phys = rho_ini_phys(x,y,z)\n\nWrapper for ``rho_ini_phys``.\
\n\nParameters\n----------\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"\nReturns\n-------\n"
"rho_phys : float";
/* extern double F_FUNC_US(rho_ini_phys,RHO_INI_PHYS)(double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_rho_ini_phys(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double rho_ini_phys_return_value=0;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:initial_conditions_MHD.rho_ini_phys",\
    capi_kwlist,&x_capi,&y_capi,&z_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"initial_conditions_MHD.rho_ini_phys() 2nd argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"initial_conditions_MHD.rho_ini_phys() 3rd argument (z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"initial_conditions_MHD.rho_ini_phys() 1st argument (x) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  rho_ini_phys_return_value = (*f2py_func)(&x,&y,&z);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",rho_ini_phys_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of rho_ini_phys ****************************/

/*********************************** p_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_p_ini[] = "\
p_phys = p_ini(xi1,xi2,xi3,kind,params,[n0_params])\n\nWrapper for ``p_ini``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"kind : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"\nReturns\n-------\n"
"p_phys : float";
/* extern double F_FUNC_US(p_ini,P_INI)(double*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_p_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double p_ini_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  long_long kind = 0;
  PyObject *kind_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","kind","params","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:initial_conditions_MHD.p_ini",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&kind_capi,&params_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_MHD.p_ini() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_MHD.p_ini() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind */
    f2py_success = long_long_from_pyobj(&kind,kind_capi,"initial_conditions_MHD.p_ini() 4th argument (kind) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(initial_conditions_MHD_error,"failed in converting 5th argument `params' of initial_conditions_MHD.p_ini to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_MHD.p_ini() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"initial_conditions_MHD.p_ini() 1st keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","1st keyword n0_params","p_ini:n0_params=%d",n0_params) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  p_ini_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&kind,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",p_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind*/
  /* End of cleaning variable kind */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of p_ini ********************************/

/*********************************** u1_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_u1_ini[] = "\
dummy_1890 = u1_ini(xi1,xi2,xi3,kind,params,[n0_params])\n\nWrapper for ``u1_ini``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"kind : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"\nReturns\n-------\n"
"dummy_1890 : float";
/* extern double F_FUNC_US(u1_ini,U1_INI)(double*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_u1_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double u1_ini_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  long_long kind = 0;
  PyObject *kind_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","kind","params","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:initial_conditions_MHD.u1_ini",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&kind_capi,&params_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_MHD.u1_ini() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_MHD.u1_ini() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind */
    f2py_success = long_long_from_pyobj(&kind,kind_capi,"initial_conditions_MHD.u1_ini() 4th argument (kind) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(initial_conditions_MHD_error,"failed in converting 5th argument `params' of initial_conditions_MHD.u1_ini to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_MHD.u1_ini() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"initial_conditions_MHD.u1_ini() 1st keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","1st keyword n0_params","u1_ini:n0_params=%d",n0_params) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  u1_ini_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&kind,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",u1_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind*/
  /* End of cleaning variable kind */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of u1_ini *******************************/

/*********************************** u2_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_u2_ini[] = "\
dummy_5390 = u2_ini(xi1,xi2,xi3,kind,params,[n0_params])\n\nWrapper for ``u2_ini``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"kind : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"\nReturns\n-------\n"
"dummy_5390 : float";
/* extern double F_FUNC_US(u2_ini,U2_INI)(double*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_u2_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double u2_ini_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  long_long kind = 0;
  PyObject *kind_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","kind","params","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:initial_conditions_MHD.u2_ini",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&kind_capi,&params_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_MHD.u2_ini() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_MHD.u2_ini() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind */
    f2py_success = long_long_from_pyobj(&kind,kind_capi,"initial_conditions_MHD.u2_ini() 4th argument (kind) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(initial_conditions_MHD_error,"failed in converting 5th argument `params' of initial_conditions_MHD.u2_ini to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_MHD.u2_ini() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"initial_conditions_MHD.u2_ini() 1st keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","1st keyword n0_params","u2_ini:n0_params=%d",n0_params) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  u2_ini_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&kind,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",u2_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind*/
  /* End of cleaning variable kind */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of u2_ini *******************************/

/*********************************** u3_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_u3_ini[] = "\
dummy_9907 = u3_ini(xi1,xi2,xi3,kind,params,[n0_params])\n\nWrapper for ``u3_ini``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"kind : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"\nReturns\n-------\n"
"dummy_9907 : float";
/* extern double F_FUNC_US(u3_ini,U3_INI)(double*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_u3_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double u3_ini_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  long_long kind = 0;
  PyObject *kind_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","kind","params","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:initial_conditions_MHD.u3_ini",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&kind_capi,&params_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_MHD.u3_ini() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_MHD.u3_ini() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind */
    f2py_success = long_long_from_pyobj(&kind,kind_capi,"initial_conditions_MHD.u3_ini() 4th argument (kind) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(initial_conditions_MHD_error,"failed in converting 5th argument `params' of initial_conditions_MHD.u3_ini to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_MHD.u3_ini() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"initial_conditions_MHD.u3_ini() 1st keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","1st keyword n0_params","u3_ini:n0_params=%d",n0_params) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  u3_ini_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&kind,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",u3_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind*/
  /* End of cleaning variable kind */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of u3_ini *******************************/

/*********************************** b1_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_b1_ini[] = "\
dummy_2755 = b1_ini(xi1,xi2,xi3,kind,params,[n0_params])\n\nWrapper for ``b1_ini``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"kind : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"\nReturns\n-------\n"
"dummy_2755 : float";
/* extern double F_FUNC_US(b1_ini,B1_INI)(double*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_b1_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double b1_ini_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  long_long kind = 0;
  PyObject *kind_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","kind","params","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:initial_conditions_MHD.b1_ini",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&kind_capi,&params_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_MHD.b1_ini() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_MHD.b1_ini() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind */
    f2py_success = long_long_from_pyobj(&kind,kind_capi,"initial_conditions_MHD.b1_ini() 4th argument (kind) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(initial_conditions_MHD_error,"failed in converting 5th argument `params' of initial_conditions_MHD.b1_ini to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_MHD.b1_ini() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"initial_conditions_MHD.b1_ini() 1st keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","1st keyword n0_params","b1_ini:n0_params=%d",n0_params) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  b1_ini_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&kind,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",b1_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind*/
  /* End of cleaning variable kind */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of b1_ini *******************************/

/*********************************** b2_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_b2_ini[] = "\
dummy_1783 = b2_ini(xi1,xi2,xi3,kind,params,[n0_params])\n\nWrapper for ``b2_ini``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"kind : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"\nReturns\n-------\n"
"dummy_1783 : float";
/* extern double F_FUNC_US(b2_ini,B2_INI)(double*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_b2_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double b2_ini_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  long_long kind = 0;
  PyObject *kind_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","kind","params","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:initial_conditions_MHD.b2_ini",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&kind_capi,&params_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_MHD.b2_ini() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_MHD.b2_ini() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind */
    f2py_success = long_long_from_pyobj(&kind,kind_capi,"initial_conditions_MHD.b2_ini() 4th argument (kind) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(initial_conditions_MHD_error,"failed in converting 5th argument `params' of initial_conditions_MHD.b2_ini to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_MHD.b2_ini() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"initial_conditions_MHD.b2_ini() 1st keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","1st keyword n0_params","b2_ini:n0_params=%d",n0_params) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  b2_ini_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&kind,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",b2_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind*/
  /* End of cleaning variable kind */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of b2_ini *******************************/

/*********************************** b3_ini ***********************************/
static char doc_f2py_rout_initial_conditions_MHD_b3_ini[] = "\
dummy_1805 = b3_ini(xi1,xi2,xi3,kind,params,[n0_params])\n\nWrapper for ``b3_ini``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"kind : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"\nReturns\n-------\n"
"dummy_1805 : float";
/* extern double F_FUNC_US(b3_ini,B3_INI)(double*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_b3_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double b3_ini_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  long_long kind = 0;
  PyObject *kind_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","kind","params","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:initial_conditions_MHD.b3_ini",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&kind_capi,&params_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_MHD.b3_ini() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_MHD.b3_ini() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind */
    f2py_success = long_long_from_pyobj(&kind,kind_capi,"initial_conditions_MHD.b3_ini() 4th argument (kind) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(initial_conditions_MHD_error,"failed in converting 5th argument `params' of initial_conditions_MHD.b3_ini to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_MHD.b3_ini() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"initial_conditions_MHD.b3_ini() 1st keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","1st keyword n0_params","b3_ini:n0_params=%d",n0_params) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  b3_ini_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&kind,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",b3_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind*/
  /* End of cleaning variable kind */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of b3_ini *******************************/

/********************************** rho_ini **********************************/
static char doc_f2py_rout_initial_conditions_MHD_rho_ini[] = "\
dummy_5605 = rho_ini(xi1,xi2,xi3,kind,params,[n0_params])\n\nWrapper for ``rho_ini``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"kind : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"\nReturns\n-------\n"
"dummy_5605 : float";
/* extern double F_FUNC_US(rho_ini,RHO_INI)(double*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_initial_conditions_MHD_rho_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double rho_ini_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  long_long kind = 0;
  PyObject *kind_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","kind","params","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:initial_conditions_MHD.rho_ini",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&kind_capi,&params_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_MHD.rho_ini() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_MHD.rho_ini() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind */
    f2py_success = long_long_from_pyobj(&kind,kind_capi,"initial_conditions_MHD.rho_ini() 4th argument (kind) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(initial_conditions_MHD_error,"failed in converting 5th argument `params' of initial_conditions_MHD.rho_ini to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_MHD.rho_ini() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"initial_conditions_MHD.rho_ini() 1st keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","1st keyword n0_params","rho_ini:n0_params=%d",n0_params) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  rho_ini_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&kind,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",rho_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind*/
  /* End of cleaning variable kind */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of rho_ini *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"p_ini_phys",-1,{{-1}},0,(char *)F_FUNC_US(p_ini_phys,P_INI_PHYS),(f2py_init_func)f2py_rout_initial_conditions_MHD_p_ini_phys,doc_f2py_rout_initial_conditions_MHD_p_ini_phys},
  {"ux_ini",-1,{{-1}},0,(char *)F_FUNC_US(ux_ini,UX_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_ux_ini,doc_f2py_rout_initial_conditions_MHD_ux_ini},
  {"uy_ini",-1,{{-1}},0,(char *)F_FUNC_US(uy_ini,UY_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_uy_ini,doc_f2py_rout_initial_conditions_MHD_uy_ini},
  {"uz_ini",-1,{{-1}},0,(char *)F_FUNC_US(uz_ini,UZ_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_uz_ini,doc_f2py_rout_initial_conditions_MHD_uz_ini},
  {"bx_ini",-1,{{-1}},0,(char *)F_FUNC_US(bx_ini,BX_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_bx_ini,doc_f2py_rout_initial_conditions_MHD_bx_ini},
  {"by_ini",-1,{{-1}},0,(char *)F_FUNC_US(by_ini,BY_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_by_ini,doc_f2py_rout_initial_conditions_MHD_by_ini},
  {"bz_ini",-1,{{-1}},0,(char *)F_FUNC_US(bz_ini,BZ_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_bz_ini,doc_f2py_rout_initial_conditions_MHD_bz_ini},
  {"rho_ini_phys",-1,{{-1}},0,(char *)F_FUNC_US(rho_ini_phys,RHO_INI_PHYS),(f2py_init_func)f2py_rout_initial_conditions_MHD_rho_ini_phys,doc_f2py_rout_initial_conditions_MHD_rho_ini_phys},
  {"p_ini",-1,{{-1}},0,(char *)F_FUNC_US(p_ini,P_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_p_ini,doc_f2py_rout_initial_conditions_MHD_p_ini},
  {"u1_ini",-1,{{-1}},0,(char *)F_FUNC_US(u1_ini,U1_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_u1_ini,doc_f2py_rout_initial_conditions_MHD_u1_ini},
  {"u2_ini",-1,{{-1}},0,(char *)F_FUNC_US(u2_ini,U2_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_u2_ini,doc_f2py_rout_initial_conditions_MHD_u2_ini},
  {"u3_ini",-1,{{-1}},0,(char *)F_FUNC_US(u3_ini,U3_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_u3_ini,doc_f2py_rout_initial_conditions_MHD_u3_ini},
  {"b1_ini",-1,{{-1}},0,(char *)F_FUNC_US(b1_ini,B1_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_b1_ini,doc_f2py_rout_initial_conditions_MHD_b1_ini},
  {"b2_ini",-1,{{-1}},0,(char *)F_FUNC_US(b2_ini,B2_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_b2_ini,doc_f2py_rout_initial_conditions_MHD_b2_ini},
  {"b3_ini",-1,{{-1}},0,(char *)F_FUNC_US(b3_ini,B3_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_b3_ini,doc_f2py_rout_initial_conditions_MHD_b3_ini},
  {"rho_ini",-1,{{-1}},0,(char *)F_FUNC_US(rho_ini,RHO_INI),(f2py_init_func)f2py_rout_initial_conditions_MHD_rho_ini,doc_f2py_rout_initial_conditions_MHD_rho_ini},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "initial_conditions_MHD",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_initial_conditions_MHD(void) {
#else
#define RETVAL
PyMODINIT_FUNC initinitial_conditions_MHD(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = initial_conditions_MHD_module = PyModule_Create(&moduledef);
#else
  m = initial_conditions_MHD_module = Py_InitModule("initial_conditions_MHD", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module initial_conditions_MHD (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'initial_conditions_MHD' is auto-generated with f2py (version:2).\nFunctions:\n"
"  p_phys = p_ini_phys(x,y,z)\n"
"  ux = ux_ini(x,y,z)\n"
"  uy = uy_ini(x,y,z)\n"
"  uz = uz_ini(x,y,z)\n"
"  bx = bx_ini(x,y,z)\n"
"  by = by_ini(x,y,z)\n"
"  bz = bz_ini(x,y,z)\n"
"  rho_phys = rho_ini_phys(x,y,z)\n"
"  p_phys = p_ini(xi1,xi2,xi3,kind,params,n0_params=len(params))\n"
"  dummy_1890 = u1_ini(xi1,xi2,xi3,kind,params,n0_params=len(params))\n"
"  dummy_5390 = u2_ini(xi1,xi2,xi3,kind,params,n0_params=len(params))\n"
"  dummy_9907 = u3_ini(xi1,xi2,xi3,kind,params,n0_params=len(params))\n"
"  dummy_2755 = b1_ini(xi1,xi2,xi3,kind,params,n0_params=len(params))\n"
"  dummy_1783 = b2_ini(xi1,xi2,xi3,kind,params,n0_params=len(params))\n"
"  dummy_1805 = b3_ini(xi1,xi2,xi3,kind,params,n0_params=len(params))\n"
"  dummy_5605 = rho_ini(xi1,xi2,xi3,kind,params,n0_params=len(params))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  initial_conditions_MHD_error = PyErr_NewException ("initial_conditions_MHD.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));
















/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"initial_conditions_MHD");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
