/* File: initial_conditions_PICmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Apr  8 06:30:28 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *initial_conditions_PIC_error;
static PyObject *initial_conditions_PIC_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
#ifdef _WIN32
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(initial_conditions_PIC_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = initial_conditions_PIC_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int long_long_from_pyobj(long_long* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyLong_Check(obj)) {
        *v = PyLong_AsLongLong(obj);
        return (!PyErr_Occurred());
    }
    if (PyInt_Check(obj)) {
        *v = (long_long)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = PyLong_AsLongLong(tmp);
        Py_DECREF(tmp);
        return (!PyErr_Occurred());
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (long_long_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = initial_conditions_PIC_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = initial_conditions_PIC_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern double F_FUNC_US(fh_ini_phys,FH_INI_PHYS)(double*,double*,double*,double*,double*,double*);
extern double F_FUNC_US(fh_ini,FH_INI)(double*,double*,double*,double*,double*,double*,long_long*,int*,double*);
extern double F_FUNC_US(g_sampling,G_SAMPLING)(double*,double*,double*,double*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** fh_ini_phys ********************************/
static char doc_f2py_rout_initial_conditions_PIC_fh_ini_phys[] = "\
value = fh_ini_phys(x,y,z,vx,vy,vz)\n\nWrapper for ``fh_ini_phys``.\
\n\nParameters\n----------\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"vx : input float\n"
"vy : input float\n"
"vz : input float\n"
"\nReturns\n-------\n"
"value : float";
/* extern double F_FUNC_US(fh_ini_phys,FH_INI_PHYS)(double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_PIC_fh_ini_phys(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double fh_ini_phys_return_value=0;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  double vx = 0;
  PyObject *vx_capi = Py_None;
  double vy = 0;
  PyObject *vy_capi = Py_None;
  double vz = 0;
  PyObject *vz_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z","vx","vy","vz",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:initial_conditions_PIC.fh_ini_phys",\
    capi_kwlist,&x_capi,&y_capi,&z_capi,&vx_capi,&vy_capi,&vz_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable vz */
    f2py_success = double_from_pyobj(&vz,vz_capi,"initial_conditions_PIC.fh_ini_phys() 6th argument (vz) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"initial_conditions_PIC.fh_ini_phys() 1st argument (x) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vx */
    f2py_success = double_from_pyobj(&vx,vx_capi,"initial_conditions_PIC.fh_ini_phys() 4th argument (vx) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vy */
    f2py_success = double_from_pyobj(&vy,vy_capi,"initial_conditions_PIC.fh_ini_phys() 5th argument (vy) can't be converted to double");
  if (f2py_success) {
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"initial_conditions_PIC.fh_ini_phys() 2nd argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"initial_conditions_PIC.fh_ini_phys() 3rd argument (z) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  fh_ini_phys_return_value = (*f2py_func)(&x,&y,&z,&vx,&vy,&vz);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",fh_ini_phys_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
  } /*if (f2py_success) of vy*/
  /* End of cleaning variable vy */
  } /*if (f2py_success) of vx*/
  /* End of cleaning variable vx */
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of vz*/
  /* End of cleaning variable vz */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of fh_ini_phys *****************************/

/*********************************** fh_ini ***********************************/
static char doc_f2py_rout_initial_conditions_PIC_fh_ini[] = "\
dummy_5092 = fh_ini(xi1,xi2,xi3,vx,vy,vz,kind_map,params_map,[n0_params_map])\n\nWrapper for ``fh_ini``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"vx : input float\n"
"vy : input float\n"
"vz : input float\n"
"kind_map : input long\n"
"params_map : input rank-1 array('d') with bounds (n0_params_map)\n"
"\nOther Parameters\n----------------\n"
"n0_params_map : input int, optional\n    Default: len(params_map)\n"
"\nReturns\n-------\n"
"dummy_5092 : float";
/* extern double F_FUNC_US(fh_ini,FH_INI)(double*,double*,double*,double*,double*,double*,long_long*,int*,double*); */
static PyObject *f2py_rout_initial_conditions_PIC_fh_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,double*,double*,double*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double fh_ini_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  double vx = 0;
  PyObject *vx_capi = Py_None;
  double vy = 0;
  PyObject *vy_capi = Py_None;
  double vz = 0;
  PyObject *vz_capi = Py_None;
  long_long kind_map = 0;
  PyObject *kind_map_capi = Py_None;
  int n0_params_map = 0;
  PyObject *n0_params_map_capi = Py_None;
  double *params_map = NULL;
  npy_intp params_map_Dims[1] = {-1};
  const int params_map_Rank = 1;
  PyArrayObject *capi_params_map_tmp = NULL;
  int capi_params_map_intent = 0;
  PyObject *params_map_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","vx","vy","vz","kind_map","params_map","n0_params_map",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|O:initial_conditions_PIC.fh_ini",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&vx_capi,&vy_capi,&vz_capi,&kind_map_capi,&params_map_capi,&n0_params_map_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable params_map */
  ;
  capi_params_map_intent |= F2PY_INTENT_IN;
  capi_params_map_tmp = array_from_pyobj(NPY_DOUBLE,params_map_Dims,params_map_Rank,capi_params_map_intent,params_map_capi);
  if (capi_params_map_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(initial_conditions_PIC_error,"failed in converting 8th argument `params_map' of initial_conditions_PIC.fh_ini to C/Fortran array" );
  } else {
    params_map = (double *)(PyArray_DATA(capi_params_map_tmp));

  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_PIC.fh_ini() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_PIC.fh_ini() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vy */
    f2py_success = double_from_pyobj(&vy,vy_capi,"initial_conditions_PIC.fh_ini() 5th argument (vy) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vz */
    f2py_success = double_from_pyobj(&vz,vz_capi,"initial_conditions_PIC.fh_ini() 6th argument (vz) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vx */
    f2py_success = double_from_pyobj(&vx,vx_capi,"initial_conditions_PIC.fh_ini() 4th argument (vx) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_PIC.fh_ini() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind_map */
    f2py_success = long_long_from_pyobj(&kind_map,kind_map_capi,"initial_conditions_PIC.fh_ini() 7th argument (kind_map) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable n0_params_map */
  if (n0_params_map_capi == Py_None) n0_params_map = len(params_map); else
    f2py_success = int_from_pyobj(&n0_params_map,n0_params_map_capi,"initial_conditions_PIC.fh_ini() 1st keyword (n0_params_map) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params_map)>=n0_params_map,"len(params_map)>=n0_params_map","1st keyword n0_params_map","fh_ini:n0_params_map=%d",n0_params_map) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  fh_ini_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&vx,&vy,&vz,&kind_map,&n0_params_map,params_map);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",fh_ini_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params_map)>=n0_params_map)*/
  } /*if (f2py_success) of n0_params_map*/
  /* End of cleaning variable n0_params_map */
  } /*if (f2py_success) of kind_map*/
  /* End of cleaning variable kind_map */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of vx*/
  /* End of cleaning variable vx */
  } /*if (f2py_success) of vz*/
  /* End of cleaning variable vz */
  } /*if (f2py_success) of vy*/
  /* End of cleaning variable vy */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_params_map_tmp!=params_map_capi) {
    Py_XDECREF(capi_params_map_tmp); }
  }  /*if (capi_params_map_tmp == NULL) ... else of params_map*/
  /* End of cleaning variable params_map */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of fh_ini *******************************/

/********************************* g_sampling *********************************/
static char doc_f2py_rout_initial_conditions_PIC_g_sampling[] = "\
dummy_5530 = g_sampling(xi1,xi2,xi3,vx,vy,vz)\n\nWrapper for ``g_sampling``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"vx : input float\n"
"vy : input float\n"
"vz : input float\n"
"\nReturns\n-------\n"
"dummy_5530 : float";
/* extern double F_FUNC_US(g_sampling,G_SAMPLING)(double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_initial_conditions_PIC_g_sampling(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double g_sampling_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  double vx = 0;
  PyObject *vx_capi = Py_None;
  double vy = 0;
  PyObject *vy_capi = Py_None;
  double vz = 0;
  PyObject *vz_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","vx","vy","vz",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:initial_conditions_PIC.g_sampling",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&vx_capi,&vy_capi,&vz_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable vz */
    f2py_success = double_from_pyobj(&vz,vz_capi,"initial_conditions_PIC.g_sampling() 6th argument (vz) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vx */
    f2py_success = double_from_pyobj(&vx,vx_capi,"initial_conditions_PIC.g_sampling() 4th argument (vx) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"initial_conditions_PIC.g_sampling() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"initial_conditions_PIC.g_sampling() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"initial_conditions_PIC.g_sampling() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable vy */
    f2py_success = double_from_pyobj(&vy,vy_capi,"initial_conditions_PIC.g_sampling() 5th argument (vy) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  g_sampling_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&vx,&vy,&vz);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",g_sampling_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of vy*/
  /* End of cleaning variable vy */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  } /*if (f2py_success) of vx*/
  /* End of cleaning variable vx */
  } /*if (f2py_success) of vz*/
  /* End of cleaning variable vz */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of g_sampling *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"fh_ini_phys",-1,{{-1}},0,(char *)F_FUNC_US(fh_ini_phys,FH_INI_PHYS),(f2py_init_func)f2py_rout_initial_conditions_PIC_fh_ini_phys,doc_f2py_rout_initial_conditions_PIC_fh_ini_phys},
  {"fh_ini",-1,{{-1}},0,(char *)F_FUNC_US(fh_ini,FH_INI),(f2py_init_func)f2py_rout_initial_conditions_PIC_fh_ini,doc_f2py_rout_initial_conditions_PIC_fh_ini},
  {"g_sampling",-1,{{-1}},0,(char *)F_FUNC_US(g_sampling,G_SAMPLING),(f2py_init_func)f2py_rout_initial_conditions_PIC_g_sampling,doc_f2py_rout_initial_conditions_PIC_g_sampling},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "initial_conditions_PIC",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_initial_conditions_PIC(void) {
#else
#define RETVAL
PyMODINIT_FUNC initinitial_conditions_PIC(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = initial_conditions_PIC_module = PyModule_Create(&moduledef);
#else
  m = initial_conditions_PIC_module = Py_InitModule("initial_conditions_PIC", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module initial_conditions_PIC (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'initial_conditions_PIC' is auto-generated with f2py (version:2).\nFunctions:\n"
"  value = fh_ini_phys(x,y,z,vx,vy,vz)\n"
"  dummy_5092 = fh_ini(xi1,xi2,xi3,vx,vy,vz,kind_map,params_map,n0_params_map=len(params_map))\n"
"  dummy_5530 = g_sampling(xi1,xi2,xi3,vx,vy,vz)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  initial_conditions_PIC_error = PyErr_NewException ("initial_conditions_PIC.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"initial_conditions_PIC");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
