name: Set environment variables for serial unit tests

description: 

runs:
  using: composite
  steps:
    - name: set and export variables
      shell: bash
      run: |
        TESTMON_KEY="testmon-unit"
        UNINSTALL_MPI="pip uninstall -y mpi4py"
        PYTEST_CMD="pytest --testmon ${{ env.TEST_FILES }}"
        echo "TESTMON_KEY=${TESTMON_KEY}" >> $GITHUB_ENV
        echo "UNINSTALL_MPI=${UNINSTALL_MPI}" >> $GITHUB_ENV
        echo "PYTEST_CMD=${PYTEST_CMD}" >> $GITHUB_ENV