geometry : 
      type           : cuboid # geometry (see mappings_3d.py for choices -> kind_map)   
      params_cuboid :
            l1       : 0. # start of slice in eta1
            r1       : 1. # end of slice in eta1, e1 > b1
            l2       : 0.
            r2       : 1.
            l3       : 0.
            r3       : 20.
      params_orthogonal :
            Lx       : 1.
            Ly       : 1.
            alpha    : .1 # x-distortion and y-distortion
            Lz       : 1.
      params_colella :
            Lx       : 1.
            Ly       : 1.
            alpha    : .1 # xy-distortion
            Lz       : 1.
      params_hollow_cyl :
            a1       : .1 # inner radius
            a2       : 1. # outer radius
            R0       : 1. # shift of pole along x-axis and length Lz=2*pi*R0 in z-direction
      params_hollow_torus :
            a1       : .1 # inner radius
            a2       : 1. # minor radius
            R0       : 1. # major radius
      params_spline :
            file     : 'mhd_equil/gvec/sample_gvec_spline_coeffs.hdf5'
            Nel      : [6, 6, 6] # number of grid cells > 1
            p        : [2, 3, 3] # spline degree > 0
            spl_kind : [False, True, True] # spline type: True=periodic, False=clamped
      params_spline_cyl :
            a        : 1. # minor radius
            R0       : 3. # major radius (shift of pole from zero)
            Nel      : [8, 24] # number of grid cells > p
            p        : [3, 3] # spline degree > 1
            spl_kind : [False, True] # spline type: True=periodic, False=clamped
      params_spline_torus :
            a        : 1. # minor radius
            R0       : 3. # major radius
            Nel      : [8, 24] # number of grid cells > p
            p        : [3, 3] # spline degree > 1
            spl_kind : [False, True] # spline type: True=periodic, False=clamped


grid :
      Nel      : [4, 4, 128] # number of grid cells > p
      p        : [2, 2, 3]  # spline degree > 1
      spl_kind : [True, True, True] # spline type: True=periodic, False=clamped
      bc       : [f, f] # normal component boundary conditions in eta_1 for 2-forms (homogeneous Dirichlet = d, free boundary = f)
      nq_el    : [2, 2, 2] # quadrature points per grid cell
      nq_pr    : [2, 2, 2] # quadrature points per histopolation cell (for projection)
      polar    : False # use polar splines


time : 
      dt         : 0.05
      Tend       : 100
      max_time   : 300. # maximum runtime of program in minutes
      split_algo : LieTrotter # 'LieTrotter' or 'Strang'
      
      
fields : 
      init :
            type   : noise # unperturbed, modes_k, modes_mn, eigfun or noise
            coords : physical # how init conds are prescribed: physical, logical or norm_logical (=normed vector fields)
            comps  : all # Default: all, otherwise list of lists: init_comps[i][j]=True means initialize component j of field i.
      init_modes_k : 
            kind : sin # sin or cos 
            k1 : [6.283186]
            k2 : [0.]
            k3 : [0.]
            amp : [0.001]
      init_modes_mn :  
            kind : sin # sin or cos
            modes_m : [1]
            modes_n : [1]
            amp : [0.001]
      init_eigfun : 
            n_tor    : -1 # toroidal mode number
            profiles : False # project equilibrium profiles
            eig_kind : 11 # real (11) or imag (12) part
            eig_freq : 0. # squared eigenfreq.
      init_noise : 
            direction : z     # x, y, z (for 1d) or xy, xz, yz (for 2d)
            amp   : 0.1       # noise amplitude

kinetic :
      species_1 :
            markers :
                  type : fullorbit # fullorbit or driftkinetic
                  ppc : 1000  # particles per 3d grid cell
                  loading :
                        type              : pseudo_random # particle loading
                        seed              : 1234 # seed for random number generator
                        dir_particles     : path_to_particles # directory of particles if loaded externally
                        vth_x             : 1.
                        vth_y             : 1.
                        vth_z             : 1.
                        v0_x              : 0.
                        v0_y              : 0.
                        v0_z              : 0.
                  n_bins        : [32, 32] # number of bins in (x,v) for 2d particle binning.   
                  v_max         : 5. # maximum velocity for binning (in units of v_A)
            init :
                  type   : noise # initialization of particles (noise OR modes_k, modes_mn -> density perturbations)
                  coords : physical # (physical OR logical)
            init_noise :
                  plane : yz # plane of noise (xy, xz, yz)
            init_modes_k :
                  kx : [.8]
                  ky : [0.]
                  kz : [0.] 
                  amp : [0.001]
            init_modes_mn :
                  modes_m : [1]
                  modes_n : [1]
                  amp : [0.001]
            control_var : False # control variate (use delta-f)?
            f_0 :
                  type            : Maxwell_homogen_slab # type of kinetic equilibrium
                  nuh             : 0.05 # ratio hot/bulk number densities (nuh<=0.0 is a run without particles)
                  particle_charge : 1. # in units of elementary charge
                  particle_mass   : 1. # in units of proton mass
                  alpha           : 1. # coupling parameter alpha = Omega_{cp0}/Omega_{A0} 
                  params_Maxwell_homogen_slab :
                        vth_x    : 1. # thermal velocity (in units of v_A)
                        vth_y    : 1.
                        vth_z    : 1.
                        v0_x     : 0.
                        v0_y     : 0.
                        v0_z     : 0.
                        nh0      : 1. # density in units ?
                  params_Maxwell_pitchangle :
                        vth    : 1. # thermal velocity (in units of v_A)
                        alpha0 : 1.
                        delta  : 1.
      species_2 :
            markers :
                  type : fullorbit # fullorbit or driftkinetic
                  ppc : 1000 # particle per 3d grid cell
                  loading :
                        type              : pseudo_random # particle loading
                        seed              : 1234 # seed for random number generator
                        dir_particles     : path_to_particles # directory of particles if loaded externally
                        vth_x             : 1.
                        vth_y             : 1.
                        vth_z             : 1.
                        v0_x              : 0.
                        v0_y              : 0.
                        v0_z              : 0.
                  n_bins        : [32, 32] # number of bins in (x,v) for 2d particle binning.   
                  v_max         : 5. # maximum velocity for binning (in units of v_A)
            init :
                  type   : noise # initialization of particles (noise OR modes_k, modes_mn -> density perturbations)
                  coords : physical # (physical OR logical)
            init_noise :
                  plane : yz # plane of noise (xy, xz, yz)
            init_modes_k :
                  kx : [.8]
                  ky : [0.]
                  kz : [0.] 
                  amp : [0.001]
            init_modes_mn :
                  modes_m : [1]
                  modes_n : [1]
                  amp : [0.001]
            control_var : False # control variate (use delta-f)?
            f_0 :
                  type            : Maxwell_homogen_slab # type of kinetic equilibrium
                  nuh             : 0.05 # ratio hot/bulk number densities (nuh<=0.0 is a run without particles)
                  particle_charge : 1. # in units of elementary charge
                  particle_mass   : 1. # in units of proton mass
                  alpha           : 1. # coupling parameter alpha = Omega_{cp0}/Omega_{A0} 
                  params_Maxwell_homogen_slab :
                        vth_x    : 1. # thermal velocity (in units of v_A)
                        vth_y    : 1.
                        vth_z    : 1.
                        v0_x     : 0.
                        v0_y     : 0.
                        v0_z     : 0.
                        nh0      : 1. # density in units ?
                  params_Maxwell_pitchangle :
                        vth    : 1. # thermal velocity (in units of v_A)
                        alpha0 : 1.
                        delta  : 1.


solvers :
      solver_1 : 
            type : pcg
            pc : fft # null or fft
            tol : 1.e-8
            maxiter : 3000
            info : False
            verbose : False
      solver_2 :
            type : pcg
            pc : fft # null or fft
            tol : 1.e-8
            maxiter : 3000
            info : False
            verbose : False
      solver_3 :
            type : pcg
            pc : fft # null or fft
            tol : 1.e-8
            maxiter : 3000
            info : False
            verbose : False
      solver_4 :
            type : pcg
            pc : fft # null or fft
            tol : 1.e-8
            maxiter : 3000
            info : False
            verbose : False
            
            
# ---- MHD specific parameters
mhd_formulation : H1vec # Hdiv : (U : Hdiv, p : L2), H1vec : (U : H1vec, p : L2)

mhd_equilibrium : 
      type : homogeneous
      homogeneous :
            B0x  : 0.
            B0y  : 0.
            B0z  : 1.
            beta : 0.
      sheared_slab :
            a    : 1.      # minor radius (Lx=a, Ly=2*pi*a) 
            R0   : 3.      # major rarius (Lz=2*pi*R0)
            B0   : 1.      
            q0   : 1.05 
            q1   : 1.80 
            n1   : 0. 
            n2   : 0. 
            na   : 1. 
            beta : 10.
# -----      