grid :
      Nel      : [4, 4, 64] # number of grid cells, >p
      p        : [2, 2, 3]  # spline degree, >1
      spl_kind : [True, True, True] # spline type: True=periodic, False=clamped
      bc       : [[null, null], [null, null], [null, null]] # boundary conditions for N-splines (homogeneous Dirichlet='d')
      nq_el    : [2, 2, 2] # quadrature points per grid cell
      nq_pr    : [2, 2, 2] # quadrature points per histopolation cell (for commuting projectors)


time : 
      dt         : 0.05 # time step
      Tend       : 0.1 # simulation time interval is [0, Tend]
      max_time   : 300. # maximum runtime of program in minutes
      split_algo : LieTrotter # LieTrotter | Strang
      

geometry : 
      type : Cuboid # mapping F (possible types seen below)  
      Cuboid : 
            l1       : 0. # start of interval in eta1
            r1       : 2. # end of interval in eta1, r1>l1
            l2       : 0. # start of interval in eta2
            r2       : 2. # end of interval in eta2, r2>l2
            l3       : 0. # start of interval in eta3
            r3       : 1. # end of interval in eta3, r3>l3
      HollowCylinder :
            a1       : .2 # inner radius
            a2       : 1. # outer radius
            R0       : 0. # shift of pole along x-axis and length Lz=2*pi*R0 in z-direction
            Lz       : 4. # length in third direction   
      Colella :
            Lx       : 2. # length in x-direction
            Ly       : 2. # length in y-direction
            alpha    : .1 # distortion factor
            Lz       : 1. # length in third direction
      Orthogonal :
            Lx       : 2. # length in x-direction
            Ly       : 2. # length in y-direction
            alpha    : .1 # x-distortion and y-distortion
            Lz       : 1. # length in third direction
      HollowTorus :
            a1       : .2 # inner radius
            a2       : 1. # minor radius
            R0       : 3. # major radius
      EllipticCylinder :
            x0       : 0. # center of ellipse
            y0       : 0. # center of ellipse
            z0       : 0. # start of cylinder in third direction
            rx       : 1. # axis length
            ry       : 2. # axis length
            Lz       : 4. # length in third direction
      RotatedEllipticCylinder :
            x0       : 0. # center of ellipse
            y0       : 0. # center of ellipse
            z0       : 0. # start of cylinder in third direction
            r1       : 1. # axis length
            r2       : 2. # axis length
            Lz       : 4. # length in third direction
            th       : .15 # rotation angle in [0, 1), units of 2*pi
      PoweredEllipticCylinder :
            x0       : 0. # center of ellipse
            y0       : 0. # center of ellipse
            z0       : 0. # start of cylinder in third direction
            rx       : 1. # axis length
            ry       : 2. # axis length
            Lz       : 4. # length in third direction
            s        : .5 # power of radial coordinate
      ShafranovShiftCylinder :
            x0       : 0. # center of ellipse
            y0       : 0. # center of ellipse
            z0       : 0. # start of cylinder in third direction
            rx       : 1. # axis length
            ry       : 1. # axis length
            Lz       : 4. # length in third direction
            delta    : .2 # shift factor, should be in [0, 0.1]
      ShafranovSqrtCylinder :
            x0       : 0. # center of ellipse
            y0       : 0. # center of ellipse
            z0       : 0. # start of cylinder in third direction
            rx       : 1. # axis length
            ry       : 1. # axis length
            Lz       : 4. # length in third direction
            delta    : .2 # shift factor, should be in [0, 0.1]
      ShafranovDshapedCylinder :
            x0       : 0. # center of ellipse
            y0       : 0. # center of ellipse
            z0       : 0. # start of cylinder in third direction
            R0       : 2. # base radius
            Lz       : 4. # length in third direction
            delta_x  : .05 # Shafranov shift in x-direction
            delta_y  : .025 # Shafranov shift in y-direction
            delta_gs : .05 # delta = sin(alpha): triangularity, shift of high point
            epsilon_gs : .5 # epsilon: inverse aspect ratio a/r0
            kappa_gs : 2. # Kappa: ellipticity (elongation)
      ShafranovNonAxisSymmCylinder :
            x0       : 0. # center of ellipse
            y0       : 0. # center of ellipse
            z0       : 0. # start of cylinder in third direction
            R0       : 2. # base radius
            Lz       : 4. # length in third direction
            delta_x  : .05 # Shafranov shift in x-direction
            delta_y  : .025 # Shafranov shift in y-direction
            delta_gs : .05 # delta = sin(alpha): triangularity, shift of high point
            epsilon_gs : .5 # epsilon: inverse aspect ratio a/r0
            kappa_gs : 2. # Kappa: ellipticity (elongation)
            xi       : .1 # strength of eta_3 dependence
      Spline :
            file     : 'mhd_equil/gvec/sample_gvec_spline_coeffs.hdf5' # hdf5 file holding spline coeffs
            Nel      : [6, 6, 6] # number of grid cells, >1
            p        : [2, 3, 3] # spline degree, >0
            spl_kind : [False, True, True] # spline type: True=periodic, False=clamped
      PoloidalSplineStraight :
            file     : 'some_file.hdf5' # hdf5 file holding spline coeffs
            Nel      : [8, 24] # number of grid cells, >p
            p        : [3, 3] # spline degree, >1
            spl_kind : [False, True] # spline type: True=periodic, False=clamped
      PoloidalSplineToroidal :
            file     : 'some_file.hdf5' # hdf5 file holding spline coeffs
            Nel      : [8, 24] # number of grid cells, >p
            p        : [3, 3] # spline degree, >1
            spl_kind : [False, True] # spline type: True=periodic, False=clamped
      PoloidalSplineCylinder :
            a        : 1. # minor radius
            R0       : 3. # major radius (shift of pole from zero)
            Nel      : [8, 24] # number of grid cells, >p
            p        : [3, 3] # spline degree, >1
            spl_kind : [False, True] # spline type: True=periodic, False=clamped
      PoloidalSplineTorus :
            a        : 1. # minor radius
            R0       : 3. # major radius
            Nel      : [8, 24] # number of grid cells, >p
            p        : [3, 3] # spline degree, >1
            spl_kind : [False, True] # spline type: True=periodic, False=clamped
            
      
fields : 
      init :
            type   : ModesCos # initial conditions (possible types seen below)
            coords : logical # where init conds are prescribed: physical, logical or norm_logical (=normed vector fields) domain
            comps  : [[True, False, False], [False, False, False]] # One list for each field; True if component should be intitialized with type.
            noise : 
                  direction : z # x, y, z (for 1d) or xy, xz, yz (for 2d), referring to eta-domain if coords=logical (x -> eta_1 etc.)
                  amp : 0.1   # noise amplitude
            ModesSin : 
                  ls : [0] # Integer mode numbers in x or eta_1 (depending on coords)
                  ms : [0] # Integer mode numbers in y or eta_2 (depending on coords)
                  ns : [1] # Integer mode numbers in z or eta_3 (depending on coords)
                  amp : [0.001] # amplitudes of each mode
            ModesCos : 
                  ls : [0] # Integer mode numbers in x or eta_1 (depending on coords)
                  ms : [0] # Integer mode numbers in y or eta_2 (depending on coords)
                  ns : [1] # Integer mode numbers in z or eta_3 (depending on coords)
                  amp : [0.001] # amplitudes of each mode
            TorusModesSin : 
                  ms : [1] # poloidal mode numbers
                  ns : [0] # toroidal mode numbers
                  amp : [0.001] # amplitudes of each mode
                  pfuns : ['sin'] # profile function in eta1-direction ('sin' or 'exp')
                  pfun_params : [null] # Provides [r_0, sigma] parameters for each "exp" profile fucntion, and null for "sin"
            InitialMHDSlab :
                  a  : 1. # minor radius (Lx=a, Ly=2*pi*a)
                  R0 : 3. # major radius (Lz=2*pi*R0)
                  m  : 0  # poloidal (y) mode number
                  n  : 1  # toroidal (z) mode number
                  U  : 0.1 # amplitude of Ux/Uy
                  A  : 0. # amplitude of Uz   
      mhd_u_space : H1vec # Hdiv | H1vec
      mhd_equilibrium : 
            type : HomogenSlab # (possible choices seen below)
            HomogenSlab :
                  B0x  : 0. # magnetic field in x
                  B0y  : 0. # magnetic field in y
                  B0z  : 1. # magnetic field in z
                  beta : 0. # plasma beta = 2*p*mu_0/B^2
                  n0   : 1. # number density
            ShearedSlab :
                  a    : 1. # minor radius (Lx=a, Ly=2*pi*a) 
                  R0   : 3. # major rarius (Lz=2*pi*R0)
                  B0   : 1. # magnetic field in z-direction    
                  q0   : 1.05 # q-value at eta_1 = 0
                  q1   : 1.80 # q-value at eta_1 = 1
                  n1   : 0. # shape factor for number density profile
                  n2   : 0. # shape factor for number density profile
                  na   : 1. # number density at r=a
                  beta : .01 # plasma beta = 2*p*mu_0/B^2
            ScrewPinch :
                  a    : 1. # minor radius (radius of cylinder)
                  R0   : 3. # major radius (Lz = 2*pi*R0)
                  B0   : 1. # magnetic field in z-direction
                  q0   : 1.05 # safety factor at r=0
                  q1   : 1.80 # safety factor at r=a
                  n1   : 0. # shape factor for number density profile 
                  n2   : 0. # shape factor for number density profile 
                  na   : 1. # number density at r=a
                  beta : .01 # plasma beta in % for flat safety factor (ratio of kinetic pressure to magnetic pressure)
            AdhocTorus :
                  a    : 1. # minor radius (radius of cylinder)
                  R0   : 3. # major radius (Lz = 2*pi*R0)
                  B0   : 1. # magnetic field in z-direction
                  q0   : 1.05 # safety factor at r=0
                  q1   : 1.80 # safety factor at r=a
                  n1   : 0. # shape factor for number density profile 
                  n2   : 0. # shape factor for number density profile 
                  na   : 1. # number density at r=a
                  p_kind : .5 # kind of pressure profile (0 : cylindrical limit, 1 : ad hoc)
                  p1     : .1 # shape factor for ad hoc pressure profile
                  p2     : .1 # shape factor for ad hoc pressure profile
                  beta : .01 # plasma beta in % for flat safety factor (ratio of kinetic pressure to magnetic pressure)


kinetic :
      hot_ions :
            markers :
                  ppc         : 100  # number of markers per 3d grid cell
                  eps         : .25 # MPI send/receive buffer (0.1 <= eps <= 1.0)
                  n_save      : 0 # number of markers to be saved during simulation
                  n_bins      : [32, 32] # number of bins in (x,v) for 2d particle binning.   
                  v_max       : 5. # maximum velocity for binning (in units of v_A)
                  control_var : False # control variate (use delta-f)?
                  bc_type     : [periodic, periodic, periodic] # remove, reflect or periodic
                  loading :
                        type          : pseudo_random # particle loading mechanism 
                        seed          : 1234 # seed for random number generator
                        dir_particles : path_to_particles # directory of particles if loaded externally
                        moms_params   : [1., 0., 0., 0., 1., 1., 1.] # moments of Gaussian s3, see background/moms_spec
            attributes :
                  nuh             : 0.05 # ratio hot/bulk number densities (nuh<=0.0 is a run without particles)
                  particle_charge : 1. # in units of elementary charge
                  particle_mass   : 1. # in units of proton mass
                  alpha           : 1. # coupling parameter alpha = Omega_{cp0}/Omega_{A0} 
            background :
                  type : 0 # 0: Maxwellian in 6d
                  moms_spec : [0, 0, 0, 0, 0, 0, 0] # Specifier for the moments n0, u0x, u0y, u0z, vth0x, vth0y, vth0z. 0 means constant
                  moms_params : [1., 0., 0., 0., 1., 1., 1.] # parameters needed to specify the moments
            perturbations : # always in logical position space
                  type : null # null or possible types seen below
                  moms : [n, uz] # which velocity moment to perturb: n, ux, uy, uz, vthx, vthy, vthz
                  Modes_sin : 
                        k1 : [6.283186] # wave vectors in eta_1 
                        k2 : [0.] # wave vectors in eta_2 
                        k3 : [0.] # wave vectors in eta_3 
                        amp : [0.001] # amplitudes
                  Modes_cos : 
                        k1 : [6.283186] # wave vectors in eta_1 
                        k2 : [0.] # wave vectors in eta_2
                        k3 : [0.] # wave vectors in eta_3
                        amp : [0.001] # amplitudes
            

solvers :
      solver_1 : 
            type : pcg
            pc : MassMatrixPreconditioner # null or name of preconditioner class
            tol : 1.e-8
            maxiter : 3000
            info : False
            verbose : False
      solver_2 :
            type : pcg
            pc : MassMatrixPreconditioner # null or name of preconditioner class
            tol : 1.e-8
            maxiter : 3000
            info : False
            verbose : False
                
