/* File: kernels_projectors_local_inimodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Mar 27 12:48:47 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *kernels_projectors_local_ini_error;
static PyObject *kernels_projectors_local_ini_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
#ifdef _WIN32
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(kernels_projectors_local_ini_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = kernels_projectors_local_ini_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int long_long_from_pyobj(long_long* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyLong_Check(obj)) {
        *v = PyLong_AsLongLong(obj);
        return (!PyErr_Occurred());
    }
    if (PyInt_Check(obj)) {
        *v = (long_long)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = PyLong_AsLongLong(tmp);
        Py_DECREF(tmp);
        return (!PyErr_Occurred());
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (long_long_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = kernels_projectors_local_ini_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = kernels_projectors_local_ini_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern double F_FUNC(fun,FUN)(double*,double*,double*,long_long*,long_long*,int*,double*);
extern void F_FUNC_US(kernel_eva,KERNEL_EVA)(int*,long_long*,int*,double*,int*,double*,int*,double*,int*,int*,int*,double*,long_long*,long_long*,int*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ fun ************************************/
static char doc_f2py_rout_kernels_projectors_local_ini_fun[] = "\
value = fun(xi1,xi2,xi3,kind_fun,kind_map,params,[n0_params])\n\nWrapper for ``fun``.\
\n\nParameters\n----------\n"
"xi1 : input float\n"
"xi2 : input float\n"
"xi3 : input float\n"
"kind_fun : input long\n"
"kind_map : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_params : input int, optional\n    Default: len(params)\n"
"\nReturns\n-------\n"
"value : float";
/* extern double F_FUNC(fun,FUN)(double*,double*,double*,long_long*,long_long*,int*,double*); */
static PyObject *f2py_rout_kernels_projectors_local_ini_fun(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           double (*f2py_func)(double*,double*,double*,long_long*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double fun_return_value=0;
  double xi1 = 0;
  PyObject *xi1_capi = Py_None;
  double xi2 = 0;
  PyObject *xi2_capi = Py_None;
  double xi3 = 0;
  PyObject *xi3_capi = Py_None;
  long_long kind_fun = 0;
  PyObject *kind_fun_capi = Py_None;
  long_long kind_map = 0;
  PyObject *kind_map_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"xi1","xi2","xi3","kind_fun","kind_map","params","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|O:kernels_projectors_local_ini.fun",\
    capi_kwlist,&xi1_capi,&xi2_capi,&xi3_capi,&kind_fun_capi,&kind_map_capi,&params_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xi3 */
    f2py_success = double_from_pyobj(&xi3,xi3_capi,"kernels_projectors_local_ini.fun() 3rd argument (xi3) can't be converted to double");
  if (f2py_success) {
  /* Processing variable kind_map */
    f2py_success = long_long_from_pyobj(&kind_map,kind_map_capi,"kernels_projectors_local_ini.fun() 5th argument (kind_map) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable kind_fun */
    f2py_success = long_long_from_pyobj(&kind_fun,kind_fun_capi,"kernels_projectors_local_ini.fun() 4th argument (kind_fun) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_local_ini_error,"failed in converting 6th argument `params' of kernels_projectors_local_ini.fun to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable xi1 */
    f2py_success = double_from_pyobj(&xi1,xi1_capi,"kernels_projectors_local_ini.fun() 1st argument (xi1) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xi2 */
    f2py_success = double_from_pyobj(&xi2,xi2_capi,"kernels_projectors_local_ini.fun() 2nd argument (xi2) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"kernels_projectors_local_ini.fun() 1st keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","1st keyword n0_params","fun:n0_params=%d",n0_params) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  fun_return_value = (*f2py_func)(&xi1,&xi2,&xi3,&kind_fun,&kind_map,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",fun_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*if (f2py_success) of xi2*/
  /* End of cleaning variable xi2 */
  } /*if (f2py_success) of xi1*/
  /* End of cleaning variable xi1 */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind_fun*/
  /* End of cleaning variable kind_fun */
  } /*if (f2py_success) of kind_map*/
  /* End of cleaning variable kind_map */
  } /*if (f2py_success) of xi3*/
  /* End of cleaning variable xi3 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of fun *********************************/

/********************************* kernel_eva *********************************/
static char doc_f2py_rout_kernels_projectors_local_ini_kernel_eva[] = "\
kernel_eva(n,xi1,xi2,xi3,mat_f,kind_fun,kind_map,params,[n0_n,n0_xi1,n0_xi2,n0_xi3,n0_mat_f,n1_mat_f,n2_mat_f,n0_params])\n\nWrapper for ``kernel_eva``.\
\n\nParameters\n----------\n"
"n : input rank-1 array('q') with bounds (n0_n)\n"
"xi1 : input rank-1 array('d') with bounds (n0_xi1)\n"
"xi2 : input rank-1 array('d') with bounds (n0_xi2)\n"
"xi3 : input rank-1 array('d') with bounds (n0_xi3)\n"
"mat_f : in/output rank-3 array('d') with bounds (n0_mat_f,n1_mat_f,n2_mat_f)\n"
"kind_fun : input long\n"
"kind_map : input long\n"
"params : input rank-1 array('d') with bounds (n0_params)\n"
"\nOther Parameters\n----------------\n"
"n0_n : input int, optional\n    Default: len(n)\n"
"n0_xi1 : input int, optional\n    Default: len(xi1)\n"
"n0_xi2 : input int, optional\n    Default: len(xi2)\n"
"n0_xi3 : input int, optional\n    Default: len(xi3)\n"
"n0_mat_f : input int, optional\n    Default: shape(mat_f,0)\n"
"n1_mat_f : input int, optional\n    Default: shape(mat_f,1)\n"
"n2_mat_f : input int, optional\n    Default: shape(mat_f,2)\n"
"n0_params : input int, optional\n    Default: len(params)";
/* extern void F_FUNC_US(kernel_eva,KERNEL_EVA)(int*,long_long*,int*,double*,int*,double*,int*,double*,int*,int*,int*,double*,long_long*,long_long*,int*,double*); */
static PyObject *f2py_rout_kernels_projectors_local_ini_kernel_eva(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,long_long*,int*,double*,int*,double*,int*,double*,int*,int*,int*,double*,long_long*,long_long*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n0_n = 0;
  PyObject *n0_n_capi = Py_None;
  long_long *n = NULL;
  npy_intp n_Dims[1] = {-1};
  const int n_Rank = 1;
  PyArrayObject *capi_n_tmp = NULL;
  int capi_n_intent = 0;
  PyObject *n_capi = Py_None;
  int n0_xi1 = 0;
  PyObject *n0_xi1_capi = Py_None;
  double *xi1 = NULL;
  npy_intp xi1_Dims[1] = {-1};
  const int xi1_Rank = 1;
  PyArrayObject *capi_xi1_tmp = NULL;
  int capi_xi1_intent = 0;
  PyObject *xi1_capi = Py_None;
  int n0_xi2 = 0;
  PyObject *n0_xi2_capi = Py_None;
  double *xi2 = NULL;
  npy_intp xi2_Dims[1] = {-1};
  const int xi2_Rank = 1;
  PyArrayObject *capi_xi2_tmp = NULL;
  int capi_xi2_intent = 0;
  PyObject *xi2_capi = Py_None;
  int n0_xi3 = 0;
  PyObject *n0_xi3_capi = Py_None;
  double *xi3 = NULL;
  npy_intp xi3_Dims[1] = {-1};
  const int xi3_Rank = 1;
  PyArrayObject *capi_xi3_tmp = NULL;
  int capi_xi3_intent = 0;
  PyObject *xi3_capi = Py_None;
  int n0_mat_f = 0;
  PyObject *n0_mat_f_capi = Py_None;
  int n1_mat_f = 0;
  PyObject *n1_mat_f_capi = Py_None;
  int n2_mat_f = 0;
  PyObject *n2_mat_f_capi = Py_None;
  double *mat_f = NULL;
  npy_intp mat_f_Dims[3] = {-1, -1, -1};
  const int mat_f_Rank = 3;
  PyArrayObject *capi_mat_f_tmp = NULL;
  int capi_mat_f_intent = 0;
  PyObject *mat_f_capi = Py_None;
  long_long kind_fun = 0;
  PyObject *kind_fun_capi = Py_None;
  long_long kind_map = 0;
  PyObject *kind_map_capi = Py_None;
  int n0_params = 0;
  PyObject *n0_params_capi = Py_None;
  double *params = NULL;
  npy_intp params_Dims[1] = {-1};
  const int params_Rank = 1;
  PyArrayObject *capi_params_tmp = NULL;
  int capi_params_intent = 0;
  PyObject *params_capi = Py_None;
  static char *capi_kwlist[] = {"n","xi1","xi2","xi3","mat_f","kind_fun","kind_map","params","n0_n","n0_xi1","n0_xi2","n0_xi3","n0_mat_f","n1_mat_f","n2_mat_f","n0_params",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|OOOOOOOO:kernels_projectors_local_ini.kernel_eva",\
    capi_kwlist,&n_capi,&xi1_capi,&xi2_capi,&xi3_capi,&mat_f_capi,&kind_fun_capi,&kind_map_capi,&params_capi,&n0_n_capi,&n0_xi1_capi,&n0_xi2_capi,&n0_xi3_capi,&n0_mat_f_capi,&n1_mat_f_capi,&n2_mat_f_capi,&n0_params_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable kind_map */
    f2py_success = long_long_from_pyobj(&kind_map,kind_map_capi,"kernels_projectors_local_ini.kernel_eva() 7th argument (kind_map) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable n */
  ;
  capi_n_intent |= F2PY_INTENT_IN;
  capi_n_tmp = array_from_pyobj(NPY_LONGLONG,n_Dims,n_Rank,capi_n_intent,n_capi);
  if (capi_n_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_local_ini_error,"failed in converting 1st argument `n' of kernels_projectors_local_ini.kernel_eva to C/Fortran array" );
  } else {
    n = (long_long *)(PyArray_DATA(capi_n_tmp));

  /* Processing variable xi1 */
  ;
  capi_xi1_intent |= F2PY_INTENT_IN;
  capi_xi1_tmp = array_from_pyobj(NPY_DOUBLE,xi1_Dims,xi1_Rank,capi_xi1_intent,xi1_capi);
  if (capi_xi1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_local_ini_error,"failed in converting 2nd argument `xi1' of kernels_projectors_local_ini.kernel_eva to C/Fortran array" );
  } else {
    xi1 = (double *)(PyArray_DATA(capi_xi1_tmp));

  /* Processing variable xi2 */
  ;
  capi_xi2_intent |= F2PY_INTENT_IN;
  capi_xi2_tmp = array_from_pyobj(NPY_DOUBLE,xi2_Dims,xi2_Rank,capi_xi2_intent,xi2_capi);
  if (capi_xi2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_local_ini_error,"failed in converting 3rd argument `xi2' of kernels_projectors_local_ini.kernel_eva to C/Fortran array" );
  } else {
    xi2 = (double *)(PyArray_DATA(capi_xi2_tmp));

  /* Processing variable xi3 */
  ;
  capi_xi3_intent |= F2PY_INTENT_IN;
  capi_xi3_tmp = array_from_pyobj(NPY_DOUBLE,xi3_Dims,xi3_Rank,capi_xi3_intent,xi3_capi);
  if (capi_xi3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_local_ini_error,"failed in converting 4th argument `xi3' of kernels_projectors_local_ini.kernel_eva to C/Fortran array" );
  } else {
    xi3 = (double *)(PyArray_DATA(capi_xi3_tmp));

  /* Processing variable kind_fun */
    f2py_success = long_long_from_pyobj(&kind_fun,kind_fun_capi,"kernels_projectors_local_ini.kernel_eva() 6th argument (kind_fun) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable params */
  ;
  capi_params_intent |= F2PY_INTENT_IN;
  capi_params_tmp = array_from_pyobj(NPY_DOUBLE,params_Dims,params_Rank,capi_params_intent,params_capi);
  if (capi_params_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_local_ini_error,"failed in converting 8th argument `params' of kernels_projectors_local_ini.kernel_eva to C/Fortran array" );
  } else {
    params = (double *)(PyArray_DATA(capi_params_tmp));

  /* Processing variable mat_f */
  ;
  capi_mat_f_intent |= F2PY_INTENT_INOUT;
  capi_mat_f_tmp = array_from_pyobj(NPY_DOUBLE,mat_f_Dims,mat_f_Rank,capi_mat_f_intent,mat_f_capi);
  if (capi_mat_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_local_ini_error,"failed in converting 5th argument `mat_f' of kernels_projectors_local_ini.kernel_eva to C/Fortran array" );
  } else {
    mat_f = (double *)(PyArray_DATA(capi_mat_f_tmp));

  /* Processing variable n0_n */
  if (n0_n_capi == Py_None) n0_n = len(n); else
    f2py_success = int_from_pyobj(&n0_n,n0_n_capi,"kernels_projectors_local_ini.kernel_eva() 1st keyword (n0_n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(n)>=n0_n,"len(n)>=n0_n","1st keyword n0_n","kernel_eva:n0_n=%d",n0_n) {
  /* Processing variable n0_xi2 */
  if (n0_xi2_capi == Py_None) n0_xi2 = len(xi2); else
    f2py_success = int_from_pyobj(&n0_xi2,n0_xi2_capi,"kernels_projectors_local_ini.kernel_eva() 3rd keyword (n0_xi2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(xi2)>=n0_xi2,"len(xi2)>=n0_xi2","3rd keyword n0_xi2","kernel_eva:n0_xi2=%d",n0_xi2) {
  /* Processing variable n1_mat_f */
  if (n1_mat_f_capi == Py_None) n1_mat_f = shape(mat_f,1); else
    f2py_success = int_from_pyobj(&n1_mat_f,n1_mat_f_capi,"kernels_projectors_local_ini.kernel_eva() 6th keyword (n1_mat_f) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(mat_f,1)==n1_mat_f,"shape(mat_f,1)==n1_mat_f","6th keyword n1_mat_f","kernel_eva:n1_mat_f=%d",n1_mat_f) {
  /* Processing variable n0_xi1 */
  if (n0_xi1_capi == Py_None) n0_xi1 = len(xi1); else
    f2py_success = int_from_pyobj(&n0_xi1,n0_xi1_capi,"kernels_projectors_local_ini.kernel_eva() 2nd keyword (n0_xi1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(xi1)>=n0_xi1,"len(xi1)>=n0_xi1","2nd keyword n0_xi1","kernel_eva:n0_xi1=%d",n0_xi1) {
  /* Processing variable n0_params */
  if (n0_params_capi == Py_None) n0_params = len(params); else
    f2py_success = int_from_pyobj(&n0_params,n0_params_capi,"kernels_projectors_local_ini.kernel_eva() 8th keyword (n0_params) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(params)>=n0_params,"len(params)>=n0_params","8th keyword n0_params","kernel_eva:n0_params=%d",n0_params) {
  /* Processing variable n2_mat_f */
  if (n2_mat_f_capi == Py_None) n2_mat_f = shape(mat_f,2); else
    f2py_success = int_from_pyobj(&n2_mat_f,n2_mat_f_capi,"kernels_projectors_local_ini.kernel_eva() 7th keyword (n2_mat_f) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(mat_f,2)==n2_mat_f,"shape(mat_f,2)==n2_mat_f","7th keyword n2_mat_f","kernel_eva:n2_mat_f=%d",n2_mat_f) {
  /* Processing variable n0_xi3 */
  if (n0_xi3_capi == Py_None) n0_xi3 = len(xi3); else
    f2py_success = int_from_pyobj(&n0_xi3,n0_xi3_capi,"kernels_projectors_local_ini.kernel_eva() 4th keyword (n0_xi3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(xi3)>=n0_xi3,"len(xi3)>=n0_xi3","4th keyword n0_xi3","kernel_eva:n0_xi3=%d",n0_xi3) {
  /* Processing variable n0_mat_f */
  if (n0_mat_f_capi == Py_None) n0_mat_f = shape(mat_f,0); else
    f2py_success = int_from_pyobj(&n0_mat_f,n0_mat_f_capi,"kernels_projectors_local_ini.kernel_eva() 5th keyword (n0_mat_f) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(mat_f,0)==n0_mat_f,"shape(mat_f,0)==n0_mat_f","5th keyword n0_mat_f","kernel_eva:n0_mat_f=%d",n0_mat_f) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n0_n,n,&n0_xi1,xi1,&n0_xi2,xi2,&n0_xi3,xi3,&n0_mat_f,&n1_mat_f,&n2_mat_f,mat_f,&kind_fun,&kind_map,&n0_params,params);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(mat_f,0)==n0_mat_f)*/
  } /*if (f2py_success) of n0_mat_f*/
  /* End of cleaning variable n0_mat_f */
  } /*CHECKSCALAR(len(xi3)>=n0_xi3)*/
  } /*if (f2py_success) of n0_xi3*/
  /* End of cleaning variable n0_xi3 */
  } /*CHECKSCALAR(shape(mat_f,2)==n2_mat_f)*/
  } /*if (f2py_success) of n2_mat_f*/
  /* End of cleaning variable n2_mat_f */
  } /*CHECKSCALAR(len(params)>=n0_params)*/
  } /*if (f2py_success) of n0_params*/
  /* End of cleaning variable n0_params */
  } /*CHECKSCALAR(len(xi1)>=n0_xi1)*/
  } /*if (f2py_success) of n0_xi1*/
  /* End of cleaning variable n0_xi1 */
  } /*CHECKSCALAR(shape(mat_f,1)==n1_mat_f)*/
  } /*if (f2py_success) of n1_mat_f*/
  /* End of cleaning variable n1_mat_f */
  } /*CHECKSCALAR(len(xi2)>=n0_xi2)*/
  } /*if (f2py_success) of n0_xi2*/
  /* End of cleaning variable n0_xi2 */
  } /*CHECKSCALAR(len(n)>=n0_n)*/
  } /*if (f2py_success) of n0_n*/
  /* End of cleaning variable n0_n */
  if((PyObject *)capi_mat_f_tmp!=mat_f_capi) {
    Py_XDECREF(capi_mat_f_tmp); }
  }  /*if (capi_mat_f_tmp == NULL) ... else of mat_f*/
  /* End of cleaning variable mat_f */
  if((PyObject *)capi_params_tmp!=params_capi) {
    Py_XDECREF(capi_params_tmp); }
  }  /*if (capi_params_tmp == NULL) ... else of params*/
  /* End of cleaning variable params */
  } /*if (f2py_success) of kind_fun*/
  /* End of cleaning variable kind_fun */
  if((PyObject *)capi_xi3_tmp!=xi3_capi) {
    Py_XDECREF(capi_xi3_tmp); }
  }  /*if (capi_xi3_tmp == NULL) ... else of xi3*/
  /* End of cleaning variable xi3 */
  if((PyObject *)capi_xi2_tmp!=xi2_capi) {
    Py_XDECREF(capi_xi2_tmp); }
  }  /*if (capi_xi2_tmp == NULL) ... else of xi2*/
  /* End of cleaning variable xi2 */
  if((PyObject *)capi_xi1_tmp!=xi1_capi) {
    Py_XDECREF(capi_xi1_tmp); }
  }  /*if (capi_xi1_tmp == NULL) ... else of xi1*/
  /* End of cleaning variable xi1 */
  if((PyObject *)capi_n_tmp!=n_capi) {
    Py_XDECREF(capi_n_tmp); }
  }  /*if (capi_n_tmp == NULL) ... else of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of kind_map*/
  /* End of cleaning variable kind_map */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of kernel_eva *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"fun",-1,{{-1}},0,(char *)F_FUNC(fun,FUN),(f2py_init_func)f2py_rout_kernels_projectors_local_ini_fun,doc_f2py_rout_kernels_projectors_local_ini_fun},
  {"kernel_eva",-1,{{-1}},0,(char *)F_FUNC_US(kernel_eva,KERNEL_EVA),(f2py_init_func)f2py_rout_kernels_projectors_local_ini_kernel_eva,doc_f2py_rout_kernels_projectors_local_ini_kernel_eva},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "kernels_projectors_local_ini",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_kernels_projectors_local_ini(void) {
#else
#define RETVAL
PyMODINIT_FUNC initkernels_projectors_local_ini(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = kernels_projectors_local_ini_module = PyModule_Create(&moduledef);
#else
  m = kernels_projectors_local_ini_module = Py_InitModule("kernels_projectors_local_ini", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module kernels_projectors_local_ini (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'kernels_projectors_local_ini' is auto-generated with f2py (version:2).\nFunctions:\n"
"  value = fun(xi1,xi2,xi3,kind_fun,kind_map,params,n0_params=len(params))\n"
"  kernel_eva(n,xi1,xi2,xi3,mat_f,kind_fun,kind_map,params,n0_n=len(n),n0_xi1=len(xi1),n0_xi2=len(xi2),n0_xi3=len(xi3),n0_mat_f=shape(mat_f,0),n1_mat_f=shape(mat_f,1),n2_mat_f=shape(mat_f,2),n0_params=len(params))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  kernels_projectors_local_ini_error = PyErr_NewException ("kernels_projectors_local_ini.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"kernels_projectors_local_ini");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
