/* File: kernels_projectors_globalmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri Mar 27 14:16:23 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *kernels_projectors_global_error;
static PyObject *kernels_projectors_global_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
#ifdef _WIN32
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(kernels_projectors_global_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int long_long_from_pyobj(long_long* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyLong_Check(obj)) {
        *v = PyLong_AsLongLong(obj);
        return (!PyErr_Occurred());
    }
    if (PyInt_Check(obj)) {
        *v = (long_long)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = PyLong_AsLongLong(tmp);
        Py_DECREF(tmp);
        return (!PyErr_Occurred());
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (long_long_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = kernels_projectors_global_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = kernels_projectors_global_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(kernel_int_1d,KERNEL_INT_1D)(long_long*,int*,double*,int*,double*,int*,double*);
extern void F_FUNC_US(kernel_int_2d,KERNEL_INT_2D)(long_long*,long_long*,int*,double*,int*,double*,int*,int*,double*,int*,double*);
extern void F_FUNC_US(kernel_int_3d,KERNEL_INT_3D)(long_long*,long_long*,long_long*,int*,double*,int*,double*,int*,double*,int*,int*,int*,double*,int*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* kernel_int_1d *******************************/
static char doc_f2py_rout_kernels_projectors_global_kernel_int_1d[] = "\
kernel_int_1d(nq1,w1,mat_f,f_loc,[n0_w1,n0_mat_f,n0_f_loc])\n\nWrapper for ``kernel_int_1d``.\
\n\nParameters\n----------\n"
"nq1 : input long\n"
"w1 : input rank-1 array('d') with bounds (n0_w1)\n"
"mat_f : input rank-1 array('d') with bounds (n0_mat_f)\n"
"f_loc : in/output rank-1 array('d') with bounds (n0_f_loc)\n"
"\nOther Parameters\n----------------\n"
"n0_w1 : input int, optional\n    Default: len(w1)\n"
"n0_mat_f : input int, optional\n    Default: len(mat_f)\n"
"n0_f_loc : input int, optional\n    Default: len(f_loc)";
/* extern void F_FUNC_US(kernel_int_1d,KERNEL_INT_1D)(long_long*,int*,double*,int*,double*,int*,double*); */
static PyObject *f2py_rout_kernels_projectors_global_kernel_int_1d(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(long_long*,int*,double*,int*,double*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  long_long nq1 = 0;
  PyObject *nq1_capi = Py_None;
  int n0_w1 = 0;
  PyObject *n0_w1_capi = Py_None;
  double *w1 = NULL;
  npy_intp w1_Dims[1] = {-1};
  const int w1_Rank = 1;
  PyArrayObject *capi_w1_tmp = NULL;
  int capi_w1_intent = 0;
  PyObject *w1_capi = Py_None;
  int n0_mat_f = 0;
  PyObject *n0_mat_f_capi = Py_None;
  double *mat_f = NULL;
  npy_intp mat_f_Dims[1] = {-1};
  const int mat_f_Rank = 1;
  PyArrayObject *capi_mat_f_tmp = NULL;
  int capi_mat_f_intent = 0;
  PyObject *mat_f_capi = Py_None;
  int n0_f_loc = 0;
  PyObject *n0_f_loc_capi = Py_None;
  double *f_loc = NULL;
  npy_intp f_loc_Dims[1] = {-1};
  const int f_loc_Rank = 1;
  PyArrayObject *capi_f_loc_tmp = NULL;
  int capi_f_loc_intent = 0;
  PyObject *f_loc_capi = Py_None;
  static char *capi_kwlist[] = {"nq1","w1","mat_f","f_loc","n0_w1","n0_mat_f","n0_f_loc",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|OOO:kernels_projectors_global.kernel_int_1d",\
    capi_kwlist,&nq1_capi,&w1_capi,&mat_f_capi,&f_loc_capi,&n0_w1_capi,&n0_mat_f_capi,&n0_f_loc_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nq1 */
    f2py_success = long_long_from_pyobj(&nq1,nq1_capi,"kernels_projectors_global.kernel_int_1d() 1st argument (nq1) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable w1 */
  ;
  capi_w1_intent |= F2PY_INTENT_IN;
  capi_w1_tmp = array_from_pyobj(NPY_DOUBLE,w1_Dims,w1_Rank,capi_w1_intent,w1_capi);
  if (capi_w1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 2nd argument `w1' of kernels_projectors_global.kernel_int_1d to C/Fortran array" );
  } else {
    w1 = (double *)(PyArray_DATA(capi_w1_tmp));

  /* Processing variable f_loc */
  ;
  capi_f_loc_intent |= F2PY_INTENT_INOUT;
  capi_f_loc_tmp = array_from_pyobj(NPY_DOUBLE,f_loc_Dims,f_loc_Rank,capi_f_loc_intent,f_loc_capi);
  if (capi_f_loc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 4th argument `f_loc' of kernels_projectors_global.kernel_int_1d to C/Fortran array" );
  } else {
    f_loc = (double *)(PyArray_DATA(capi_f_loc_tmp));

  /* Processing variable mat_f */
  ;
  capi_mat_f_intent |= F2PY_INTENT_IN;
  capi_mat_f_tmp = array_from_pyobj(NPY_DOUBLE,mat_f_Dims,mat_f_Rank,capi_mat_f_intent,mat_f_capi);
  if (capi_mat_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 3rd argument `mat_f' of kernels_projectors_global.kernel_int_1d to C/Fortran array" );
  } else {
    mat_f = (double *)(PyArray_DATA(capi_mat_f_tmp));

  /* Processing variable n0_mat_f */
  if (n0_mat_f_capi == Py_None) n0_mat_f = len(mat_f); else
    f2py_success = int_from_pyobj(&n0_mat_f,n0_mat_f_capi,"kernels_projectors_global.kernel_int_1d() 2nd keyword (n0_mat_f) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(mat_f)>=n0_mat_f,"len(mat_f)>=n0_mat_f","2nd keyword n0_mat_f","kernel_int_1d:n0_mat_f=%d",n0_mat_f) {
  /* Processing variable n0_f_loc */
  if (n0_f_loc_capi == Py_None) n0_f_loc = len(f_loc); else
    f2py_success = int_from_pyobj(&n0_f_loc,n0_f_loc_capi,"kernels_projectors_global.kernel_int_1d() 3rd keyword (n0_f_loc) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(f_loc)>=n0_f_loc,"len(f_loc)>=n0_f_loc","3rd keyword n0_f_loc","kernel_int_1d:n0_f_loc=%d",n0_f_loc) {
  /* Processing variable n0_w1 */
  if (n0_w1_capi == Py_None) n0_w1 = len(w1); else
    f2py_success = int_from_pyobj(&n0_w1,n0_w1_capi,"kernels_projectors_global.kernel_int_1d() 1st keyword (n0_w1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(w1)>=n0_w1,"len(w1)>=n0_w1","1st keyword n0_w1","kernel_int_1d:n0_w1=%d",n0_w1) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nq1,&n0_w1,w1,&n0_mat_f,mat_f,&n0_f_loc,f_loc);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(w1)>=n0_w1)*/
  } /*if (f2py_success) of n0_w1*/
  /* End of cleaning variable n0_w1 */
  } /*CHECKSCALAR(len(f_loc)>=n0_f_loc)*/
  } /*if (f2py_success) of n0_f_loc*/
  /* End of cleaning variable n0_f_loc */
  } /*CHECKSCALAR(len(mat_f)>=n0_mat_f)*/
  } /*if (f2py_success) of n0_mat_f*/
  /* End of cleaning variable n0_mat_f */
  if((PyObject *)capi_mat_f_tmp!=mat_f_capi) {
    Py_XDECREF(capi_mat_f_tmp); }
  }  /*if (capi_mat_f_tmp == NULL) ... else of mat_f*/
  /* End of cleaning variable mat_f */
  if((PyObject *)capi_f_loc_tmp!=f_loc_capi) {
    Py_XDECREF(capi_f_loc_tmp); }
  }  /*if (capi_f_loc_tmp == NULL) ... else of f_loc*/
  /* End of cleaning variable f_loc */
  if((PyObject *)capi_w1_tmp!=w1_capi) {
    Py_XDECREF(capi_w1_tmp); }
  }  /*if (capi_w1_tmp == NULL) ... else of w1*/
  /* End of cleaning variable w1 */
  } /*if (f2py_success) of nq1*/
  /* End of cleaning variable nq1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of kernel_int_1d ****************************/

/******************************* kernel_int_2d *******************************/
static char doc_f2py_rout_kernels_projectors_global_kernel_int_2d[] = "\
kernel_int_2d(nq1,nq2,w1,w2,mat_f,f_loc,[n0_w1,n0_w2,n0_mat_f,n1_mat_f,n0_f_loc])\n\nWrapper for ``kernel_int_2d``.\
\n\nParameters\n----------\n"
"nq1 : input long\n"
"nq2 : input long\n"
"w1 : input rank-1 array('d') with bounds (n0_w1)\n"
"w2 : input rank-1 array('d') with bounds (n0_w2)\n"
"mat_f : input rank-2 array('d') with bounds (n0_mat_f,n1_mat_f)\n"
"f_loc : in/output rank-1 array('d') with bounds (n0_f_loc)\n"
"\nOther Parameters\n----------------\n"
"n0_w1 : input int, optional\n    Default: len(w1)\n"
"n0_w2 : input int, optional\n    Default: len(w2)\n"
"n0_mat_f : input int, optional\n    Default: shape(mat_f,0)\n"
"n1_mat_f : input int, optional\n    Default: shape(mat_f,1)\n"
"n0_f_loc : input int, optional\n    Default: len(f_loc)";
/* extern void F_FUNC_US(kernel_int_2d,KERNEL_INT_2D)(long_long*,long_long*,int*,double*,int*,double*,int*,int*,double*,int*,double*); */
static PyObject *f2py_rout_kernels_projectors_global_kernel_int_2d(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(long_long*,long_long*,int*,double*,int*,double*,int*,int*,double*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  long_long nq1 = 0;
  PyObject *nq1_capi = Py_None;
  long_long nq2 = 0;
  PyObject *nq2_capi = Py_None;
  int n0_w1 = 0;
  PyObject *n0_w1_capi = Py_None;
  double *w1 = NULL;
  npy_intp w1_Dims[1] = {-1};
  const int w1_Rank = 1;
  PyArrayObject *capi_w1_tmp = NULL;
  int capi_w1_intent = 0;
  PyObject *w1_capi = Py_None;
  int n0_w2 = 0;
  PyObject *n0_w2_capi = Py_None;
  double *w2 = NULL;
  npy_intp w2_Dims[1] = {-1};
  const int w2_Rank = 1;
  PyArrayObject *capi_w2_tmp = NULL;
  int capi_w2_intent = 0;
  PyObject *w2_capi = Py_None;
  int n0_mat_f = 0;
  PyObject *n0_mat_f_capi = Py_None;
  int n1_mat_f = 0;
  PyObject *n1_mat_f_capi = Py_None;
  double *mat_f = NULL;
  npy_intp mat_f_Dims[2] = {-1, -1};
  const int mat_f_Rank = 2;
  PyArrayObject *capi_mat_f_tmp = NULL;
  int capi_mat_f_intent = 0;
  PyObject *mat_f_capi = Py_None;
  int n0_f_loc = 0;
  PyObject *n0_f_loc_capi = Py_None;
  double *f_loc = NULL;
  npy_intp f_loc_Dims[1] = {-1};
  const int f_loc_Rank = 1;
  PyArrayObject *capi_f_loc_tmp = NULL;
  int capi_f_loc_intent = 0;
  PyObject *f_loc_capi = Py_None;
  static char *capi_kwlist[] = {"nq1","nq2","w1","w2","mat_f","f_loc","n0_w1","n0_w2","n0_mat_f","n1_mat_f","n0_f_loc",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OOOOO:kernels_projectors_global.kernel_int_2d",\
    capi_kwlist,&nq1_capi,&nq2_capi,&w1_capi,&w2_capi,&mat_f_capi,&f_loc_capi,&n0_w1_capi,&n0_w2_capi,&n0_mat_f_capi,&n1_mat_f_capi,&n0_f_loc_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nq2 */
    f2py_success = long_long_from_pyobj(&nq2,nq2_capi,"kernels_projectors_global.kernel_int_2d() 2nd argument (nq2) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable w2 */
  ;
  capi_w2_intent |= F2PY_INTENT_IN;
  capi_w2_tmp = array_from_pyobj(NPY_DOUBLE,w2_Dims,w2_Rank,capi_w2_intent,w2_capi);
  if (capi_w2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 4th argument `w2' of kernels_projectors_global.kernel_int_2d to C/Fortran array" );
  } else {
    w2 = (double *)(PyArray_DATA(capi_w2_tmp));

  /* Processing variable w1 */
  ;
  capi_w1_intent |= F2PY_INTENT_IN;
  capi_w1_tmp = array_from_pyobj(NPY_DOUBLE,w1_Dims,w1_Rank,capi_w1_intent,w1_capi);
  if (capi_w1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 3rd argument `w1' of kernels_projectors_global.kernel_int_2d to C/Fortran array" );
  } else {
    w1 = (double *)(PyArray_DATA(capi_w1_tmp));

  /* Processing variable mat_f */
  ;
  capi_mat_f_intent |= F2PY_INTENT_IN;
  capi_mat_f_tmp = array_from_pyobj(NPY_DOUBLE,mat_f_Dims,mat_f_Rank,capi_mat_f_intent,mat_f_capi);
  if (capi_mat_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 5th argument `mat_f' of kernels_projectors_global.kernel_int_2d to C/Fortran array" );
  } else {
    mat_f = (double *)(PyArray_DATA(capi_mat_f_tmp));

  /* Processing variable nq1 */
    f2py_success = long_long_from_pyobj(&nq1,nq1_capi,"kernels_projectors_global.kernel_int_2d() 1st argument (nq1) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable f_loc */
  ;
  capi_f_loc_intent |= F2PY_INTENT_INOUT;
  capi_f_loc_tmp = array_from_pyobj(NPY_DOUBLE,f_loc_Dims,f_loc_Rank,capi_f_loc_intent,f_loc_capi);
  if (capi_f_loc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 6th argument `f_loc' of kernels_projectors_global.kernel_int_2d to C/Fortran array" );
  } else {
    f_loc = (double *)(PyArray_DATA(capi_f_loc_tmp));

  /* Processing variable n0_f_loc */
  if (n0_f_loc_capi == Py_None) n0_f_loc = len(f_loc); else
    f2py_success = int_from_pyobj(&n0_f_loc,n0_f_loc_capi,"kernels_projectors_global.kernel_int_2d() 5th keyword (n0_f_loc) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(f_loc)>=n0_f_loc,"len(f_loc)>=n0_f_loc","5th keyword n0_f_loc","kernel_int_2d:n0_f_loc=%d",n0_f_loc) {
  /* Processing variable n0_w2 */
  if (n0_w2_capi == Py_None) n0_w2 = len(w2); else
    f2py_success = int_from_pyobj(&n0_w2,n0_w2_capi,"kernels_projectors_global.kernel_int_2d() 2nd keyword (n0_w2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(w2)>=n0_w2,"len(w2)>=n0_w2","2nd keyword n0_w2","kernel_int_2d:n0_w2=%d",n0_w2) {
  /* Processing variable n0_mat_f */
  if (n0_mat_f_capi == Py_None) n0_mat_f = shape(mat_f,0); else
    f2py_success = int_from_pyobj(&n0_mat_f,n0_mat_f_capi,"kernels_projectors_global.kernel_int_2d() 3rd keyword (n0_mat_f) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(mat_f,0)==n0_mat_f,"shape(mat_f,0)==n0_mat_f","3rd keyword n0_mat_f","kernel_int_2d:n0_mat_f=%d",n0_mat_f) {
  /* Processing variable n1_mat_f */
  if (n1_mat_f_capi == Py_None) n1_mat_f = shape(mat_f,1); else
    f2py_success = int_from_pyobj(&n1_mat_f,n1_mat_f_capi,"kernels_projectors_global.kernel_int_2d() 4th keyword (n1_mat_f) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(mat_f,1)==n1_mat_f,"shape(mat_f,1)==n1_mat_f","4th keyword n1_mat_f","kernel_int_2d:n1_mat_f=%d",n1_mat_f) {
  /* Processing variable n0_w1 */
  if (n0_w1_capi == Py_None) n0_w1 = len(w1); else
    f2py_success = int_from_pyobj(&n0_w1,n0_w1_capi,"kernels_projectors_global.kernel_int_2d() 1st keyword (n0_w1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(w1)>=n0_w1,"len(w1)>=n0_w1","1st keyword n0_w1","kernel_int_2d:n0_w1=%d",n0_w1) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nq1,&nq2,&n0_w1,w1,&n0_w2,w2,&n0_mat_f,&n1_mat_f,mat_f,&n0_f_loc,f_loc);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(w1)>=n0_w1)*/
  } /*if (f2py_success) of n0_w1*/
  /* End of cleaning variable n0_w1 */
  } /*CHECKSCALAR(shape(mat_f,1)==n1_mat_f)*/
  } /*if (f2py_success) of n1_mat_f*/
  /* End of cleaning variable n1_mat_f */
  } /*CHECKSCALAR(shape(mat_f,0)==n0_mat_f)*/
  } /*if (f2py_success) of n0_mat_f*/
  /* End of cleaning variable n0_mat_f */
  } /*CHECKSCALAR(len(w2)>=n0_w2)*/
  } /*if (f2py_success) of n0_w2*/
  /* End of cleaning variable n0_w2 */
  } /*CHECKSCALAR(len(f_loc)>=n0_f_loc)*/
  } /*if (f2py_success) of n0_f_loc*/
  /* End of cleaning variable n0_f_loc */
  if((PyObject *)capi_f_loc_tmp!=f_loc_capi) {
    Py_XDECREF(capi_f_loc_tmp); }
  }  /*if (capi_f_loc_tmp == NULL) ... else of f_loc*/
  /* End of cleaning variable f_loc */
  } /*if (f2py_success) of nq1*/
  /* End of cleaning variable nq1 */
  if((PyObject *)capi_mat_f_tmp!=mat_f_capi) {
    Py_XDECREF(capi_mat_f_tmp); }
  }  /*if (capi_mat_f_tmp == NULL) ... else of mat_f*/
  /* End of cleaning variable mat_f */
  if((PyObject *)capi_w1_tmp!=w1_capi) {
    Py_XDECREF(capi_w1_tmp); }
  }  /*if (capi_w1_tmp == NULL) ... else of w1*/
  /* End of cleaning variable w1 */
  if((PyObject *)capi_w2_tmp!=w2_capi) {
    Py_XDECREF(capi_w2_tmp); }
  }  /*if (capi_w2_tmp == NULL) ... else of w2*/
  /* End of cleaning variable w2 */
  } /*if (f2py_success) of nq2*/
  /* End of cleaning variable nq2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of kernel_int_2d ****************************/

/******************************* kernel_int_3d *******************************/
static char doc_f2py_rout_kernels_projectors_global_kernel_int_3d[] = "\
kernel_int_3d(nq1,nq2,nq3,w1,w2,w3,mat_f,f_loc,[n0_w1,n0_w2,n0_w3,n0_mat_f,n1_mat_f,n2_mat_f,n0_f_loc])\n\nWrapper for ``kernel_int_3d``.\
\n\nParameters\n----------\n"
"nq1 : input long\n"
"nq2 : input long\n"
"nq3 : input long\n"
"w1 : input rank-1 array('d') with bounds (n0_w1)\n"
"w2 : input rank-1 array('d') with bounds (n0_w2)\n"
"w3 : input rank-1 array('d') with bounds (n0_w3)\n"
"mat_f : input rank-3 array('d') with bounds (n0_mat_f,n1_mat_f,n2_mat_f)\n"
"f_loc : in/output rank-1 array('d') with bounds (n0_f_loc)\n"
"\nOther Parameters\n----------------\n"
"n0_w1 : input int, optional\n    Default: len(w1)\n"
"n0_w2 : input int, optional\n    Default: len(w2)\n"
"n0_w3 : input int, optional\n    Default: len(w3)\n"
"n0_mat_f : input int, optional\n    Default: shape(mat_f,0)\n"
"n1_mat_f : input int, optional\n    Default: shape(mat_f,1)\n"
"n2_mat_f : input int, optional\n    Default: shape(mat_f,2)\n"
"n0_f_loc : input int, optional\n    Default: len(f_loc)";
/* extern void F_FUNC_US(kernel_int_3d,KERNEL_INT_3D)(long_long*,long_long*,long_long*,int*,double*,int*,double*,int*,double*,int*,int*,int*,double*,int*,double*); */
static PyObject *f2py_rout_kernels_projectors_global_kernel_int_3d(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(long_long*,long_long*,long_long*,int*,double*,int*,double*,int*,double*,int*,int*,int*,double*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  long_long nq1 = 0;
  PyObject *nq1_capi = Py_None;
  long_long nq2 = 0;
  PyObject *nq2_capi = Py_None;
  long_long nq3 = 0;
  PyObject *nq3_capi = Py_None;
  int n0_w1 = 0;
  PyObject *n0_w1_capi = Py_None;
  double *w1 = NULL;
  npy_intp w1_Dims[1] = {-1};
  const int w1_Rank = 1;
  PyArrayObject *capi_w1_tmp = NULL;
  int capi_w1_intent = 0;
  PyObject *w1_capi = Py_None;
  int n0_w2 = 0;
  PyObject *n0_w2_capi = Py_None;
  double *w2 = NULL;
  npy_intp w2_Dims[1] = {-1};
  const int w2_Rank = 1;
  PyArrayObject *capi_w2_tmp = NULL;
  int capi_w2_intent = 0;
  PyObject *w2_capi = Py_None;
  int n0_w3 = 0;
  PyObject *n0_w3_capi = Py_None;
  double *w3 = NULL;
  npy_intp w3_Dims[1] = {-1};
  const int w3_Rank = 1;
  PyArrayObject *capi_w3_tmp = NULL;
  int capi_w3_intent = 0;
  PyObject *w3_capi = Py_None;
  int n0_mat_f = 0;
  PyObject *n0_mat_f_capi = Py_None;
  int n1_mat_f = 0;
  PyObject *n1_mat_f_capi = Py_None;
  int n2_mat_f = 0;
  PyObject *n2_mat_f_capi = Py_None;
  double *mat_f = NULL;
  npy_intp mat_f_Dims[3] = {-1, -1, -1};
  const int mat_f_Rank = 3;
  PyArrayObject *capi_mat_f_tmp = NULL;
  int capi_mat_f_intent = 0;
  PyObject *mat_f_capi = Py_None;
  int n0_f_loc = 0;
  PyObject *n0_f_loc_capi = Py_None;
  double *f_loc = NULL;
  npy_intp f_loc_Dims[1] = {-1};
  const int f_loc_Rank = 1;
  PyArrayObject *capi_f_loc_tmp = NULL;
  int capi_f_loc_intent = 0;
  PyObject *f_loc_capi = Py_None;
  static char *capi_kwlist[] = {"nq1","nq2","nq3","w1","w2","w3","mat_f","f_loc","n0_w1","n0_w2","n0_w3","n0_mat_f","n1_mat_f","n2_mat_f","n0_f_loc",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|OOOOOOO:kernels_projectors_global.kernel_int_3d",\
    capi_kwlist,&nq1_capi,&nq2_capi,&nq3_capi,&w1_capi,&w2_capi,&w3_capi,&mat_f_capi,&f_loc_capi,&n0_w1_capi,&n0_w2_capi,&n0_w3_capi,&n0_mat_f_capi,&n1_mat_f_capi,&n2_mat_f_capi,&n0_f_loc_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nq2 */
    f2py_success = long_long_from_pyobj(&nq2,nq2_capi,"kernels_projectors_global.kernel_int_3d() 2nd argument (nq2) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable w2 */
  ;
  capi_w2_intent |= F2PY_INTENT_IN;
  capi_w2_tmp = array_from_pyobj(NPY_DOUBLE,w2_Dims,w2_Rank,capi_w2_intent,w2_capi);
  if (capi_w2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 5th argument `w2' of kernels_projectors_global.kernel_int_3d to C/Fortran array" );
  } else {
    w2 = (double *)(PyArray_DATA(capi_w2_tmp));

  /* Processing variable w1 */
  ;
  capi_w1_intent |= F2PY_INTENT_IN;
  capi_w1_tmp = array_from_pyobj(NPY_DOUBLE,w1_Dims,w1_Rank,capi_w1_intent,w1_capi);
  if (capi_w1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 4th argument `w1' of kernels_projectors_global.kernel_int_3d to C/Fortran array" );
  } else {
    w1 = (double *)(PyArray_DATA(capi_w1_tmp));

  /* Processing variable nq1 */
    f2py_success = long_long_from_pyobj(&nq1,nq1_capi,"kernels_projectors_global.kernel_int_3d() 1st argument (nq1) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable mat_f */
  ;
  capi_mat_f_intent |= F2PY_INTENT_IN;
  capi_mat_f_tmp = array_from_pyobj(NPY_DOUBLE,mat_f_Dims,mat_f_Rank,capi_mat_f_intent,mat_f_capi);
  if (capi_mat_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 7th argument `mat_f' of kernels_projectors_global.kernel_int_3d to C/Fortran array" );
  } else {
    mat_f = (double *)(PyArray_DATA(capi_mat_f_tmp));

  /* Processing variable nq3 */
    f2py_success = long_long_from_pyobj(&nq3,nq3_capi,"kernels_projectors_global.kernel_int_3d() 3rd argument (nq3) can't be converted to long_long");
  if (f2py_success) {
  /* Processing variable f_loc */
  ;
  capi_f_loc_intent |= F2PY_INTENT_INOUT;
  capi_f_loc_tmp = array_from_pyobj(NPY_DOUBLE,f_loc_Dims,f_loc_Rank,capi_f_loc_intent,f_loc_capi);
  if (capi_f_loc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 8th argument `f_loc' of kernels_projectors_global.kernel_int_3d to C/Fortran array" );
  } else {
    f_loc = (double *)(PyArray_DATA(capi_f_loc_tmp));

  /* Processing variable w3 */
  ;
  capi_w3_intent |= F2PY_INTENT_IN;
  capi_w3_tmp = array_from_pyobj(NPY_DOUBLE,w3_Dims,w3_Rank,capi_w3_intent,w3_capi);
  if (capi_w3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(kernels_projectors_global_error,"failed in converting 6th argument `w3' of kernels_projectors_global.kernel_int_3d to C/Fortran array" );
  } else {
    w3 = (double *)(PyArray_DATA(capi_w3_tmp));

  /* Processing variable n0_w3 */
  if (n0_w3_capi == Py_None) n0_w3 = len(w3); else
    f2py_success = int_from_pyobj(&n0_w3,n0_w3_capi,"kernels_projectors_global.kernel_int_3d() 3rd keyword (n0_w3) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(w3)>=n0_w3,"len(w3)>=n0_w3","3rd keyword n0_w3","kernel_int_3d:n0_w3=%d",n0_w3) {
  /* Processing variable n0_f_loc */
  if (n0_f_loc_capi == Py_None) n0_f_loc = len(f_loc); else
    f2py_success = int_from_pyobj(&n0_f_loc,n0_f_loc_capi,"kernels_projectors_global.kernel_int_3d() 7th keyword (n0_f_loc) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(f_loc)>=n0_f_loc,"len(f_loc)>=n0_f_loc","7th keyword n0_f_loc","kernel_int_3d:n0_f_loc=%d",n0_f_loc) {
  /* Processing variable n0_w2 */
  if (n0_w2_capi == Py_None) n0_w2 = len(w2); else
    f2py_success = int_from_pyobj(&n0_w2,n0_w2_capi,"kernels_projectors_global.kernel_int_3d() 2nd keyword (n0_w2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(w2)>=n0_w2,"len(w2)>=n0_w2","2nd keyword n0_w2","kernel_int_3d:n0_w2=%d",n0_w2) {
  /* Processing variable n2_mat_f */
  if (n2_mat_f_capi == Py_None) n2_mat_f = shape(mat_f,2); else
    f2py_success = int_from_pyobj(&n2_mat_f,n2_mat_f_capi,"kernels_projectors_global.kernel_int_3d() 6th keyword (n2_mat_f) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(mat_f,2)==n2_mat_f,"shape(mat_f,2)==n2_mat_f","6th keyword n2_mat_f","kernel_int_3d:n2_mat_f=%d",n2_mat_f) {
  /* Processing variable n0_mat_f */
  if (n0_mat_f_capi == Py_None) n0_mat_f = shape(mat_f,0); else
    f2py_success = int_from_pyobj(&n0_mat_f,n0_mat_f_capi,"kernels_projectors_global.kernel_int_3d() 4th keyword (n0_mat_f) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(mat_f,0)==n0_mat_f,"shape(mat_f,0)==n0_mat_f","4th keyword n0_mat_f","kernel_int_3d:n0_mat_f=%d",n0_mat_f) {
  /* Processing variable n1_mat_f */
  if (n1_mat_f_capi == Py_None) n1_mat_f = shape(mat_f,1); else
    f2py_success = int_from_pyobj(&n1_mat_f,n1_mat_f_capi,"kernels_projectors_global.kernel_int_3d() 5th keyword (n1_mat_f) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(mat_f,1)==n1_mat_f,"shape(mat_f,1)==n1_mat_f","5th keyword n1_mat_f","kernel_int_3d:n1_mat_f=%d",n1_mat_f) {
  /* Processing variable n0_w1 */
  if (n0_w1_capi == Py_None) n0_w1 = len(w1); else
    f2py_success = int_from_pyobj(&n0_w1,n0_w1_capi,"kernels_projectors_global.kernel_int_3d() 1st keyword (n0_w1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(w1)>=n0_w1,"len(w1)>=n0_w1","1st keyword n0_w1","kernel_int_3d:n0_w1=%d",n0_w1) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nq1,&nq2,&nq3,&n0_w1,w1,&n0_w2,w2,&n0_w3,w3,&n0_mat_f,&n1_mat_f,&n2_mat_f,mat_f,&n0_f_loc,f_loc);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(w1)>=n0_w1)*/
  } /*if (f2py_success) of n0_w1*/
  /* End of cleaning variable n0_w1 */
  } /*CHECKSCALAR(shape(mat_f,1)==n1_mat_f)*/
  } /*if (f2py_success) of n1_mat_f*/
  /* End of cleaning variable n1_mat_f */
  } /*CHECKSCALAR(shape(mat_f,0)==n0_mat_f)*/
  } /*if (f2py_success) of n0_mat_f*/
  /* End of cleaning variable n0_mat_f */
  } /*CHECKSCALAR(shape(mat_f,2)==n2_mat_f)*/
  } /*if (f2py_success) of n2_mat_f*/
  /* End of cleaning variable n2_mat_f */
  } /*CHECKSCALAR(len(w2)>=n0_w2)*/
  } /*if (f2py_success) of n0_w2*/
  /* End of cleaning variable n0_w2 */
  } /*CHECKSCALAR(len(f_loc)>=n0_f_loc)*/
  } /*if (f2py_success) of n0_f_loc*/
  /* End of cleaning variable n0_f_loc */
  } /*CHECKSCALAR(len(w3)>=n0_w3)*/
  } /*if (f2py_success) of n0_w3*/
  /* End of cleaning variable n0_w3 */
  if((PyObject *)capi_w3_tmp!=w3_capi) {
    Py_XDECREF(capi_w3_tmp); }
  }  /*if (capi_w3_tmp == NULL) ... else of w3*/
  /* End of cleaning variable w3 */
  if((PyObject *)capi_f_loc_tmp!=f_loc_capi) {
    Py_XDECREF(capi_f_loc_tmp); }
  }  /*if (capi_f_loc_tmp == NULL) ... else of f_loc*/
  /* End of cleaning variable f_loc */
  } /*if (f2py_success) of nq3*/
  /* End of cleaning variable nq3 */
  if((PyObject *)capi_mat_f_tmp!=mat_f_capi) {
    Py_XDECREF(capi_mat_f_tmp); }
  }  /*if (capi_mat_f_tmp == NULL) ... else of mat_f*/
  /* End of cleaning variable mat_f */
  } /*if (f2py_success) of nq1*/
  /* End of cleaning variable nq1 */
  if((PyObject *)capi_w1_tmp!=w1_capi) {
    Py_XDECREF(capi_w1_tmp); }
  }  /*if (capi_w1_tmp == NULL) ... else of w1*/
  /* End of cleaning variable w1 */
  if((PyObject *)capi_w2_tmp!=w2_capi) {
    Py_XDECREF(capi_w2_tmp); }
  }  /*if (capi_w2_tmp == NULL) ... else of w2*/
  /* End of cleaning variable w2 */
  } /*if (f2py_success) of nq2*/
  /* End of cleaning variable nq2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of kernel_int_3d ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"kernel_int_1d",-1,{{-1}},0,(char *)F_FUNC_US(kernel_int_1d,KERNEL_INT_1D),(f2py_init_func)f2py_rout_kernels_projectors_global_kernel_int_1d,doc_f2py_rout_kernels_projectors_global_kernel_int_1d},
  {"kernel_int_2d",-1,{{-1}},0,(char *)F_FUNC_US(kernel_int_2d,KERNEL_INT_2D),(f2py_init_func)f2py_rout_kernels_projectors_global_kernel_int_2d,doc_f2py_rout_kernels_projectors_global_kernel_int_2d},
  {"kernel_int_3d",-1,{{-1}},0,(char *)F_FUNC_US(kernel_int_3d,KERNEL_INT_3D),(f2py_init_func)f2py_rout_kernels_projectors_global_kernel_int_3d,doc_f2py_rout_kernels_projectors_global_kernel_int_3d},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "kernels_projectors_global",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_kernels_projectors_global(void) {
#else
#define RETVAL
PyMODINIT_FUNC initkernels_projectors_global(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = kernels_projectors_global_module = PyModule_Create(&moduledef);
#else
  m = kernels_projectors_global_module = Py_InitModule("kernels_projectors_global", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module kernels_projectors_global (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'kernels_projectors_global' is auto-generated with f2py (version:2).\nFunctions:\n"
"  kernel_int_1d(nq1,w1,mat_f,f_loc,n0_w1=len(w1),n0_mat_f=len(mat_f),n0_f_loc=len(f_loc))\n"
"  kernel_int_2d(nq1,nq2,w1,w2,mat_f,f_loc,n0_w1=len(w1),n0_w2=len(w2),n0_mat_f=shape(mat_f,0),n1_mat_f=shape(mat_f,1),n0_f_loc=len(f_loc))\n"
"  kernel_int_3d(nq1,nq2,nq3,w1,w2,w3,mat_f,f_loc,n0_w1=len(w1),n0_w2=len(w2),n0_w3=len(w3),n0_mat_f=shape(mat_f,0),n1_mat_f=shape(mat_f,1),n2_mat_f=shape(mat_f,2),n0_f_loc=len(f_loc))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  kernels_projectors_global_error = PyErr_NewException ("kernels_projectors_global.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));



/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"kernels_projectors_global");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
