mhd_equils = {
    "HomogenSlab": {
        "type": "HomogenSlab",
        "HomogenSlab": {"B0x": 0.0, "B0y": 0.0, "B0z": 1.0, "beta": 0.1, "n0": 1.0},
    },
    "ShearedSlab": {
        "type": "ShearedSlab",
        "ShearedSlab": {
            "a": 1.0,
            "R0": 3.0,
            "B0": 1.0,
            "q0": 1.05,
            "q1": 1.80,
            "n1": 0.0,
            "n2": 0.0,
            "na": 1.0,
            "beta": 0.1,
        },
    },
    "ScrewPinch": {
        "type": "ScrewPinch",
        "ScrewPinch": {
            "a": 1.0,
            "R0": 3.0,
            "B0": 1.0,
            "q0": 1.05,
            "q1": 1.80,
            "n1": 0.0,
            "n2": 0.0,
            "na": 1.0,
            "beta": 0.1,
        },
    },
    "AdhocTorus": {
        "type": "AdhocTorus",
        "AdhocTorus": {
            "a": 1.0,
            "R0": 3.0,
            "B0": 2.0,
            "q_kind": 0,
            "q0": 1.05,
            "q1": 1.80,
            "n1": 0.5,
            "n2": 1.0,
            "na": 0.2,
            "p_kind": 1,
            "p0": 1.0,
            "p1": 0.1,
            "p2": 0.1,
            "beta": 0.01,
            "psi_k": 3,
            "psi_nel": 50,
        },
    },
    "AdhocTorusQPsi": {
        "type": "AdhocTorusQPsi",
        "AdhocTorusQPsi": {
            "a": 0.361925,
            "R0": 1.0,
            "B0": 1.0,
            "q0": 0.6,
            "q1": 2.5,
            "q0p": 0.78,
            "q1p": 5.00,
            "n1": 0.5,
            "n2": 1.0,
            "na": 0.2,
            "beta": 0.1,
            "p1": 0.25,
            "psi_k": 3,
            "psi_nel": 50,
        },
    },
    "EQDSKequilibrium": {
        "type": "EQDSKequilibrium",
        "EQDSKequilibrium": {
            "rel_path": True,
            "file": "AUGNLED_g031213.00830.high",
            "data_type": 0,
            "p_for_psi": [3, 3],
            "psi_resolution": [25.0, 6.25],
            "p_for_flux": 3,
            "flux_resolution": 50.0,
            "n1": 0.0,
            "n2": 0.0,
            "na": 1.0,
        },
    },
    "GVECequilibrium": {
        "type": "GVECequilibrium",
        "GVECequilibrium": {
            "rel_path": False,
            "dat_file": "/u/maxlin/NMPP/00_codes/updated_struphy/struphy/src/struphy/fields_background/mhd_equil/gvec/ellipstell_v2/newBC_E1D6_M6N6/GVEC_ELLIPSTELL_V2_State_0000_00200000.dat",
            "json_file": None,
            "use_pest": False,
            "use_nfp": True,
            "rmin": 0.0,
            "Nel": [32, 32, 32],
            "p": [3, 3, 3],
        },
    },
    "DESCequilibrium": {
        "type": "DESCequilibrium",
        "DESCequilibrium": {
            "eq_name": None,
            "rel_path": True,
            "use_pest": False,
            "use_nfp": True,
            "rmin": 0.0,
            "Nel": [32, 32, 32],
            "p": [3, 3, 3],
        },
    },
}
