name: Create pull request into struphy-hub/struphy-parameter-files

on:
  pull_request:
    branches:
      - devel
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true  # This is crucial!
          fetch-depth: 5
          path: struphy

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: struphy-hub/struphy-parameter-files
          token: ${{ secrets.STRUPHY_HUB_ACCESS_TOKEN }}
          path: struphy-parameter-files

      - name: Copy examples and push new branch
        run: |
            cd struphy-parameter-files
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b from-struphy-${{ github.ref_name }}-${{ github.event.number }}-${{ github.run_number }}
            cp -r ../struphy/examples/. ./
            git status
            git add .
            git commit -m "Changes to parameter files from struphy (on push to main)"
            git push origin from-struphy-${{ github.ref_name }}-${{ github.event.number }}-${{ github.run_number }}

  create-PR:
    needs: clone-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: struphy-hub/struphy-parameter-files
          token: ${{ secrets.STRUPHY_HUB_ACCESS_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.STRUPHY_HUB_ACCESS_TOKEN }}
          title: 'New parameter files from struphy'
          body: 'This is an auto-generated PR from a Struphy workflow (on push to main).'
          branch: from-struphy-${{ github.ref_name }}-${{ github.event.number }}-${{ github.run_number }}
          branch-suffix: short-commit-hash
          base: 'main'
          draft: false