name: Deploy docs to GitHub Pages

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install prerequisites (Ubuntu)
        uses: ./.github/actions/install/ubuntu-latest
        env:
          FC: ${{ env.FC }}
          CC: ${{ env.CC }}
          CXX: ${{ env.CXX }}

      - name: Install Struphy (dev-doc)
        uses: ./.github/actions/install/install-struphy
        with:
          optional-deps: 'dev,doc'

      - name: Compile Struphy
        uses: ./.github/actions/compile

      - name: Build Sphinx docs
        env:
          STRUPHY_DOCS_SKIP_TUTORIALS: "1"
        run: |
          cd doc
          make html

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Upload built docs
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/_build/html/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
