name: Test documentation build

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: read

concurrency:
  group: "docs-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install prerequisites (Ubuntu)
        uses: ./.github/actions/install/ubuntu-latest
        env:
          FC: ${{ env.FC }}
          CC: ${{ env.CC }}
          CXX: ${{ env.CXX }}

      - name: Install Struphy (dev-doc)
        uses: ./.github/actions/install/install-struphy
        with:
          optional-deps: 'dev,doc'

      - name: Compile Struphy
        uses: ./.github/actions/compile

      - name: Build Sphinx docs
        env:
          STRUPHY_DOCS_SKIP_TUTORIALS: "1"
        run: |
          cd doc
          make html
