name: Reusable workflow for testing

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string

jobs:
  test:
    environment: protected
    runs-on: [self-hosted, protected]
    strategy:
      fail-fast: false
      matrix:
        compile-language: ["fortran", "c"]
        test-type: ["unit", "model", "verification"] #"quickstart", "tutorials"]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Load modules
        shell: bash
        run: |
          module purge
          module load ${{ inputs.modules }}
          module list

      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # Create a virtual environment and install dependencies
      - name: Set up Python environment
        shell: bash
        run: |
          python -m venv env
          source env/bin/activate

      - name: Install Struphy
        shell: bash
        run: |
          source env/bin/activate
          pip install --upgrade pip
          pip install ".[dev,phys,doc]"
          pip list
          struphy -h
          struphy --refresh-models
      
      # Check that mpirun oversubscribing works, doesn't work unless OMPI_MCA_rmaps_base_oversubscribe==1
      - name: Test mpirun
        shell: bash
        run: |
          source env/bin/activate
          echo $OMPI_MCA_rmaps_base_oversubscribe
          echo $PRRTE_MCA_rmaps_base_oversubscribe
          which mpirun
          mpirun --version
          mpirun --oversubscribe --report-bindings -n 4 python -c "from mpi4py import MPI; comm=MPI.COMM_WORLD; print(f'Hello from rank {comm.Get_rank()} of {comm.Get_size()}'); assert comm.Get_size()==4"


      # Compile
      - name: Checkout pyccel version
        shell: bash
        run: |
          source env/bin/activate
          pyccel --version

      - name: Compile kernels
        shell: bash
        run: |
          source env/bin/activate
          struphy compile -y --language ${{ matrix.compile-language }}

      # Run tests
      # - name: Run unit tests
      #   if: matrix.test-type == 'unit'
      #   shell: bash
      #   run: |
      #     struphy test unit

      - name: Run unit tests with MPI
        if: matrix.test-type == 'unit'
        shell: bash
        run: |
          struphy test Maxwell
          struphy test unit --mpi 2

      # - name: Run model tests
      #   if: matrix.test-type == 'model'
      #   shell: bash
      #   run: |
      #     struphy test models

      - name: Run model tests with MPI
        if: matrix.test-type == 'model'
        shell: bash
        run: |
          struphy test Maxwell
          struphy test models --mpi 2

      # - name: Run verification tests
      #   if: matrix.test-type == 'verification'
      #   shell: bash
      #   run: |
      #     struphy test verification

      - name: Run verification tests with MPI
        if: matrix.test-type == 'verification'
        shell: bash
        run: |
          struphy test Maxwell
          struphy test verification --mpi 2
