name: Reusable workflow for testing

on:
  workflow_call:
    inputs:
      runner_tags:
        description: JSON array of runner labels
        required: true
        type: string

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# defaults:
#   run:
#     shell: bash

jobs:
  test:
    # environment: protected
    runs-on: ${{ fromJSON(inputs.runner_tags) }}
    strategy:
      fail-fast: false
      matrix:
        compile-language: ["fortran"] #, "c"]
        # test-type: ["unit", "model", "verification"]

    steps:
      - name: Set strict shell options
        shell: bash
        run: |
          set -euo pipefail

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # - name: Say hello from cluster
      #   shell: bash
      #   run: |
      #     set -euxo pipefail

      #     echo "Hello from cluster!"
      #     pwd
      #     whoami
      #     hostname
      #     which bash
      #     which ssh
      #     python --version
      
      # - name: Print some information
      #   shell: bash
      #   run: |
      #     echo "Current date and time: $(date)"
      #     echo "Current user: $(whoami)"
      #     echo "Current working directory: $(pwd)"
      #     echo "List of files in the current directory:"
      #     ls -l
      #     echo "Python version:"
      #     python --version
      #     echo "SLURM job information:"
      #     squeue -u $(whoami)
      #     curl -fsSL https://raw.githubusercontent.com/max-models/whereami/main/install.sh | bash
      #     export PATH="${HOME}/.local/bin:${PATH}"
      #     whereami

      # - name: Submit SLURM job
      #   shell: bash
      #   run: |
      #     python profiling/submit_diocotron_job.py
