name: Reusable workflow for testing

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string

jobs:
  test:
    environment: protected
    runs-on: [self-hosted, protected]
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     compile-language: ["fortran", "c"]
    #     test-type: ["unit", "model", "verification"] #"quickstart", "tutorials"]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # TODO: maxlin, call with modules input
      - name: Install and run tests
        shell: bash -l
        run: |
          .github/scripts/install_and_test.sh
