name: Scheduled Ubuntu

on:
  push:
    branches:
      - 13-move-each-model-to-its-own-file
  schedule:
    # run at 1 a.m. on Sundays and Wednesdays
    - cron: "0 1 * * 0" 
    - cron: "0 1 * * 3"
  workflow_dispatch:

jobs:
  ubuntu-install-test:
    uses: ./.github/workflows/reusable-testing.yml
    with:
      os: ubuntu-latest