name: ruff

on:
  pull_request:
    branches:
      - devel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Download and run cloc
        run: |
          curl -s https://raw.githubusercontent.com/AlDanial/cloc/master/cloc > cloc
          chmod +x cloc
          ./cloc --version
          ./cloc $(git ls-files)

  # mypy:
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v4

  #     - name: Type checking with mypy
  #       run: |
  #         pip install mypy
  #         mypy src/ || true

  # prospector:
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v4

  #     - name: Code analysis with prospector
  #       run: |
  #         pip install prospector
  #         prospector src/ || true

  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install ruff
        run: pip install ruff==0.16.10

      - name: Check formatting (ruff format)
        run: ruff format --check

      - name: Lint and check import sorting (ruff check)
        run: ruff check
