name: Submodule struphy-tutorials

on:
  pull_request:
    branches:
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check-submodule-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # This is crucial!
          fetch-depth: 5

      - name: Get submodule diff
        uses: ./.github/actions/submodule-diff
        with:
          submod-name: struphy-tutorials
          
      - name: Install prerequisites (Ubuntu)
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/install/ubuntu-latest
      
      - name: Install OSMesa/EGL
        if: env.SUBMOD_CHANGED == 'true'
        run: sudo apt-get install -y libosmesa6 libosmesa6-dev libegl-mesa0
      
      - name: Install Struphy
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/install/install-struphy
        with:
          optional-deps: 'dev,doc'

      - name: Compile Struphy
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/compile
        with:
          language: c
      
      - name: Run workflow if submodule changed (all PR commits)
        if: env.SUBMOD_CHANGED == 'true'
        env:
          PYVISTA_OFF_SCREEN: "true"
          PYVISTA_JUPYTER_BACKEND: "static"
        run: |
          echo "${{ env.SUBMOD_NAME }} has changed, running tests..."
          ls
          cd struphy-tutorials
          jupyter nbconvert --execute --to html tutorial_*.ipynb