name: Submodule struphy-parameter-files

on:
  pull_request:
    branches:
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check-submodule-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # This is crucial!
          fetch-depth: 5

      - name: Get submodule diff
        uses: ./.github/actions/submodule-diff
        with:
          submod-name: struphy-parameter-files

      - name: Install prerequisites (Ubuntu)
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/install/ubuntu-latest
      
      - name: Install Struphy
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/install/install-struphy
        with:
          optional-deps: 'dev,doc'

      - name: Compile Struphy
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/compile
        with:
          language: c
          
      - name: Run weak Landau damping
        if: env.SUBMOD_CHANGED == 'true'
        run: |
          echo "${{ env.SUBMOD_NAME }} has changed, running test..."
          ls
          cd struphy-parameter-files/VlasovAmpereOneSpecies/weak_Landau_damping
          ls
          mpirun -n 2 python params_weak_Landau_damping.py
          python pproc_weak_Landau_damping.py 

      - name: Run strong Landau damping
        if: env.SUBMOD_CHANGED == 'true'
        run: |
          echo "${{ env.SUBMOD_NAME }} has changed, running test..."
          ls
          cd struphy-parameter-files/VlasovAmpereOneSpecies/strong_Landau_damping
          ls
          mpirun -n 2 python params_strong_Landau_damping.py
          python pproc_strong_Landau_damping.py

      - name: Run two-stream instability
        if: env.SUBMOD_CHANGED == 'true'
        run: |
          echo "${{ env.SUBMOD_NAME }} has changed, running test..."
          ls
          cd struphy-parameter-files/VlasovAmpereOneSpecies/two_stream
          ls
          mpirun -n 2 python params_two_stream.py
          python pproc_two_stream.py

      - name: Run bump-on-tail instability
        if: env.SUBMOD_CHANGED == 'true'
        run: |
          echo "${{ env.SUBMOD_NAME }} has changed, running test..."
          ls
          cd struphy-parameter-files/VlasovAmpereOneSpecies/bump_on
          ls
          mpirun -n 2 python params_bump_on.py
          python pproc_bump_on.py
