name: Submodule struphy-parameter-files

on:
  pull_request:
    branches:
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check-submodule-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true  # This is crucial!
          fetch-depth: 5

      - name: Get submodule diff
        uses: ./.github/actions/submodule-diff
        with:
          submod-name: examples

      - name: Check .testmondata 1
        if: env.SUBMOD_CHANGED == 'true'
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Setup cache for testmon
        if: env.SUBMOD_CHANGED == 'true'
        uses: actions/cache@v4
        with:
          path: |
            .testmondata-regression
            .testmondata-regression-mpi
          key: testmon-regression-${{ github.ref_name }}-${{ github.event.number }}-${{ github.run_number }}
          restore-keys: |
            testmon-regression-${{ github.ref_name }}-${{ github.event.number }}-
            testmon-regression-${{ github.ref_name }}
            testmon-regression-devel
            testmon-regression-

      - name: Check .testmondata 2
        if: env.SUBMOD_CHANGED == 'true'
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Install Struphy in Container
        if: env.SUBMOD_CHANGED == 'true'  
        uses: ./.github/actions/install/struphy_in_container

      - name: Reinstall feectools from submodule    
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/install/feectools-submodule
        with:
          env-name: /struphy_fortran_/env_fortran_

      - name: Compile Struphy
        if: env.SUBMOD_CHANGED == 'true'
        run: |
          source /struphy_fortran_/env_fortran_/bin/activate
          struphy compile
          
      - name: Run regression tests (serial)
        if: env.SUBMOD_CHANGED == 'true'
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-regression
        run: |
          echo "${{ env.SUBMOD_NAME }} has changed, running test..."
          ls
          source /struphy_fortran_/env_fortran_/bin/activate
          ls /struphy_fortran_
          pytest -m regression -xvs /struphy_fortran_/src/struphy

      - name: Run regression tests (parallel)
        if: env.SUBMOD_CHANGED == 'true'
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-regression-mpi
        run: |
          echo "${{ env.SUBMOD_NAME }} has changed, running test..."
          ls
          source /struphy_fortran_/env_fortran_/bin/activate
          mpirun -n 1 pytest -m single --testmon-forceselect -xvs --with-mpi --model-name Maxwell /struphy_fortran_/src/struphy
          mpirun -n 2 pytest -m regression --testmon-forceselect -xvs --with-mpi /struphy_fortran_/src/struphy
