name: Submodule struphy-parameter-files

on:
  pull_request:
    branches:
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check-submodule-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # This is crucial!
          fetch-depth: 5

      - name: Get submodule diff
        uses: ./.github/actions/submodule-diff
        with:
          submod-name: examples

      - name: Install prerequisites (Ubuntu)
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/install/ubuntu-latest
      
      - name: Install Struphy
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/install/install-struphy
        with:
          optional-deps: 'dev,doc'

      - name: Compile Struphy
        if: env.SUBMOD_CHANGED == 'true'
        uses: ./.github/actions/compile
        with:
          language: c
          
      - name: Run regression tests (serial)
        if: env.SUBMOD_CHANGED == 'true'
        run: |
          echo "${{ env.SUBMOD_NAME }} has changed, running test..."
          ls
          pytest src/struphy/models/tests/test_regression.py -xvs

      - name: Run regression tests (parallel)
        if: env.SUBMOD_CHANGED == 'true'
        run: |
          echo "${{ env.SUBMOD_NAME }} has changed, running test..."
          ls
          mpirun -n 2 pytest --with-mpi src/struphy/models/tests/test_regression.py -xvs
