name: Submodule struphy-tutorials

on:
  pull_request:
    branches:
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check-submodule-changes:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/struphy-hub/struphy/ubuntu-with-struphy:latest
      credentials:
        username: spossann
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # This is crucial!
          fetch-depth: 5

      - name: Get folder diff
        uses: ./.github/actions/folder-diff
        with:
          folder-name: doc/tutorials

      - name: Install Struphy in Container
        if: env.FOLDER_CHANGED == 'true'  
        uses: ./.github/actions/install/struphy_in_container

      - name: Reinstall feectools from submodule    
        if: env.FOLDER_CHANGED == 'true'
        uses: ./.github/actions/install/feectools-submodule
        with:
          env-name: /struphy_fortran_/env_fortran_

      - name: Compile Struphy
        if: env.FOLDER_CHANGED == 'true'
        run: |
          source /struphy_fortran_/env_fortran_/bin/activate
          struphy compile
      
      - name: Run workflow if submodule changed (all PR commits)
        if: env.FOLDER_CHANGED == 'true'
        env:
          PYVISTA_OFF_SCREEN: "true"
          PYVISTA_JUPYTER_BACKEND: "static"
        run: |
          echo "${{ env.FOLDER_NAME }} has changed, running tests..."
          ls
          source /struphy_fortran_/env_fortran_/bin/activate
          ls /struphy_fortran_
          cd /struphy_fortran_/doc/tutorials
          jupyter nbconvert --execute --to html tutorial_*.ipynb