name: PR - unit tests serial in Container

on:
  pull_request:
    branches:
      - devel
  push:
    branches:
      - devel
  schedule:
    # run at 1 a.m. on Sunday
    - cron: "0 1 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  unit-tests-in-container-with-struphy:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/struphy-hub/struphy/ubuntu-with-struphy:latest
      credentials:
        username: spossann
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true  # This is crucial!
          fetch-depth: 5

      - name: Check .testmondata 1
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Setup cache for testmon
        uses: actions/cache@v4
        with:
          path: |
            .testmondata-unit
          key: testmon-unit-${{ github.ref_name }}-${{ github.event.number }}-${{ github.run_number }}
          restore-keys: |
            testmon-unit-${{ github.ref_name }}-${{ github.event.number }}-
            testmon-unit-${{ github.ref_name }}
            testmon-unit-devel
            testmon-unit-

      - name: Check .testmondata 2
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Install Struphy
        uses: ./.github/actions/install/install-struphy
        with:
          env-name: /struphy_fortran_/env_fortran_
          optional-deps: 'dev'
      
      # - name: Reinstall feectools from submodule
      #   uses: ./.github/actions/install/feectools-submodule
      #   with:
      #     env-name: /struphy_fortran_/env_fortran_

      - name: Compile Struphy
        run: |
          source /struphy_fortran_/env_fortran_/bin/activate
          struphy compile

      - name: Run unit tests
        uses: ./.github/actions/tests/unit
        with:
          env-name: /struphy_fortran_/env_fortran_