name: Cluster workflow
on:
  push:
    branches:
      - protected-install-on-clusters

jobs:
  raven-test:
    uses: ./.github/workflows/reusable-clusters.yml
    with:
      runner_tags: '["self-hosted", "protected", "raven"]'
  tok-test:
    uses: ./.github/workflows/reusable-clusters.yml
    with:
      runner_tags: '["self-hosted", "protected", "tok"]'
