name: PR - unit tests with MPI in Container

on:
  pull_request:
    branches:
      - devel
  push:
    branches:
      - devel
  schedule:
    # run at 1 a.m. on Sunday
    - cron: "0 1 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-with-mpi:
    uses: ./.github/workflows/reusable-unit-testing.yml
    with:
      os: ubuntu-latest
      n-procs: 2
    secrets:
      ghcr-token: ${{ secrets.GHCR_TOKEN }}