name: Cluster workflow
on:
  push:
    branches:
      - protected-install-on-clusters

jobs:
  Raven:
    uses: ./.github/workflows/reusable-clusters.yml
    with:
      runner_tags: '["self-hosted", "protected", "raven"]'
  
  Viper:
    uses: ./.github/workflows/reusable-clusters.yml
    with:
      runner_tags: '["self-hosted", "protected", "viper"]'
  TOK:
    uses: ./.github/workflows/reusable-clusters.yml
    with:
      runner_tags: '["self-hosted", "protected", "tok"]'
  
  Pitagora:
    uses: ./.github/workflows/reusable-clusters.yml
    with:
      runner_tags: '["self-hosted", "protected", "pitagora"]'
