name: PR - unit tests with MPI in Container

on:
  pull_request:
    branches:
      - devel
  schedule:
    # run at 1 a.m. on Sunday
    - cron: "0 1 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-with-mpi:
    name: Unit tests (${{ matrix.n-procs }} ranks)
    uses: ./.github/workflows/reusable-unit-testing.yml
    strategy:
      fail-fast: false
      matrix:
        n-procs: [1, 2, 4]
    with:
      os: ubuntu-latest
      n-procs: ${{ matrix.n-procs }}
    secrets:
      ghcr-token: ${{ secrets.GHCR_TOKEN }}
